const REAL NOSIMDa6 = commondata->a6;                                  // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a6
MAYBE_UNUSED const REAL_SIMD_ARRAY a6 = ConstSIMD(NOSIMDa6);           // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a6
const REAL NOSIMDa_1_NQC = commondata->a_1_NQC;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_1_NQC
MAYBE_UNUSED const REAL_SIMD_ARRAY a_1_NQC = ConstSIMD(NOSIMDa_1_NQC); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_1_NQC
const REAL NOSIMDa_2_NQC = commondata->a_2_NQC;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_2_NQC
MAYBE_UNUSED const REAL_SIMD_ARRAY a_2_NQC = ConstSIMD(NOSIMDa_2_NQC); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_2_NQC
const REAL NOSIMDa_3_NQC = commondata->a_3_NQC;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_3_NQC
MAYBE_UNUSED const REAL_SIMD_ARRAY a_3_NQC = ConstSIMD(NOSIMDa_3_NQC); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_3_NQC
const REAL NOSIMDa_f = commondata->a_f;                                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_f
MAYBE_UNUSED const REAL_SIMD_ARRAY a_f = ConstSIMD(NOSIMDa_f);         // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::a_f
const REAL NOSIMDb_1_NQC = commondata->b_1_NQC;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::b_1_NQC
MAYBE_UNUSED const REAL_SIMD_ARRAY b_1_NQC = ConstSIMD(NOSIMDb_1_NQC); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::b_1_NQC
const REAL NOSIMDb_2_NQC = commondata->b_2_NQC;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::b_2_NQC
MAYBE_UNUSED const REAL_SIMD_ARRAY b_2_NQC = ConstSIMD(NOSIMDb_2_NQC); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::b_2_NQC
const REAL NOSIMDchi1 = commondata->chi1;                              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::chi1
MAYBE_UNUSED const REAL_SIMD_ARRAY chi1 = ConstSIMD(NOSIMDchi1);       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::chi1
const REAL NOSIMDchi2 = commondata->chi2;                              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::chi2
MAYBE_UNUSED const REAL_SIMD_ARRAY chi2 = ConstSIMD(NOSIMDchi2);       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::chi2
const REAL NOSIMDDelta_t = commondata->Delta_t;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Delta_t
MAYBE_UNUSED const REAL_SIMD_ARRAY Delta_t = ConstSIMD(NOSIMDDelta_t); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Delta_t
const REAL NOSIMDdHreal_dpphi = commondata->dHreal_dpphi;              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dpphi
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dpphi =
    ConstSIMD(NOSIMDdHreal_dpphi);                                  // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dpphi
const REAL NOSIMDdHreal_dpphi_circ = commondata->dHreal_dpphi_circ; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dpphi_circ
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dpphi_circ =
    ConstSIMD(NOSIMDdHreal_dpphi_circ);                       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dpphi_circ
const REAL NOSIMDdHreal_dprstar = commondata->dHreal_dprstar; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dprstar
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dprstar =
    ConstSIMD(NOSIMDdHreal_dprstar);                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dprstar
const REAL NOSIMDdHreal_dr = commondata->dHreal_dr; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dr = ConstSIMD(NOSIMDdHreal_dr); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr
const REAL NOSIMDdHreal_dr_circ = commondata->dHreal_dr_circ; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_circ
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dr_circ =
    ConstSIMD(NOSIMDdHreal_dr_circ);                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_circ
const REAL NOSIMDdHreal_dr_dpphi = commondata->dHreal_dr_dpphi; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_dpphi
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dr_dpphi =
    ConstSIMD(NOSIMDdHreal_dr_dpphi);                     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_dpphi
const REAL NOSIMDdHreal_dr_dr = commondata->dHreal_dr_dr; // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_dr
MAYBE_UNUSED const REAL_SIMD_ARRAY dHreal_dr_dr =
    ConstSIMD(NOSIMDdHreal_dr_dr);                                 // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dHreal_dr_dr
const REAL NOSIMDdSO = commondata->dSO;                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dSO
MAYBE_UNUSED const REAL_SIMD_ARRAY dSO = ConstSIMD(NOSIMDdSO);     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dSO
const REAL NOSIMDdT = commondata->dT;                              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dT
MAYBE_UNUSED const REAL_SIMD_ARRAY dT = ConstSIMD(NOSIMDdT);       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dT
const REAL NOSIMDdt = commondata->dt;                              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dt
MAYBE_UNUSED const REAL_SIMD_ARRAY dt = ConstSIMD(NOSIMDdt);       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::dt
const REAL NOSIMDflux = commondata->flux;                          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::flux
MAYBE_UNUSED const REAL_SIMD_ARRAY flux = ConstSIMD(NOSIMDflux);   // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::flux
const REAL NOSIMDHreal = commondata->Hreal;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Hreal
MAYBE_UNUSED const REAL_SIMD_ARRAY Hreal = ConstSIMD(NOSIMDHreal); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Hreal
const REAL NOSIMDinitial_omega = commondata->initial_omega;        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::initial_omega
MAYBE_UNUSED const REAL_SIMD_ARRAY initial_omega =
    ConstSIMD(NOSIMDinitial_omega);                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::initial_omega
const REAL NOSIMDm1 = commondata->m1;                          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::m1
MAYBE_UNUSED const REAL_SIMD_ARRAY m1 = ConstSIMD(NOSIMDm1);   // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::m1
const REAL NOSIMDm2 = commondata->m2;                          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::m2
MAYBE_UNUSED const REAL_SIMD_ARRAY m2 = ConstSIMD(NOSIMDm2);   // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::m2
const REAL NOSIMDM_f = commondata->M_f;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::M_f
MAYBE_UNUSED const REAL_SIMD_ARRAY M_f = ConstSIMD(NOSIMDM_f); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::M_f
const REAL NOSIMDmass_ratio = commondata->mass_ratio;          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::mass_ratio
MAYBE_UNUSED const REAL_SIMD_ARRAY mass_ratio = ConstSIMD(NOSIMDmass_ratio); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::mass_ratio
const REAL NOSIMDnr_amp_1 = commondata->nr_amp_1;                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_1
MAYBE_UNUSED const REAL_SIMD_ARRAY nr_amp_1 = ConstSIMD(NOSIMDnr_amp_1);     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_1
const REAL NOSIMDnr_amp_2 = commondata->nr_amp_2;                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_2
MAYBE_UNUSED const REAL_SIMD_ARRAY nr_amp_2 = ConstSIMD(NOSIMDnr_amp_2);     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_2
const REAL NOSIMDnr_amp_3 = commondata->nr_amp_3;                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_3
MAYBE_UNUSED const REAL_SIMD_ARRAY nr_amp_3 = ConstSIMD(NOSIMDnr_amp_3);     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_amp_3
const REAL NOSIMDnr_omega_1 = commondata->nr_omega_1;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_omega_1
MAYBE_UNUSED const REAL_SIMD_ARRAY nr_omega_1 = ConstSIMD(NOSIMDnr_omega_1); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_omega_1
const REAL NOSIMDnr_omega_2 = commondata->nr_omega_2;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_omega_2
MAYBE_UNUSED const REAL_SIMD_ARRAY nr_omega_2 = ConstSIMD(NOSIMDnr_omega_2); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::nr_omega_2
MAYBE_UNUSED const int NUMGRIDS = commondata->NUMGRIDS;                      // nrpy.grid::NUMGRIDS
const REAL NOSIMDOmega_circ = commondata->Omega_circ;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Omega_circ
MAYBE_UNUSED const REAL_SIMD_ARRAY Omega_circ = ConstSIMD(NOSIMDOmega_circ); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::Omega_circ
const REAL NOSIMDomega_qnm = commondata->omega_qnm;                          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::omega_qnm
MAYBE_UNUSED const REAL_SIMD_ARRAY omega_qnm = ConstSIMD(NOSIMDomega_qnm);   // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::omega_qnm
const REAL NOSIMDphi = commondata->phi;                                      // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::phi
MAYBE_UNUSED const REAL_SIMD_ARRAY phi = ConstSIMD(NOSIMDphi);               // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::phi
const REAL NOSIMDpphi = commondata->pphi;                                    // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::pphi
MAYBE_UNUSED const REAL_SIMD_ARRAY pphi = ConstSIMD(NOSIMDpphi);             // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::pphi
const REAL NOSIMDprstar = commondata->prstar;                                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::prstar
MAYBE_UNUSED const REAL_SIMD_ARRAY prstar = ConstSIMD(NOSIMDprstar);         // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::prstar
const REAL NOSIMDr = commondata->r;                                          // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r
MAYBE_UNUSED const REAL_SIMD_ARRAY r = ConstSIMD(NOSIMDr);                   // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r
const REAL NOSIMDr_ISCO = commondata->r_ISCO;                                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r_ISCO
MAYBE_UNUSED const REAL_SIMD_ARRAY r_ISCO = ConstSIMD(NOSIMDr_ISCO);         // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r_ISCO
const REAL NOSIMDr_stop = commondata->r_stop;                                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r_stop
MAYBE_UNUSED const REAL_SIMD_ARRAY r_stop = ConstSIMD(NOSIMDr_stop);         // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::r_stop
const REAL NOSIMDt_attach = commondata->t_attach;                            // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_attach
MAYBE_UNUSED const REAL_SIMD_ARRAY t_attach = ConstSIMD(NOSIMDt_attach);     // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_attach
const REAL NOSIMDt_ISCO = commondata->t_ISCO;                                // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_ISCO
MAYBE_UNUSED const REAL_SIMD_ARRAY t_ISCO = ConstSIMD(NOSIMDt_ISCO);         // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_ISCO
const REAL NOSIMDt_stepback = commondata->t_stepback;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_stepback
MAYBE_UNUSED const REAL_SIMD_ARRAY t_stepback = ConstSIMD(NOSIMDt_stepback); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::t_stepback
const REAL NOSIMDtau_qnm = commondata->tau_qnm;                              // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::tau_qnm
MAYBE_UNUSED const REAL_SIMD_ARRAY tau_qnm = ConstSIMD(NOSIMDtau_qnm);       // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::tau_qnm
const REAL NOSIMDtotal_mass = commondata->total_mass;                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::total_mass
MAYBE_UNUSED const REAL_SIMD_ARRAY total_mass = ConstSIMD(NOSIMDtotal_mass); // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::total_mass
const REAL NOSIMDxi = commondata->xi;                                        // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::xi
MAYBE_UNUSED const REAL_SIMD_ARRAY xi = ConstSIMD(NOSIMDxi);                 // nrpy.infrastructures.BHaH.seobnr.SEOBNR_C_codegen_library::xi
