"""
Register CFunction for computing SEOBNRv5 co-precessing rotations across a timeseries.

Authors:
Suchindram Dasgupta
sd00113 at mix dot wvu dot edu

Zachariah B. Etienne
zachetie at gmail *dot com
"""

from inspect import currentframe as cfr
from types import FrameType as FT
from typing import Union, cast

import nrpy.c_codegen as ccg
import nrpy.c_function as cfc
import nrpy.equations.seobnr.SEOBNRv5_coprecessing_rotations_quantities as seobnr_rot
import nrpy.helpers.parallel_codegen as pcg


def register_CFunction_SEOBNRv5_coprecessing_rotations() -> (
    Union[None, pcg.NRPyEnv_type]
):
    """
    Register CFunction for evaluating the inertial GW polarizations from co-precessing modes.

    This generates a highly optimized C-loop that processes arrays of Euler angles
    and complex waveform modes, applying Wigner small-d rotations to emit
    the real inertial polarizations h_+ and h_x.

    :return: None if in registration phase, else the updated NRPy environment.
    """
    if pcg.pcg_registration_phase():
        pcg.register_func_call(f"{__name__}.{cast(FT, cfr()).f_code.co_name}", locals())
        return None

    # Step 1: Initialize the symbolic equations using default SEOBNRv5 modes.
    modes = [(2, 2), (2, 1), (3, 3), (3, 2), (4, 4), (4, 3), (5, 5)]
    rot = seobnr_rot.SEOBNRv5_Coprecessing_Rotations(modes=modes)

    # Step 2: Generate pure-real C code for the generic and pole branches.
    pre_code = ccg.c_codegen(
        [rot.M33],
        ["M33"],
        verbose=False,
        include_braces=False,
    )

    generic_code = ccg.c_codegen(
        [rot.h_plus_I_generic, rot.h_cross_I_generic],
        ["h_plus_I", "h_cross_I"],
        verbose=False,
        include_braces=False,
    )

    pole_pos_code = ccg.c_codegen(
        [rot.h_plus_I_pole_pos, rot.h_cross_I_pole_pos],
        ["h_plus_I", "h_cross_I"],
        verbose=False,
        include_braces=False,
    )

    pole_neg_code = ccg.c_codegen(
        [rot.h_plus_I_pole_neg, rot.h_cross_I_pole_neg],
        ["h_plus_I", "h_cross_I"],
        verbose=False,
        include_braces=False,
    )

    # Step 3: Dynamically construct the C-function parameters.
    params_list = [
        "const size_t nsteps",
        "const REAL iota",
        "const REAL varphi_0",
        "const REAL J_f_x",
        "const REAL J_f_y",
        "const REAL J_f_z",
        "const REAL *restrict alpha_JP_array",
        "const REAL *restrict beta_JP_array",
        "const REAL *restrict gamma_JP_array",
    ]
    for l, m in modes:
        params_list.append(f"const double complex *restrict hP_l{l}m{m}_array")

    params_list.extend(
        ["REAL *restrict h_plus_I_array", "REAL *restrict h_cross_I_array"]
    )
    params = " , ".join(params_list)

    # Step 4: Construct the C-function body.
    body = """
    // Loop over the timeseries to process the waveform transformation
    size_t i;
    for (i = 0; i < nsteps; i++) {
        // Extract current timestep Euler angles
        const REAL alpha_JP = alpha_JP_array[i];
        const REAL beta_JP  = beta_JP_array[i];
        const REAL gamma_JP = gamma_JP_array[i];
"""
    for l, m in modes:
        body += f"        const REAL hP_l{l}m{m}_Re = creal(hP_l{l}m{m}_array[i]);\n"
        body += f"        const REAL hP_l{l}m{m}_Im = cimag(hP_l{l}m{m}_array[i]);\n"

    body += "\n        /* --- Code generated by NRPy+ --- */\n"

    body += "\n        REAL M33 = 0.0;\n        {\n"
    body += "\n".join(
        [f"            {line}" if line else "" for line in pre_code.split("\n")]
    )
    body += "\n        }\n"

    body += "\n\n        REAL h_plus_I = 0.0;\n        REAL h_cross_I = 0.0;\n"
    body += "\n        if (M33 > 1.0 - 1e-14) {\n"
    body += "\n".join(
        [f"            {line}" if line else "" for line in pole_pos_code.split("\n")]
    )
    body += "\n        } else if (M33 < -1.0 + 1e-14) {\n"
    body += "\n".join(
        [f"            {line}" if line else "" for line in pole_neg_code.split("\n")]
    )
    body += "\n        } else {\n"
    body += "\n".join(
        [f"            {line}" if line else "" for line in generic_code.split("\n")]
    )
    body += "\n        }\n"

    body += "        /* ------------------------------- */\n\n"

    body += """
        // Store results in the output timeseries arrays
        h_plus_I_array[i]  = h_plus_I;
        h_cross_I_array[i] = h_cross_I;
    }
    """

    includes = ["BHaH_defines.h", "BHaH_function_prototypes.h"]

    desc = """Applies the co-precessing frame transformations to generate the inertial GW polarizations.
This function loops over a given timeseries, applying the Wigner small-d rotations
to the co-precessing modes (h^P_lm) to compute h_+ and h_x in the observer's frame.

@param nsteps - The number of points in the timeseries arrays.
@param iota - The observer inclination angle.
@param varphi_0 - The observer azimuthal angle.
@param J_f_x, J_f_y, J_f_z - Cartesian components of the final angular momentum.
@param alpha_JP_array, beta_JP_array, gamma_JP_array - Euler angles from J -> P frame.
"""
    for l, m in modes:
        desc += f"@param hP_l{l}m{m}_array - Array containing the complex co-precessing ({l},{m}) mode.\n"

    desc += """@param h_plus_I_array - Output array for the inertial h_+ polarization.
@param h_cross_I_array - Output array for the inertial h_x polarization.
"""

    cfc.register_CFunction(
        includes=includes,
        desc=desc,
        cfunc_type="void",
        name="SEOBNRv5_coprecessing_rotations",
        params=params,
        include_CodeParameters_h=False,
        body=body,
    )

    return pcg.NRPyEnv()
