
/**
 * @file diagnostic_gfs.h
 * @brief Defines the enum and name table for all diagnostic gridfunctions.
 * @details
 * This header provides the single source of truth for all diagnostic
 * quantities available for interpolation and output. It is automatically
 * generated by NRPy from a Python dictionary.
 *
 * It defines two key components:
 *
 *   1. An anonymous enum that lists all diagnostic gridfunction tokens (e.g.,
 *      DIAG_RHO, DIAG_UX). This list is terminated by the special member
 *      `TOTAL_NUM_DIAG_GFS`, which provides a convenient compile-time count
 *      of the total number of diagnostics.
 *
 *   2. A static const array of C strings, `diagnostic_gf_names`, which maps
 *      each enum token to a short, human-readable name (e.g., "rho", "ux").
 *      This mapping uses C99 designated initializers for robustness against
 *      changes in the enum's order.
 *
 * The contents are wrapped in an `extern "C"` block to ensure
 * compatibility with C++ compilers.
 *
 * @note This file is auto-generated and should not be edited by hand.
 *       Changes should be made in the corresponding NRPy Python code.
 *
 * Author: Zachariah B. Etienne
 *         zachetie **at** gmail **dot* com
 */

#ifndef DIAGNOSTIC_GFS_H
#define DIAGNOSTIC_GFS_H

#ifdef __cplusplus
extern "C" {
#endif

// This enum defines all available diagnostic gridfunctions.
// It is the single source of truth for diagnostic quantities.
enum {
  DIAG_RESIDUAL,
  DIAG_UUGF,
  DIAG_VVGF,
  DIAG_GRIDINDEX,
  TOTAL_NUM_DIAG_GFS // must be last: total produced diagnostics (== count)
};

#ifdef __cplusplus
#define DIAG_INIT(idx, val) val
#else
#define DIAG_INIT(idx, val) [idx] = val
#endif

// Human-friendly, one-word names for each diagnostic gridfunction.
// Using C99 designated initializers makes this robust against reordering the enum.
MAYBE_UNUSED static const char *diagnostic_gf_names[TOTAL_NUM_DIAG_GFS] = {
    DIAG_INIT(DIAG_RESIDUAL, "Residual_H_constraint"), //
    DIAG_INIT(DIAG_UUGF, "u_numerical"),               //
    DIAG_INIT(DIAG_VVGF, "v_numerical"),               //
    DIAG_INIT(DIAG_GRIDINDEX, "GridIndex"),            //
};

#ifdef __cplusplus
} // extern "C"
#endif

#endif // DIAGNOSTIC_GFS_H
