// BHaH core header file, automatically generated from cuda.output_BHaH_defines_h,
//    DO NOT EDIT THIS FILE BY HAND.

// Standard macro definitions
// We include the macro definition NUM_STREAMS since it is used for calculations in various
// algorithms in addition to defining the streams array
#define NUM_STREAMS 3

// Standard declarations
// Device storage for grid parameters
extern __constant__ params_struct d_params[NUM_STREAMS];
// Device storage for commondata
extern __constant__ commondata_struct d_commondata;
// Device storage for grid function parity
extern __constant__ int8_t d_evol_gf_parity[24];
extern cudaStream_t streams[NUM_STREAMS];
extern size_t GPU_N_SMS;

// CUDA Error checking macro only active if compiled with -DDEBUG
// Otherwise additional synchronization overhead will occur
#ifdef DEBUG
#define cudaCheckErrors(v, msg)                                                                                                                      \
  do {                                                                                                                                               \
    cudaError_t __err = cudaGetLastError();                                                                                                          \
    if (__err != cudaSuccess) {                                                                                                                      \
      fprintf(stderr, "Fatal error: %s %s (%s at %s:%d)\n", #v, msg, cudaGetErrorString(__err), __FILE__, __LINE__);                                 \
      fprintf(stderr, "*** FAILED - ABORTING\n");                                                                                                    \
      exit(1);                                                                                                                                       \
    }                                                                                                                                                \
  } while (0);
#else
#define cudaCheckErrors(v, msg)
#endif

#define BHAH_MEMCPY_HOST_TO_DEVICE(dest_ptr, src_ptr, sz) cudaMemcpy(dest_ptr, src_ptr, sz, cudaMemcpyHostToDevice);

#define BHAH_THREADS_IN_X_DIR_DEFAULT 32
#define BHAH_THREADS_IN_Y_DIR_DEFAULT 1
#define BHAH_THREADS_IN_Z_DIR_DEFAULT 1
