from typing import List
import nrpy.params as par
import nrpy.c_function as cfc
import os


def construct_param_ccl(
    thorn_name: str,
    list_of_param_ccl_CodeParam_names: List[str],
    shares_extends_str: str = "",
) -> None:
    """
    Generate the content for the param.ccl file and write it to disk.

    :param thorn_name: Name of the thorn.
    """
    paramccl_str = f"""# This param.ccl file was automatically generated by NRPy+.
#   You are advised against modifying it directly; instead
#   modify the Python code that generates it.

{shares_extends_str}

restricted:
"""
    for parname in list_of_param_ccl_CodeParam_names:
        paramccl_str += f'{CParam.c_type_alias} "{CParam.name} (see NRPy+ for parameter definition)"\n'
        paramccl_str += "{\n"
        paramccl_str += ' *:* :: "All values accepted. NRPy+ does not restrict the allowed ranges of parameters yet."\n'
        paramccl_str += f"}} {CParam.defaultvalue}\n\n"
        del list_of_param_ccl_CodeParam_names[parname]

    with open(os.path.join(thorn_name, "param.ccl"), "w") as file:
        file.write(paramccl_str)
