"""
Register pointwise BSSN basis transforms from Cartesian basis to rfm basis.

This module emits one private kernel per supported coordinate system using the
standard BHaH wrapper-function infrastructure. The public unsuffixed runtime
dispatcher is generated later by
``BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()``.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from __future__ import annotations

from typing import List, Set, Tuple

import sympy as sp

import nrpy.c_codegen as ccg
import nrpy.c_function as cfc
import nrpy.equations.basis_transforms.jacobians as bt
import nrpy.indexedexp as ixp
import nrpy.reference_metric as refmetric

_SYM01_PAIRS: Tuple[Tuple[int, int], ...] = (
    (0, 0),
    (0, 1),
    (0, 2),
    (1, 1),
    (1, 2),
    (2, 2),
)


def _prefix_params(expr: sp.Expr) -> sp.Expr:
    """
    Rewrite coordinate-system parameters as ``params->...`` C symbols.

    :param expr: SymPy expression that may contain coordinate-system parameters.
    :return: Expression with parameter symbols rewritten as ``params->...``.
    """
    local_symbols = {
        "xx0",
        "xx1",
        "xx2",
        *(f"CartgammabarDD{i}{j}" for i, j in _SYM01_PAIRS),
        *(f"CartAbarDD{i}{j}" for i, j in _SYM01_PAIRS),
        *(f"CartbetaU{i}" for i in range(3)),
        *(f"CartBU{i}" for i in range(3)),
        *(f"CartLambdabarU{i}" for i in range(3)),
    }
    substitutions: dict[sp.Basic | complex, sp.Expr | complex] = {}
    for symbol in expr.free_symbols:
        if isinstance(symbol, sp.Symbol) and symbol.name not in local_symbols:
            substitutions[symbol] = sp.Symbol(f"params->{symbol.name}")
    return expr.subs(substitutions)


def register_CFunction_basis_transform_BSSN_Cartesian_to_rfm_single_point(
    set_of_CoordSystems: Set[str],
) -> None:
    r"""
    Register ``basis_transform_BSSN_Cartesian_to_rfm_single_point``.

    :param set_of_CoordSystems: Coordinate systems for which private wrapper
        kernels should be generated.

    The public unsuffixed wrapper is generated by
    ``BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()``.

    Doctests:
    >>> import nrpy.c_function as cfc
    >>> from nrpy.helpers.generic import validate_strings
    >>> from nrpy.infrastructures import BHaH
    >>> import nrpy.params as par
    >>> par.set_parval_from_str("parallelization", "openmp")
    >>> cfc.CFunction_dict.clear()
    >>> register_CFunction_basis_transform_BSSN_Cartesian_to_rfm_single_point(set_of_CoordSystems={"SinhSpherical", "SinhSymTP"})  # doctest: +ELLIPSIS
    Setting up basis_transforms[SinhSpherical]...
    >>> BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()
    >>> generated_str = cfc.CFunction_dict["basis_transform_BSSN_Cartesian_to_rfm_single_point"].full_function
    >>> validation_desc = "basis_transform_BSSN_Cartesian_to_rfm_single_point__openmp"
    >>> validate_strings(generated_str, validation_desc, file_ext="c")
    """
    CartgammabarDD = ixp.declarerank2("CartgammabarDD", symmetry="sym01")
    CartAbarDD = ixp.declarerank2("CartAbarDD", symmetry="sym01")
    CartbetaU = ixp.declarerank1("CartbetaU")
    CartBU = ixp.declarerank1("CartBU")
    CartLambdabarU = ixp.declarerank1("CartLambdabarU")
    includes = ["BHaH_defines.h", "BHaH_function_prototypes.h"]
    desc = r"""
@brief Transform one BSSN point from Cartesian basis to a destination rfm basis.

This private kernel assumes one destination coordinate system. The public
unsuffixed runtime-dispatch wrapper is emitted separately by
``rfm_wrapper_functions``.

@param[in] params Destination-grid parameters used for indexing and coordinate-dependent expressions.
@param[in] idx3 Destination-grid flattened point index.
@param[in] xx_dst Destination-grid local coordinates for this point.
@param[in,out] y_n_gfs Gridfunction storage updated in place.
"""
    cfunc_type = "void"
    name = "basis_transform_BSSN_Cartesian_to_rfm_single_point"
    params = (
        "const params_struct *restrict params, "
        "const int idx3, const REAL xx_dst[3], REAL *restrict y_n_gfs"
    )

    for CoordSystem in sorted(set_of_CoordSystems):
        if CoordSystem.startswith("GeneralRFM"):
            continue

        basis_transforms = bt.basis_transforms[CoordSystem]
        rfm = refmetric.reference_metric[CoordSystem]
        LambdabarU = (
            basis_transforms.basis_transform_vectorU_from_Cartesian_to_rfmbasis(
                CartLambdabarU
            )
        )
        betaU = basis_transforms.basis_transform_vectorU_from_Cartesian_to_rfmbasis(
            CartbetaU
        )
        BU = basis_transforms.basis_transform_vectorU_from_Cartesian_to_rfmbasis(CartBU)
        AbarDD = basis_transforms.basis_transform_tensorDD_from_Cartesian_to_rfmbasis(
            CartAbarDD
        )
        gammabarDD = (
            basis_transforms.basis_transform_tensorDD_from_Cartesian_to_rfmbasis(
                CartgammabarDD
            )
        )

        lhses: List[str] = []
        exprs: List[sp.Expr] = []
        for i, j in _SYM01_PAIRS:
            lhses.append(f"y_n_gfs[IDX4ptS(HDD{i}{j}GF, idx3)]")
            exprs.append((gammabarDD[i][j] - rfm.ghatDD[i][j]) / rfm.ReDD[i][j])
            lhses.append(f"y_n_gfs[IDX4ptS(ADD{i}{j}GF, idx3)]")
            exprs.append(AbarDD[i][j] / rfm.ReDD[i][j])
        for i in range(3):
            lhses.append(f"y_n_gfs[IDX4ptS(VETU{i}GF, idx3)]")
            exprs.append(betaU[i] / rfm.ReU[i])
            lhses.append(f"y_n_gfs[IDX4ptS(BETU{i}GF, idx3)]")
            exprs.append(BU[i] / rfm.ReU[i])
            lhses.append(f"y_n_gfs[IDX4ptS(LAMBDAU{i}GF, idx3)]")
            exprs.append(LambdabarU[i] / rfm.ReU[i])
        exprs = [_prefix_params(expr) for expr in exprs]

        body = """#define IDX4ptS(gf, idx) ((idx) + (params->Nxx_plus_2NGHOSTS0 * params->Nxx_plus_2NGHOSTS1 * params->Nxx_plus_2NGHOSTS2) * (gf))
MAYBE_UNUSED const REAL xx0 = xx_dst[0];
MAYBE_UNUSED const REAL xx1 = xx_dst[1];
MAYBE_UNUSED const REAL xx2 = xx_dst[2];

// Read Cartesian-basis BSSN fields from memory.
"""
        for gf in ("hDD", "aDD"):
            for i, j in _SYM01_PAIRS:
                body += f"const REAL Cart{gf}{i}{j} = y_n_gfs[IDX4ptS({gf.upper()}{i}{j}GF, idx3)];\n"
        for gf in ("vetU", "betU", "lambdaU"):
            for i in range(3):
                body += f"const REAL Cart{gf}{i} = y_n_gfs[IDX4ptS({gf.upper()}{i}GF, idx3)];\n"
        body += "\n// Reconstruct Cartesian unrescaled variables from BSSN storage conventions.\n"
        for i in range(3):
            body += f"const REAL CartbetaU{i} = CartvetU{i};\n"
            body += f"const REAL CartBU{i} = CartbetU{i};\n"
            body += f"const REAL CartLambdabarU{i} = CartlambdaU{i};\n"
        for i, j in _SYM01_PAIRS:
            body += f"const REAL CartAbarDD{i}{j} = CartaDD{i}{j};\n"
            if i == j:
                body += f"const REAL CartgammabarDD{i}{j} = CarthDD{i}{j} + 1.0;\n"
            else:
                body += f"const REAL CartgammabarDD{i}{j} = CarthDD{i}{j};\n"
        body += "\n"
        body += ccg.c_codegen(
            exprs,
            lhses,
            include_braces=False,
            verbose=False,
        )
        body += "\n#undef IDX4ptS\n"

        cfc.register_CFunction(
            includes=includes,
            desc=desc,
            cfunc_type=cfunc_type,
            name=name,
            params=params,
            body=body,
            include_CodeParameters_h=False,
            CoordSystem_for_wrapper_func=CoordSystem,
        )


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()
    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    print(f"Doctest passed: All {results.attempted} test(s) passed")
