"""
Register pointwise BSSN basis transforms from rfm basis to Cartesian basis.

This module emits one private kernel per supported coordinate system using the
standard BHaH wrapper-function infrastructure. The public unsuffixed runtime
dispatcher is generated later by
``BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()``.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from __future__ import annotations

from typing import List, Set, Tuple

import sympy as sp

import nrpy.c_codegen as ccg
import nrpy.c_function as cfc
import nrpy.equations.basis_transforms.jacobians as bt
from nrpy.equations.general_relativity.BSSN_quantities import BSSN_quantities

_SYM01_PAIRS: Tuple[Tuple[int, int], ...] = (
    (0, 0),
    (0, 1),
    (0, 2),
    (1, 1),
    (1, 2),
    (2, 2),
)


def _prefix_params(expr: sp.Expr) -> sp.Expr:
    """
    Rewrite coordinate-system parameters as ``params->...`` C symbols.

    :param expr: SymPy expression that may contain coordinate-system parameters.
    :return: Expression with parameter symbols rewritten as ``params->...``.
    """
    local_symbols = {
        "xx0",
        "xx1",
        "xx2",
        *(f"hDD{i}{j}" for i, j in _SYM01_PAIRS),
        *(f"aDD{i}{j}" for i, j in _SYM01_PAIRS),
        *(f"vetU{i}" for i in range(3)),
        *(f"betU{i}" for i in range(3)),
        *(f"lambdaU{i}" for i in range(3)),
    }
    substitutions: dict[sp.Basic | complex, sp.Expr | complex] = {}
    for symbol in expr.free_symbols:
        if isinstance(symbol, sp.Symbol) and symbol.name not in local_symbols:
            substitutions[symbol] = sp.Symbol(f"params->{symbol.name}")
    return expr.subs(substitutions)


def register_CFunction_basis_transform_BSSN_rfm_to_Cartesian_single_point(
    set_of_CoordSystems: Set[str],
) -> None:
    r"""
    Register ``basis_transform_BSSN_rfm_to_Cartesian_single_point``.

    :param set_of_CoordSystems: Coordinate systems for which private wrapper
        kernels should be generated.

    The public unsuffixed wrapper is generated by
    ``BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()``.

    Doctests:
    >>> import nrpy.c_function as cfc
    >>> from nrpy.helpers.generic import validate_strings
    >>> from nrpy.infrastructures import BHaH
    >>> import nrpy.params as par
    >>> par.set_parval_from_str("parallelization", "openmp")
    >>> cfc.CFunction_dict.clear()
    >>> register_CFunction_basis_transform_BSSN_rfm_to_Cartesian_single_point(set_of_CoordSystems={"SinhSpherical", "SinhSymTP"})  # doctest: +ELLIPSIS
    Setting up basis_transforms[SinhSpherical]...
    >>> BHaH.rfm_wrapper_functions.register_CFunctions_CoordSystem_wrapper_funcs()
    >>> generated_str = cfc.CFunction_dict["basis_transform_BSSN_rfm_to_Cartesian_single_point"].full_function
    >>> validation_desc = "basis_transform_BSSN_rfm_to_Cartesian_single_point__openmp"
    >>> validate_strings(generated_str, validation_desc, file_ext="c")
    """
    includes = ["BHaH_defines.h", "BHaH_function_prototypes.h"]
    desc = r"""
@brief Transform one BSSN point from a source rfm basis to Cartesian basis.

This private kernel assumes source-grid coordinate-dependent expressions for a
single coordinate system. The public unsuffixed runtime-dispatch wrapper is
emitted separately by ``rfm_wrapper_functions``.

@param[in] params Source-grid parameters used for coordinate-dependent expressions.
@param[in] paramsdst Destination-grid parameters used only for indexing at ``idx3``.
@param[in] idx3 Destination-grid flattened point index.
@param[in] xx_src Source-grid local coordinates for this point.
@param[in,out] y_n_gfs Gridfunction storage updated in place.
"""
    cfunc_type = "void"
    name = "basis_transform_BSSN_rfm_to_Cartesian_single_point"
    params = (
        "const params_struct *restrict params, "
        "const params_struct *restrict paramsdst, "
        "const int idx3, const REAL xx_src[3], REAL *restrict y_n_gfs"
    )

    for CoordSystem in sorted(set_of_CoordSystems):
        if CoordSystem.startswith("GeneralRFM"):
            continue

        basis_transforms = bt.basis_transforms[CoordSystem]
        bssn_quantities = BSSN_quantities[CoordSystem]
        CartLambdabarU = (
            basis_transforms.basis_transform_vectorU_from_rfmbasis_to_Cartesian(
                bssn_quantities.LambdabarU
            )
        )
        CartbetaU = basis_transforms.basis_transform_vectorU_from_rfmbasis_to_Cartesian(
            bssn_quantities.betaU
        )
        CartBU = basis_transforms.basis_transform_vectorU_from_rfmbasis_to_Cartesian(
            bssn_quantities.BU
        )
        CartAbarDD = (
            basis_transforms.basis_transform_tensorDD_from_rfmbasis_to_Cartesian(
                bssn_quantities.AbarDD
            )
        )
        CartgammabarDD = (
            basis_transforms.basis_transform_tensorDD_from_rfmbasis_to_Cartesian(
                bssn_quantities.gammabarDD
            )
        )

        lhses: List[str] = []
        exprs: List[sp.Expr] = []
        for i, j in _SYM01_PAIRS:
            lhses.append(f"y_n_gfs[IDX4ptS_dst(ADD{i}{j}GF, idx3)]")
            exprs.append(CartAbarDD[i][j])
            lhses.append(f"y_n_gfs[IDX4ptS_dst(HDD{i}{j}GF, idx3)]")
            exprs.append(CartgammabarDD[i][j] - (sp.Integer(1) if i == j else 0))
        for i in range(3):
            lhses.append(f"y_n_gfs[IDX4ptS_dst(VETU{i}GF, idx3)]")
            exprs.append(CartbetaU[i])
            lhses.append(f"y_n_gfs[IDX4ptS_dst(BETU{i}GF, idx3)]")
            exprs.append(CartBU[i])
            lhses.append(f"y_n_gfs[IDX4ptS_dst(LAMBDAU{i}GF, idx3)]")
            exprs.append(CartLambdabarU[i])
        exprs = [_prefix_params(expr) for expr in exprs]

        body = """#define IDX4ptS_dst(gf, idx) ((idx) + (paramsdst->Nxx_plus_2NGHOSTS0 * paramsdst->Nxx_plus_2NGHOSTS1 * paramsdst->Nxx_plus_2NGHOSTS2) * (gf))
MAYBE_UNUSED const REAL xx0 = xx_src[0];
MAYBE_UNUSED const REAL xx1 = xx_src[1];
MAYBE_UNUSED const REAL xx2 = xx_src[2];

// Read rescaled BSSN fields from destination-grid storage.
"""
        for gf in ("hDD", "aDD"):
            for i, j in _SYM01_PAIRS:
                body += f"const REAL {gf}{i}{j} = y_n_gfs[IDX4ptS_dst({gf.upper()}{i}{j}GF, idx3)];\n"
        for gf in ("vetU", "betU", "lambdaU"):
            for i in range(3):
                body += f"const REAL {gf}{i} = y_n_gfs[IDX4ptS_dst({gf.upper()}{i}GF, idx3)];\n"
        body += "\n"
        body += ccg.c_codegen(
            exprs,
            lhses,
            include_braces=False,
            verbose=False,
        )
        body += "\n#undef IDX4ptS_dst\n"

        cfc.register_CFunction(
            includes=includes,
            desc=desc,
            cfunc_type=cfunc_type,
            name=name,
            params=params,
            body=body,
            include_CodeParameters_h=False,
            CoordSystem_for_wrapper_func=CoordSystem,
        )


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()
    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    print(f"Doctest passed: All {results.attempted} test(s) passed")
