"""
BLUEPRINT DIAGNOSTIC AND VISUALIZATION SUITE.
This utility serves as the primary validation tool for the 'light_blueprint.bin' file
generated by the C-based Geodesic Integrator.

It performs three critical functions:
1. Data Integrity: Parses the binary file using the structured 'BLUEPRINT_DTYPE' to
   ensure the data alignment matches the C 'blueprint_data_t' struct.
2. Statistical Validation: Calculates the distribution of termination types (hits
   on the source plane vs. escape to the celestial sphere) to verify physics enums.
3. Spatial Visualization: Generates hexbin heatmaps for window coordinates, source
   plane intercepts, and celestial sphere angles to check for coordinate mapping
   errors or integration 'blind spots'.
"""

import os
import sys
from typing import Any, Optional

# Temporarily add the script's directory to sys.path to ensure we can
# import 'config_and_types.py' even if the script is called from elsewhere.
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)

try:
    import config_and_types as cfg  # type: ignore
except ImportError:
    print(f"[!] ERROR: Cannot find 'config_and_types.py' in {script_dir}")
    print("    Please ensure it is saved in the same directory as this script.")
    sys.exit(1)


def plot_heatmaps(data: Any) -> None:
    """
    Generate hexbin heatmaps for window, source plane, and sphere coordinates.

    Hexbins are used instead of scatter plots to handle large datasets efficiently
    without overlapping individual points (overplotting).

    :param data: The structured NumPy array containing ray termination data.
    """
    # pylint: disable=import-outside-toplevel, import-error
    import matplotlib.pyplot as plt  # type: ignore
    import numpy as np

    # --- Preamble: Descriptive Physical Variable Mapping ---
    # Extract coordinates from the structured array for plotting.
    y_w, z_w = data["y_w"], data["z_w"]
    y_s, z_s = data["y_s"], data["z_s"]
    phi, theta = data["final_phi"], data["final_theta"]

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # 1. Window Coordinates (y_w, z_w) - All rays
    # Validates the initial ray distribution at the camera's field of view.
    # This should typically show a uniform grid or box representing the 'scan_density'.
    hb0 = axes[0].hexbin(y_w, z_w, gridsize=50, cmap="viridis", mincnt=1)
    axes[0].set_title("Window Plane (Camera)\n$y_w$ vs $z_w$")
    axes[0].set_xlabel("$y_w$")
    axes[0].set_ylabel("$z_w$")
    fig.colorbar(hb0, ax=axes[0], label="Ray Count")

    # 2. Source Plane (y_s, z_s) - Filtering for TERM_SOURCE_PLANE
    # Visualizes the geometry of the accretion disk hits.
    # Expect a 'ring' or 'annulus' structure corresponding to [source_r_min, source_r_max].
    source_mask = data["termination_type"] == cfg.TERM_SOURCE_PLANE
    if np.any(source_mask):
        hb1 = axes[1].hexbin(
            y_s[source_mask],
            z_s[source_mask],
            gridsize=50,
            cmap="plasma",
            mincnt=1,
        )
        axes[1].set_title("Source Plane Hits\n$y_s$ vs $z_s$")
        fig.colorbar(hb1, ax=axes[1], label="Ray Count")
    else:
        # Diagnostic warning: if no hits appear, the C event detection might be failing.
        axes[1].text(
            0.5,
            0.5,
            "No Source Plane Hits\n(Check Enum Mapping)",
            ha="center",
            va="center",
            transform=axes[1].transAxes,
        )
    axes[1].set_xlabel("$y_s$")
    axes[1].set_ylabel("$z_s$")

    # 3. Celestial Sphere (phi, theta) - Filtering for TERM_SPHERE
    # Maps rays that escaped to 'infinity'.
    # theta is the polar angle [0, pi], phi is the azimuthal angle [0, 2pi].
    sphere_mask = data["termination_type"] == cfg.TERM_SPHERE
    if np.any(sphere_mask):
        hb2 = axes[2].hexbin(
            phi[sphere_mask],
            theta[sphere_mask],
            gridsize=50,
            cmap="magma",
            mincnt=1,
        )
        axes[2].set_title(r"Celestial Sphere Hits" + "\n" + r"$\phi$ vs $\theta$")
        fig.colorbar(hb2, ax=axes[2], label="Ray Count")
    else:
        axes[2].text(
            0.5,
            0.5,
            "No Sphere Hits\n(Check Enum Mapping)",
            ha="center",
            va="center",
            transform=axes[2].transAxes,
        )
    axes[2].set_xlabel(r"$\phi$")
    axes[2].set_ylabel(r"$\theta$")

    plt.tight_layout()
    print("[i] Displaying heatmaps. Close the window to continue...")
    plt.show()


def diagnose_blueprint(blueprint_path: Optional[str] = None) -> None:
    """
    Read the binary blueprint file and print critical diagnostics to the console.

    This helps identify numerical instabilities or logic errors in the integrator.

    :param blueprint_path: Path to the .bin file. Defaults to relative project path.
    """
    # pylint: disable=import-outside-toplevel
    import numpy as np

    if blueprint_path is None:
        # Default relative path construction based on your project structure.
        blueprint_path = os.path.abspath(
            os.path.join(
                script_dir,
                "..",
                "..",
                "..",
                "project",
                "photon_geodesic_integrator",
                "light_blueprint.bin",
            )
        )

    print("=================================================================")
    print(" BLUEPRINT DIAGNOSTICS & VISUALIZATION")
    print(f" File: {blueprint_path}")
    print("=================================================================")

    if not os.path.exists(blueprint_path):
        print(f"[!] ERROR: Blueprint file not found at:\n    {blueprint_path}")
        return

    # Load data using the structured dtype.
    # This automatically unpacks the f8 (double) and int32 fields.
    data = np.fromfile(blueprint_path, dtype=cfg.BLUEPRINT_DTYPE)
    total_rays = len(data)
    print(f"Total records loaded: {total_rays:,}\n")

    # --- 1. Check Enum Mappings ---
    # Crucial for verifying that C enums and Python enums match.
    # If the C code terminates at the sphere but uses ID 9, this check will flag it.
    print("--- 1. Raw Termination Enums in Binary ---")
    unique_enums, counts = np.unique(data["termination_type"], return_counts=True)
    for e, c in zip(unique_enums, counts):
        print(f"  Raw Enum {e:2d}: {c:8,} rays ({c/total_rays*100:6.2f}%)")

    print(
        f"\n  [Config Current]: SOURCE_PLANE = {cfg.TERM_SOURCE_PLANE}, SPHERE = {cfg.TERM_SPHERE}"
    )
    print(
        "  -> If your raw enums above do NOT match these, update config_and_types.py."
    )

    # --- 2. Check Window Coordinates (Field of View) ---
    # Validates that the C-generated rays actually align with the window dimensions
    # specified in the Python configuration.
    print("\n--- 2. Window Coordinate Bounds (y_w, z_w) ---")
    half_w = cfg.WINDOW_WIDTH / 2.0
    in_view = np.sum(
        (data["y_w"] >= -half_w)
        & (data["y_w"] < half_w)
        & (data["z_w"] >= -half_w)
        & (data["z_w"] < half_w)
    )
    print(f"  Rays inside Renderer FOV: {in_view:,} ({in_view/total_rays*100:.2f}%)")

    # --- 3. View Raw Sample Data ---
    # Direct sanity check of the first 5 records.
    # Useful for spotting immediate NANs or impossible values (e.g., negative theta).
    print("\n--- 3. First 5 Raw Records ---")
    header = f"{'Ray#':<6} | {'Term Type':<9} | {'y_w':>8} | {'z_w':>8} | {'y_s / theta':>11} | {'z_s / phi':>11}"
    print(header)
    print("-" * len(header))

    for i in range(min(9, total_rays)):
        rec = data[i]
        tt = rec["termination_type"]
        # Context-aware display: show plane coords for disk hits, angles for sphere hits.
        val_1 = rec["y_s"] if tt == cfg.TERM_SOURCE_PLANE else rec["final_theta"]
        val_2 = rec["z_s"] if tt == cfg.TERM_SOURCE_PLANE else rec["final_phi"]
        print(
            f"{i:<6} | {tt:<9} | {rec['y_w']:>8.5} | {rec['z_w']:>8.5f} | {val_1:>11.5f} | {val_2:>11.5f}"
        )

    # --- 4. Launch Visualization ---
    print("\n[i] Generating heatmaps...")
    plot_heatmaps(data)
    print("=================================================================")


if __name__ == "__main__":
    diagnose_blueprint()
