"""
Orchestrator for the CPU numerical-spacetime photon geodesic integrator.

This module constructs the C project that evolves batched photon trajectories
through a numerical spacetime sourced from the combined raytracing ``.bin``
generated from ``two_blackholes_collide.py --raytracing-time ...``.

The generated code keeps the existing Structure-of-Arrays photon pipeline and
adaptive RKF45 stepping, but all metric and Christoffel evaluations now come
from the numerical interpolation helpers instead of analytic spacetime kernels.

This example currently generates a CPU/OpenMP project.

Author: Dalton J. Moone
        daltonmoone **at** gmail **dot** com
"""

import argparse
import os
import shutil
import sys

import sympy as sp

import nrpy.c_function as cfc
import nrpy.params as par
import nrpy.reference_metric as refmetric
from nrpy.equations.general_relativity.geodesics import geodesics as geo
from nrpy.infrastructures.BHaH import BHaH_defines_h
from nrpy.infrastructures.BHaH import CodeParameters as CPs
from nrpy.infrastructures.BHaH import Makefile_helpers as Makefile
from nrpy.infrastructures.BHaH import cmdline_input_and_parfiles
from nrpy.infrastructures.BHaH.general_relativity.geodesics import (
    normalization_constraint,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.interpolation import (
    azimuthal_symmetry_spatial_lagrange_interpolation,
    numerical_interpolation,
    temporal_lagrange_interpolation,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.photon import (
    batch_integrator_numerical,
    calculate_and_fill_blueprint_data_universal,
    calculate_ode_rhs_kernel,
    event_detection_manager_kernel,
    find_event_time_and_state,
    handle_source_plane_intersection,
    handle_window_plane_intersection,
    main,
    p0_reverse_kernel,
    rkf45_finalize_and_control_kernel,
    rkf45_stage_update,
    set_initial_conditions_kernel,
)


def _require(condition: bool, message: str) -> None:
    """
    Raise ``ValueError`` if an argument validation condition fails.

    :param condition: Condition that must hold.
    :param message: Description of the violated constraint.
    :raises ValueError: If ``condition`` is false.
    """
    if not condition:
        raise ValueError(message)


if __name__ == "__main__":
    # Step 1: Configure command-line arguments for the generation pipeline
    parser = argparse.ArgumentParser(
        description="""Generate the Split-Pipeline Photon Geodesic Integrator (Numerical). Requires a numerical spacetime .bin file generated by two_blackholes_collide.py.""",
        epilog="""To generate the desired numerical spacetime data, run:
python3 two_blackholes_collide.py --raytracing-time T_FINAL DIAGNOSTICS_OUTPUT_EVERY --raytracing-coord-system CoordSystem --raytracing-Nxx NXX0 NXX1 NXX2 --raytracing-domain ...

Then rerun this photon script using the .bin filename printed to the terminal by two_blackholes_collide.py, e.g.:
python3 photon_batch_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_SinhSpherical_sinhw_0p4_72_12_2.bin --dataset-coord-system SinhSpherical --dataset-grid-size 7.5 --dataset-sinhw 0.4

or:
python3 photon_batch_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_SinhCylindrical_sinhwrho_0p25_sinhwz_0p4_72_2_12.bin --dataset-coord-system SinhCylindrical --dataset-grid-size 7.5 --dataset-sinhw 0.25 0.4""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--bin-name",
        type=str,
        required=True,
        help="""Name of the numerical spacetime .bin file inside project/raytracing_data.""",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="project",
        help="The parent directory where the generated C project will reside.",
    )
    parser.add_argument(
        "--dataset-coord-system",
        type=str,
        required=True,
        choices=refmetric.supported_CoordSystems,
        help="""Coordinate system used when generating the numerical spacetime dataset. Required by the spatial interpolation pipeline.""",
    )
    parser.add_argument(
        "--dataset-grid-size",
        type=float,
        required=True,
        help="""Physical grid size used when generating the numerical spacetime dataset.""",
    )
    parser.add_argument(
        "--dataset-sinhw",
        nargs="+",
        type=float,
        default=None,
        metavar="SINHW",
        help="""Sinh width parameter(s) used when generating the numerical spacetime dataset. SinhSpherical: SINHW. SinhCylindrical: SINHWRHO SINHWZ. Do not use with non-Sinh coordinate systems.""",
    )
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    args = parser.parse_args()

    _require(
        os.path.basename(args.bin_name) == args.bin_name,
        "--bin-name must be a filename only, not a path.",
    )
    _require(
        args.bin_name.endswith(".bin"),
        "--bin-name must name a numerical spacetime .bin file.",
    )
    _require(
        args.dataset_grid_size > 0.0,
        "--dataset-grid-size must be positive.",
    )
    dataset_sinhw = None
    dataset_sinhwrho = None
    dataset_sinhwz = None
    if args.dataset_coord_system == "SinhSpherical":
        _require(
            args.dataset_sinhw is not None and len(args.dataset_sinhw) == 1,
            "--dataset-coord-system SinhSpherical requires --dataset-sinhw SINHW.",
        )
        dataset_sinhw = args.dataset_sinhw[0]
        _require(dataset_sinhw > 0.0, "SINHW must be positive.")
    elif args.dataset_coord_system == "SinhCylindrical":
        _require(
            args.dataset_sinhw is not None and len(args.dataset_sinhw) == 2,
            """--dataset-coord-system SinhCylindrical requires --dataset-sinhw SINHWRHO SINHWZ.""",
        )
        dataset_sinhwrho = args.dataset_sinhw[0]
        dataset_sinhwz = args.dataset_sinhw[1]
        _require(dataset_sinhwrho > 0.0, "SINHWRHO must be positive.")
        _require(dataset_sinhwz > 0.0, "SINHWZ must be positive.")
    else:
        _require(
            args.dataset_sinhw is None,
            """--dataset-sinhw is supported only for SinhSpherical and SinhCylindrical.""",
        )

    # Step 2: Define strict project constants and simulation targets
    project_name = "photon_batch_geodesic_integrator_numerical"
    exec_name = "photon_batch_geodesic_integrator_numerical"
    project_dir = os.path.abspath(os.path.join(args.outdir, project_name))

    # Step 2.a: Define the target spacetime and particle type.
    SPACETIME = "Numerical"
    integrator_mode = "Numerical"
    PARTICLE = "photon"
    GEO_KEY = f"{SPACETIME}_{PARTICLE}"
    dataset_coord_system = args.dataset_coord_system
    enable_simd = False

    # Step 3: Initialize the project directory and select the infrastructure backend
    print(f"Initializing project: {project_name}")
    shutil.rmtree(project_dir, ignore_errors=True)
    os.makedirs(project_dir, exist_ok=True)

    # Step 3.a: Select the BHaH OpenMP backend for this example.
    par.set_parval_from_str("Infrastructure", "BHaH")
    par.set_parval_from_str("parallelization", "openmp")
    par.set_parval_from_str(
        "CoordSystem_to_register_CodeParameters", dataset_coord_system
    )

    # Step 4: Build the generic symbolic photon equations used by the
    # runtime numerical interpolation pipeline.
    print(f" -> Assembling symbolic data for {GEO_KEY}...")
    # Step 4.a: Bypass __init__ because these symbolic helper methods build
    # placeholder-based expressions and do not require spacetime-specific state.
    generic_geodesic_equations = geo.GeodesicEquations.__new__(geo.GeodesicEquations)
    coordinate_symbols = list(sp.symbols("t x y z", real=True))
    geodesic_rhs = generic_geodesic_equations.geodesic_eom_rhs_photon()
    p0_photon = generic_geodesic_equations.hamiltonian_constraint_photon()
    normalization_constraint_expr = (
        generic_geodesic_equations.normalization_constraint()
    )

    # Step 5: Register C functions in split-pipeline order.
    print(" -> Registering C functions and local CodeParameters...")

    # Step 5.a: Register initialization kernels.
    set_initial_conditions_kernel.set_initial_conditions_kernel(SPACETIME)

    p0_reverse_kernel.p0_reverse_kernel(p0_photon)

    # Step 5.b: Register normalization diagnostics.
    normalization_constraint.normalization_constraint(
        normalization_constraint_expr, PARTICLE
    )

    # Step 5.c: Register numerical interpolation helpers.
    register_azimuthal_interp = (
        azimuthal_symmetry_spatial_lagrange_interpolation.register_CFunction_azimuthal_symmetry_spatial_lagrange_interpolation
    )
    register_azimuthal_interp(
        dataset_coord_system, enable_simd=enable_simd, project_dir=project_dir
    )
    temporal_lagrange_interpolation.register_CFunction_temporal_lagrange_interpolation(
        enable_simd=enable_simd, project_dir=project_dir
    )
    numerical_interpolation.register_CFunction_numerical_interpolation(
        dataset_coord_system, enable_simd=enable_simd, project_dir=project_dir
    )

    # Step 5.d: Register RKF45 evolution kernels.
    calculate_ode_rhs_kernel.calculate_ode_rhs_kernel(geodesic_rhs, coordinate_symbols)
    rkf45_stage_update.rkf45_stage_update()
    rkf45_finalize_and_control_kernel.rkf45_finalize_and_control_kernel(
        enable_numerical_time_window_step_cap=True
    )

    # Step 5.e: Register event-detection and boundary-intersection kernels.
    find_event_time_and_state.find_event_time_and_state()
    handle_source_plane_intersection.handle_source_plane_intersection()
    handle_window_plane_intersection.handle_window_plane_intersection()
    event_detection_manager_kernel.event_detection_manager_kernel()
    calculate_and_fill_blueprint_data_universal.calculate_and_fill_blueprint_data_universal()

    # Step 5.f: Register project-level orchestration helpers.
    # The numerical interpolation and RKF45 finalization registrations above
    # already pull in the shared slot/time-window helpers on demand. Calling
    # them again here would append duplicate definitions into BHaH_defines.h.
    batch_integrator_numerical.batch_integrator_numerical(
        SPACETIME, dataset_coord_system
    )
    main.main(SPACETIME, integrator_mode)

    # Step 5.g: Remove helper registrations emitted only through other kernels.
    # The event manager emits these helpers through prefunc, so keeping the
    # standalone registrations would add unused source files and prototypes.
    for internal_func in [
        "find_event_time_and_state",
        "handle_source_plane_intersection",
        "handle_window_plane_intersection",
    ]:
        cfc.CFunction_dict.pop(internal_func, None)

    # Step 6: Override CodeParameter defaults before parfile generation.
    print(" -> Overriding desired photon CodeParameters before .par generation...")

    # Step 6.a: Set the numerical-spacetime data path.
    # This path intentionally stays under the repo-root raytracing cache.
    # ``--outdir`` controls only the generated photon project location.
    numerical_spacetime_bin_path = os.path.abspath(
        os.path.join(
            "project",
            "raytracing_data",
            args.bin_name,
        )
    )

    par.glb_code_params_dict["numerical_spacetime_bin_path"].defaultvalue = (
        numerical_spacetime_bin_path
    )

    # Step 6.b: Match the dataset reference-metric defaults used by the
    # combined raytracing file before metadata overrides Nxx/dxx/xxmin/xxmax.
    par.adjust_CodeParam_default("grid_physical_size", args.dataset_grid_size)
    rfm = refmetric.reference_metric[dataset_coord_system]
    for param_name, grid_size_mapping in rfm.grid_physical_size_dict.items():
        if grid_size_mapping == "grid_physical_size":
            par.adjust_CodeParam_default(param_name, args.dataset_grid_size)
        elif grid_size_mapping == "-grid_physical_size":
            par.adjust_CodeParam_default(param_name, -args.dataset_grid_size)
        else:
            raise ValueError(
                f"""Unsupported grid_physical_size mapping '{grid_size_mapping}' for {dataset_coord_system}:{param_name}"""
            )
    if dataset_coord_system == "SinhSpherical":
        assert dataset_sinhw is not None
        par.adjust_CodeParam_default("SINHW", dataset_sinhw)
    elif dataset_coord_system == "SinhCylindrical":
        assert dataset_sinhwrho is not None
        assert dataset_sinhwz is not None
        par.adjust_CodeParam_default("SINHWRHO", dataset_sinhwrho)
        par.adjust_CodeParam_default("SINHWZ", dataset_sinhwz)

    # Step 6.c: Set interpolation-order defaults.
    par.glb_code_params_dict[
        "numerical_spacetime_spatial_interp_order"
    ].defaultvalue = 3
    par.glb_code_params_dict[
        "numerical_spacetime_temporal_interp_order"
    ].defaultvalue = 3

    # Step 6.d: Set initial-condition defaults.
    par.glb_code_params_dict["t_start"].defaultvalue = 100.0
    par.glb_code_params_dict["scan_density"].defaultvalue = 100

    # Step 6.e: Set batch-integrator and numerical-limit defaults.
    par.glb_code_params_dict["p_t_max"].defaultvalue = 1000.0
    par.glb_code_params_dict["perform_normalization_check"].defaultvalue = True
    par.glb_code_params_dict["r_escape"].defaultvalue = 40.0

    # Step 6.f: Cap coordinate-time growth per accepted RKF45 step.
    par.glb_code_params_dict["rkf45_max_delta_t"].defaultvalue = 0.5

    # Step 6.g: Set time-window manager defaults.
    par.glb_code_params_dict["slot_manager_delta_t"].defaultvalue = 2.0
    par.glb_code_params_dict["slot_manager_t_min"].defaultvalue = 5.0

    # Step 6.h: Set source-plane geometry defaults.
    par.glb_code_params_dict["source_plane_center_x"].defaultvalue = -100.0
    par.glb_code_params_dict["source_plane_center_y"].defaultvalue = 0.0
    par.glb_code_params_dict["source_plane_center_z"].defaultvalue = 0.0

    par.glb_code_params_dict["source_plane_normal_x"].defaultvalue = 1.0
    par.glb_code_params_dict["source_plane_normal_y"].defaultvalue = 0.0
    par.glb_code_params_dict["source_plane_normal_z"].defaultvalue = 0.0

    par.glb_code_params_dict["source_r_max"].defaultvalue = 30.0
    par.glb_code_params_dict["source_r_min"].defaultvalue = 0.0

    par.glb_code_params_dict["source_up_vec_x"].defaultvalue = 0.0
    par.glb_code_params_dict["source_up_vec_y"].defaultvalue = 1.0
    par.glb_code_params_dict["source_up_vec_z"].defaultvalue = 0.0

    # Step 6.i: Set camera window geometry defaults.
    par.glb_code_params_dict["camera_pos_x"].defaultvalue = 11.0
    par.glb_code_params_dict["camera_pos_y"].defaultvalue = 0.0
    par.glb_code_params_dict["camera_pos_z"].defaultvalue = 0.0

    par.glb_code_params_dict["original_window_center_x"].defaultvalue = 10.0
    par.glb_code_params_dict["original_window_center_y"].defaultvalue = 0.0
    par.glb_code_params_dict["original_window_center_z"].defaultvalue = 0.0

    par.glb_code_params_dict["window_height"].defaultvalue = 1.0
    par.glb_code_params_dict["window_width"].defaultvalue = 1.0

    par.glb_code_params_dict["window_up_vec_x"].defaultvalue = 0.0
    par.glb_code_params_dict["window_up_vec_y"].defaultvalue = 0.0
    par.glb_code_params_dict["window_up_vec_z"].defaultvalue = 1.0

    # Step 6.j: Set the fixed CPU tiling defaults.
    par.glb_code_params_dict["window_tiles_width"].defaultvalue = 1
    par.glb_code_params_dict["window_tiles_height"].defaultvalue = 1

    # Step 6.k: Set RKF45 controller defaults.
    par.glb_code_params_dict["numerical_initial_h"].defaultvalue = 0.05
    par.glb_code_params_dict["rkf45_absolute_error_tolerance"].defaultvalue = 1.0e-8
    par.glb_code_params_dict["rkf45_error_tolerance"].defaultvalue = 1.0e-8
    par.glb_code_params_dict["rkf45_h_max"].defaultvalue = 10.0
    par.glb_code_params_dict["rkf45_h_min"].defaultvalue = 1.0e-15

    print(f" -> Numerical spacetime .bin path: {numerical_spacetime_bin_path}")
    print(f" -> Dataset coordinate system: {dataset_coord_system}")
    print(f" -> Dataset grid size: {args.dataset_grid_size}")
    if dataset_sinhw is not None:
        print(f" -> Dataset SINHW: {dataset_sinhw}")
    if dataset_sinhwrho is not None:
        print(f" -> Dataset SINHWRHO: {dataset_sinhwrho}")
    if dataset_sinhwz is not None:
        print(f" -> Dataset SINHWZ: {dataset_sinhwz}")

    # Step 6.l: Generate C code for parameter handling.
    print(" -> Generating parameter handling code...")
    CPs.write_CodeParameters_h_files(project_dir=project_dir, set_commondata_only=True)
    CPs.register_CFunctions_params_commondata_struct_set_to_default()
    cmdline_input_and_parfiles.generate_default_parfile(
        project_dir=project_dir, project_name=project_name
    )
    cmdline_input_and_parfiles.register_CFunction_cmdline_input_and_parfile_parser(
        project_name=project_name,
        cmdline_inputs=[
            "source_r_min",
            "source_r_max",
            "window_width",
            "window_height",
            "window_tiles_width",
            "window_tiles_height",
            "scan_density",
        ],
    )

    # Step 7: Assemble the generated C project.
    print(" -> Assembling C project on disk...")

    # Step 7.a: Map the shared CUDA-style helpers onto OpenMP.
    cpu_macros = {
        "ReadCUDA(ptr)": "#define ReadCUDA(ptr) (*(ptr))\n",
        "WriteCUDA(ptr, val)": "#define WriteCUDA(ptr, val) (*(ptr) = (val))\n",
        "BHAH_MALLOC_DEVICE(a, sz)": (
            "#define BHAH_MALLOC_DEVICE(a, sz) BHAH_MALLOC(a, sz)\n"
        ),
        "BHAH_FREE_DEVICE(a)": "#define BHAH_FREE_DEVICE(a) BHAH_FREE(a)\n",
        "MulCUDA(a, b)": "#define MulCUDA(a, b) ((a) * (b))\n",
        "DivCUDA(a, b)": "#define DivCUDA(a, b) ((a) / (b))\n",
        "AddCUDA(a, b)": "#define AddCUDA(a, b) ((a) + (b))\n",
        "FusedMulAddCUDA(a, b, c)": (
            "#define FusedMulAddCUDA(a, b, c) ((a) * (b) + (c))\n"
        ),
        "AbsCUDA(val)": "#define AbsCUDA(val) fabs(val)\n",
        "SqrtCUDA(val)": "#define SqrtCUDA(val) sqrt(val)\n",
        "PowCUDA(a, b)": "#define PowCUDA(a, b) pow(a, b)\n",
        "BHAH_HD_FUNC": "#define BHAH_HD_FUNC\n",
        "BHAH_HD_INLINE": "#define BHAH_HD_INLINE static inline\n",
        "BHAH_WARP_ATOMIC_ADD(ptr, val)": (
            "#define BHAH_WARP_ATOMIC_ADD(ptr, val) "
            '_Pragma("omp atomic") *(ptr) += (val)\n'
        ),
        "GLOBAL_COMMONDATA_EXTERN": (
            "// CPU passes commondata by reference, no global needed.\n"
        ),
        "BHAH_DEVICE_SYNC()": "#define BHAH_DEVICE_SYNC() do {} while(0)\n",
    }

    # Step 7.b: Match the combined raytracing payload layout, which uses
    # NGHOSTS = 3.
    BHaH_defines_h.output_BHaH_defines_h(
        project_dir=project_dir,
        enable_rfm_precompute=False,
        fin_NGHOSTS_add_one_for_upwinding_or_KO=True,
        supplemental_defines_dict=cpu_macros,
    )

    compiler = "gcc"
    cflags = [
        "-fopenmp",
        "-O3",
        "-fno-omit-frame-pointer",
        "-DDEBUG",
        "-Wno-stringop-truncation",
    ]
    libs = ["-lm"]
    ext = "c"

    print(" -> Generating Makefile")

    # Step 7.c: Select the Makefile optimization profile.
    opt_option = "fast"

    Makefile.output_CFunctions_function_prototypes_and_construct_Makefile(
        project_dir=project_dir,
        project_name=project_name,
        exec_or_library_name=exec_name,
        compiler_opt_option=opt_option,
        addl_CFLAGS=cflags,
        addl_libraries=libs,
        CC=compiler,
        src_code_file_ext=ext,
    )
    # Step 8: Copy helper scripts and print usage instructions.
    vis_dir = os.path.join("nrpy", "examples", "geodesic_visualizations")
    vis_script_src = os.path.join(vis_dir, "visualize_lensed_image.py")
    config_src = os.path.join(vis_dir, "blueprint_config_and_schema.py")
    render_src = os.path.join(vis_dir, "render_lensed_image.py")
    blueprint_analysis_src = os.path.join(vis_dir, "blueprint_analysis.py")

    for script_src in (
        vis_script_src,
        config_src,
        render_src,
        blueprint_analysis_src,
    ):
        shutil.copy(script_src, project_dir)

    # Step 8.a: Build helper commands from CodeParameter defaults.
    c_r_min = float(par.glb_code_params_dict["source_r_min"].defaultvalue)
    c_r_max = float(par.glb_code_params_dict["source_r_max"].defaultvalue)
    c_window_width = float(par.glb_code_params_dict["window_width"].defaultvalue)
    c_window_height = float(par.glb_code_params_dict["window_height"].defaultvalue)
    c_tiles_width = int(par.glb_code_params_dict["window_tiles_width"].defaultvalue)
    c_tiles_height = int(par.glb_code_params_dict["window_tiles_height"].defaultvalue)
    c_pixel_width = 600
    data_request_file = "numerical_spacetime_data_request.json"
    data_prep_command = f"python3 combined_raytracing_bin_helper.py {data_request_file}"
    parfile_path = os.path.join(project_dir, f"{project_name}.par")

    vis_command = " ".join(
        [
            "python3 visualize_lensed_image.py",
            f"--source_r_min {c_r_min}",
            f"--source_r_max {c_r_max}",
            f"--window_width {c_window_width}",
            f"--window_height {c_window_height}",
            f"--window_tiles_width {c_tiles_width}",
            f"--window_tiles_height {c_tiles_height}",
            f"--pixel_width {c_pixel_width}",
        ]
    )

    print(f"Finished! Now go into {project_dir}.")
    print(f"    Parameter file can be found at {parfile_path}\n")
    print("    To prepare the required numerical spacetime data, run:")
    print(f"    {data_prep_command}\n")
    print("    Then build and run the photon executable:")
    print("    make")
    print(f"    ./{exec_name}\n")
    print(
        """    To generate the lensed image after running the C executable, ensure you have the required Python packages:"""
    )
    print("    pip install matplotlib numpy numba Pillow\n")
    print(
        "    Then, execute the visualization script directly from the project directory:"
    )
    print(f"    {vis_command}\n")

    blueprint_command = " ".join(
        [
            "python3 blueprint_analysis.py",
            f"--window_tiles_width {c_tiles_width}",
            f"--window_tiles_height {c_tiles_height}",
            f"--window_width {c_window_width}",
            f"--window_height {c_window_height}",
        ]
    )

    print("    To run the blueprint diagnostic:")
    print(f"    {blueprint_command}\n")
