"""
Orchestrator for the CPU numerical-spacetime single-photon geodesic integrator.

This module constructs the standalone C project that evolves one photon through
a numerical spacetime sourced from the combined raytracing ``.bin`` generated
from ``two_blackholes_collide.py --raytracing-time ...``. It retains the batch
example's command-line inputs, numerical interpolation setup, parameter
defaults, and RKF45 registrations, but selects the single-photon integrator and
writes accepted trajectory states to ``trajectory.txt``.

Author: Dalton J. Moone
        daltonmoone **at** gmail **dot** com
"""

import argparse
import os
import shutil
import sys
from typing import List, Optional

import sympy as sp

import nrpy.params as par
import nrpy.reference_metric as refmetric
from nrpy.equations.general_relativity.geodesics import geodesics as geo
from nrpy.infrastructures.BHaH import BHaH_defines_h
from nrpy.infrastructures.BHaH import CodeParameters as CPs
from nrpy.infrastructures.BHaH import Makefile_helpers as Makefile
from nrpy.infrastructures.BHaH import cmdline_input_and_parfiles
from nrpy.infrastructures.BHaH.general_relativity.geodesics import (
    normalization_constraint,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.interpolation import (
    azimuthal_symmetry_spatial_lagrange_interpolation,
    numerical_interpolation,
    temporal_lagrange_interpolation,
    temporal_lagrange_interpolation_c1,
    time_window_manager_numerical,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.photon import (
    calculate_ode_rhs_kernel,
    main_single,
    normalization_constraint_photon_normalized,
    p0_reverse_kernel,
    photon_momentum_to_normalized_kernel,
    rkf45_finalize_and_control_kernel,
    rkf45_stage_update,
    single_integrator_numerical,
)


def _require(condition: bool, message: str) -> None:
    """
    Raise ``ValueError`` if an argument validation condition fails.

    :param condition: Condition that must hold.
    :param message: Description of the violated constraint.
    :raises ValueError: If ``condition`` is false.
    """
    if not condition:
        raise ValueError(message)


SUPPORTED_NUMERICAL_COORDINATE_SYSTEMS = ("SinhCylindricalv2n2",)
SUPPORTED_INTERPOLATION_METHODS = ("g4DD", "g4DD_d0", "GammaUDD")


def _build_parser() -> argparse.ArgumentParser:
    """
    Build the numerical photon single-geodesic generator argument parser.

    :return: Configured command-line argument parser.
    """
    parser = argparse.ArgumentParser(
        description="""Generate the Split-Pipeline Photon Geodesic Integrator (Numerical). Requires a numerical spacetime .bin file generated by two_blackholes_collide.py.""",
        epilog="""To generate the desired numerical spacetime data, run:
python3 two_blackholes_collide.py --raytracing-time T_FINAL DIAGNOSTICS_OUTPUT_EVERY --raytracing-coord-system CoordSystem --raytracing-Nxx NXX0 NXX1 NXX2 --raytracing-domain ...

Then rerun this photon script using the .bin filename printed to the terminal by two_blackholes_collide.py, e.g.:
python3 photon_single_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_z1_0p5_z2_neg0p5_M1_0p5_M2_0p5_SinhCylindricalv2n2_sinhwrho_0p25_sinhwz_0p4_rho-slope_0p0625_z-slope_0p0625_72_2_12.bin --coord-system-numerical SinhCylindricalv2n2 --domain 7.5 0.25 0.4 0.0625 0.0625 --t-numerical-initial 5.0 --t-numerical-end 100.0 --dt-spacetime-data 0.5""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--bin-name",
        type=str,
        required=True,
        help="""Name of the numerical spacetime .bin file inside project/raytracing_data.""",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="project",
        help="The parent directory where the generated C project will reside.",
    )
    parser.add_argument(
        "--coord-system-numerical",
        type=str,
        required=True,
        choices=SUPPORTED_NUMERICAL_COORDINATE_SYSTEMS,
        help="""Coordinate system used when generating the numerical spacetime dataset.""",
    )
    parser.add_argument(
        "--domain",
        nargs="+",
        type=float,
        required=True,
        help="""SinhCylindricalv2n2 domain: GRID_PHYSICAL_SIZE SINHWRHO SINHWZ RHO_SLOPE Z_SLOPE.""",
    )
    parser.add_argument(
        "--t-numerical-initial",
        type=float,
        required=True,
        help="""Coordinate time of the first numerical spacetime slice.""",
    )
    parser.add_argument(
        "--t-numerical-end",
        type=float,
        required=True,
        help="""Coordinate time of the final stored numerical slice. After this time the numerical spacetime is frozen to that final slice.""",
    )
    parser.add_argument(
        "--dt-spacetime-data",
        type=float,
        required=True,
        help="""Uniform physical coordinate-time spacing of the numerical spacetime data.""",
    )
    parser.add_argument(
        "--initial-time",
        "--time-start",
        dest="initial_t",
        type=float,
        default=28.0,
        help="""Initial coordinate time assigned to the photon. --time-start is a compatibility alias.""",
    )
    parser.add_argument(
        "--initial-position",
        dest="initial_position",
        nargs=3,
        type=float,
        default=[10.0, 0.0, 0.0],
        metavar=("X", "Y", "Z"),
        help="""Initial Cartesian photon position.""",
    )
    parser.add_argument(
        "--initial-momentum",
        dest="initial_momentum",
        nargs=3,
        type=float,
        default=[-1.0, 0.0, 0.0],
        metavar=("PX", "PY", "PZ"),
        help="""Initial spatial photon momentum components.""",
    )
    parser.add_argument(
        "--r-escape",
        dest="r_escape",
        type=float,
        default=25.0,
        help="""Escape radius used to terminate the trajectory.""",
    )
    parser.add_argument(
        "--eom",
        type=str,
        choices=("geodesic", "normalized"),
        default="geodesic",
        help="""Photon equations of motion: direct affine-parameter geodesics or normalized coordinate-time evolution.""",
    )
    parser.add_argument(
        "--interpolation-method",
        choices=SUPPORTED_INTERPOLATION_METHODS,
        default="g4DD",
        help="""Numerical spacetime payload and interpolation method.""",
    )

    return parser


def _parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    """
    Parse numerical photon single-geodesic generator arguments.

    :param argv: Optional argument list; defaults to ``sys.argv`` when omitted.
    :return: Parsed command-line arguments.
    """
    return _build_parser().parse_args(argv)


if __name__ == "__main__":
    # Step 1: Configure command-line arguments for the generation pipeline.
    parser = _build_parser()
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    args = _parse_args()
    normalized_eom = args.eom == "normalized"
    interpolation_method = args.interpolation_method

    _require(
        os.path.basename(args.bin_name) == args.bin_name,
        "--bin-name must be a filename only, not a path.",
    )
    _require(
        args.bin_name.endswith(".bin"),
        "--bin-name must name a numerical spacetime .bin file.",
    )
    _require(
        args.dt_spacetime_data > 0.0,
        "--dt-spacetime-data must be positive.",
    )
    _require(
        len(args.domain) > 0,
        "--domain requires at least one value.",
    )
    _require(
        args.initial_t >= 0.0,
        "--initial-time must be nonnegative.",
    )
    _require(
        args.r_escape > 0.0,
        "--r-escape must be positive.",
    )
    _require(
        sum(momentum * momentum for momentum in args.initial_momentum) > 0.0,
        "--initial-momentum must not be zero.",
    )
    _require(
        args.t_numerical_initial < args.t_numerical_end,
        "--t-numerical-initial must be strictly less than --t-numerical-end.",
    )
    domain = list(args.domain)
    grid_physical_size = None
    sinhw_numerical_rho = None
    sinhw_numerical_z = None
    rho_slope = None
    z_slope = None
    if args.coord_system_numerical == "SinhCylindricalv2n2":
        _require(
            len(domain) == 5,
            """--coord-system-numerical SinhCylindricalv2n2 requires --domain GRID_PHYSICAL_SIZE SINHWRHO SINHWZ RHO_SLOPE Z_SLOPE.""",
        )
        (
            grid_physical_size,
            sinhw_numerical_rho,
            sinhw_numerical_z,
            rho_slope,
            z_slope,
        ) = domain
        _require(sinhw_numerical_rho > 0.0, "SINHWRHO must be positive.")
        _require(sinhw_numerical_z > 0.0, "SINHWZ must be positive.")
        _require(rho_slope > 0.0, "RHO_SLOPE must be positive.")
        _require(z_slope > 0.0, "Z_SLOPE must be positive.")
    else:
        raise ValueError(
            f"Unsupported numerical coordinate system: {args.coord_system_numerical}."
        )
    assert grid_physical_size is not None
    _require(grid_physical_size > 0.0, "GRID_PHYSICAL_SIZE must be positive.")
    # Step 2: Define strict project constants and simulation targets
    project_name = f"photon_single_geodesic_integrator_numerical_{interpolation_method}"
    exec_name = project_name
    project_dir = os.path.abspath(os.path.join(args.outdir, project_name))

    # Step 2.a: Define the target spacetime and particle type.
    SPACETIME = "Numerical"
    PARTICLE = "photon"
    GEO_KEY = f"{SPACETIME}_{PARTICLE}"
    coord_system_numerical = args.coord_system_numerical
    enable_simd = False

    # Step 3: Initialize the project directory and select the infrastructure backend
    print(f"Initializing project: {project_name}")
    shutil.rmtree(project_dir, ignore_errors=True)
    os.makedirs(project_dir, exist_ok=True)

    # Step 3.a: Select the BHaH OpenMP backend for this example.
    par.set_parval_from_str("Infrastructure", "BHaH")
    par.set_parval_from_str("parallelization", "openmp")
    par.set_parval_from_str(
        "CoordSystem_to_register_CodeParameters", coord_system_numerical
    )

    # Step 4: Build generic symbolic photon data for numerical evolution.
    print(f" -> Assembling symbolic data for {GEO_KEY}...")
    # Step 4.a: Bypass __init__ because these symbolic helper methods build
    # placeholder-based expressions and do not require spacetime-specific state.
    generic_geodesic_equations = geo.GeodesicEquations.__new__(geo.GeodesicEquations)
    coordinate_symbols = list(sp.symbols("t x y z", real=True))
    if interpolation_method == "GammaUDD":
        geodesic_rhs = (
            generic_geodesic_equations.geodesic_eom_rhs_photon_normalized_christoffel()
            if normalized_eom
            else generic_geodesic_equations.geodesic_eom_rhs_photon_christoffel()
        )
    else:
        geodesic_rhs = (
            generic_geodesic_equations.geodesic_eom_rhs_photon_normalized()
            if normalized_eom
            else generic_geodesic_equations.geodesic_eom_rhs_photon()
        )
    p0_photon = generic_geodesic_equations.hamiltonian_constraint_photon()
    normalization_constraint_expr = (
        generic_geodesic_equations.normalization_constraint_photon_normalized()
        if normalized_eom
        else generic_geodesic_equations.normalization_constraint()
    )
    # Step 5: Register C functions in split-pipeline order.
    print(" -> Registering C functions and local CodeParameters...")

    # Step 5.a: Register the initial null solve.
    p0_reverse_kernel.p0_reverse_kernel(p0_photon)
    if normalized_eom:
        u_expr, PiD_exprs = (
            geo.GeodesicEquations.photon_momentum_to_normalized_quantities()
        )
        photon_momentum_to_normalized_kernel.photon_momentum_to_normalized_kernel(
            u_expr, PiD_exprs
        )

    # Step 5.b: Register normalization diagnostics.
    if normalized_eom:
        normalization_constraint_photon_normalized.normalization_constraint_photon_normalized(
            normalization_constraint_expr
        )
    else:
        normalization_constraint.normalization_constraint(
            normalization_constraint_expr, PARTICLE
        )

    # Step 5.c: Register numerical interpolation helpers.
    register_azimuthal_interp = (
        azimuthal_symmetry_spatial_lagrange_interpolation.register_CFunction_azimuthal_symmetry_spatial_lagrange_interpolation
    )
    register_azimuthal_interp(
        coord_system_numerical,
        interpolation_method=interpolation_method,
        enable_simd=enable_simd,
        project_dir=project_dir,
    )
    temporal_lagrange_interpolation.register_CFunction_temporal_lagrange_interpolation(
        interpolation_method=interpolation_method,
        enable_simd=enable_simd,
        project_dir=project_dir,
    )
    temporal_lagrange_interpolation_c1.register_CFunction_temporal_lagrange_interpolation_c1(
        enable_simd=enable_simd, project_dir=project_dir
    )
    time_window_manager_numerical.time_window_manager_numerical(interpolation_method)
    numerical_interpolation.register_CFunction_numerical_interpolation(
        coord_system_numerical,
        interpolation_method=interpolation_method,
        enable_simd=enable_simd,
        project_dir=project_dir,
        normalized_eom=normalized_eom,
    )

    # Step 5.e: Register RKF45 evolution kernels.
    calculate_ode_rhs_kernel.calculate_ode_rhs_kernel(
        geodesic_rhs,
        coordinate_symbols,
        normalized_eom=normalized_eom,
        interpolation_method=interpolation_method,
    )
    rkf45_stage_update.rkf45_stage_update()
    rkf45_finalize_and_control_kernel.rkf45_finalize_and_control_kernel(
        enable_numerical_time_window_step_cap=True,
        normalized_eom=normalized_eom,
        register_numerical_initial_h=False,
    )

    # Step 5.f: Register the single-photon integration function and C entry point.
    # The numerical interpolation and RKF45 registrations above pull in the
    # shared slot/time-window helpers required by the single integrator.
    single_integrator_numerical.single_integrator_numerical(
        SPACETIME,
        coord_system_numerical,
        interpolation_method=interpolation_method,
        normalized_eom=normalized_eom,
    )
    main_single.main_single("single_integrator_numerical")

    # Step 6: Override CodeParameter defaults before parfile generation.
    print(" -> Overriding desired photon CodeParameters before .par generation...")

    # Step 6.a: Set the numerical-spacetime data path.
    # This path intentionally stays under the repo-root raytracing cache.
    # ``--outdir`` controls only the generated photon project location.
    numerical_spacetime_bin_path = os.path.abspath(
        os.path.join(
            "project",
            "raytracing_data",
            args.bin_name,
        )
    )

    par.adjust_CodeParam_default(
        "numerical_spacetime_bin_path", numerical_spacetime_bin_path
    )

    # Step 6.b: Match the dataset reference-metric defaults used by the
    # combined raytracing file before metadata overrides Nxx/dxx/xxmin/xxmax.
    par.adjust_CodeParam_default("grid_physical_size", grid_physical_size)
    rfm = refmetric.reference_metric[coord_system_numerical]
    for param_name, grid_size_mapping in rfm.grid_physical_size_dict.items():
        if grid_size_mapping == "grid_physical_size":
            par.adjust_CodeParam_default(param_name, grid_physical_size)
        elif grid_size_mapping == "-grid_physical_size":
            par.adjust_CodeParam_default(param_name, -grid_physical_size)
        else:
            raise ValueError(
                f"""Unsupported grid_physical_size mapping '{grid_size_mapping}' for {coord_system_numerical}:{param_name}"""
            )
    assert sinhw_numerical_rho is not None
    assert sinhw_numerical_z is not None
    assert rho_slope is not None
    assert z_slope is not None
    par.adjust_CodeParam_default("SINHWRHO", sinhw_numerical_rho)
    par.adjust_CodeParam_default("SINHWZ", sinhw_numerical_z)
    par.adjust_CodeParam_default("rho_slope", rho_slope)
    par.adjust_CodeParam_default("z_slope", z_slope)

    # Step 6.c: Set interpolation-order defaults.
    par.adjust_CodeParam_default("numerical_spacetime_spatial_interp_order", 3)
    par.adjust_CodeParam_default("numerical_spacetime_temporal_interp_order", 3)

    # Step 6.d: Set direct initial-condition defaults.
    par.adjust_CodeParam_default("initial_t", args.initial_t)
    for name, value in zip(
        ["initial_x", "initial_y", "initial_z"], args.initial_position
    ):
        par.adjust_CodeParam_default(name, value)
    for name, value in zip(
        ["initial_p_x", "initial_p_y", "initial_p_z"], args.initial_momentum
    ):
        par.adjust_CodeParam_default(name, value)
    par.adjust_CodeParam_default("initial_integration_param", 0.0)
    par.adjust_CodeParam_default("initial_eulerian_distance", 0.0)
    par.adjust_CodeParam_default("initial_h", -0.05 if normalized_eom else 0.05)

    # Step 6.e: Set single-integrator and numerical-limit defaults.
    par.adjust_CodeParam_default(
        "evolution_measure_max", 3.0 if normalized_eom else 1000.0
    )
    par.adjust_CodeParam_default("perform_normalization_check", True)
    par.adjust_CodeParam_default("r_escape", args.r_escape)

    # Step 6.f: Set the lower analytic / numerical transition defaults.
    par.adjust_CodeParam_default("t_numerical_initial", args.t_numerical_initial)
    par.adjust_CodeParam_default("t_numerical_end", args.t_numerical_end)
    par.adjust_CodeParam_default("dt_numerical_spacetime_data", args.dt_spacetime_data)
    # Keep sparse retained-slice debugging disabled for normal runs.
    par.adjust_CodeParam_default("numerical_spacetime_time_slice_stride", 1)

    # Step 6.f: Cap coordinate-time growth per accepted RKF45 step.
    par.adjust_CodeParam_default("rkf45_max_delta_t", 0.5)

    # Step 6.g: Set time-window manager defaults.
    par.adjust_CodeParam_default("slot_manager_delta_t", 5.0)
    par.adjust_CodeParam_default("slot_manager_t_min", -150.0)

    # Step 6.h: Set RKF45 controller defaults.
    par.adjust_CodeParam_default("rkf45_absolute_error_tolerance", 1.0e-8)
    par.adjust_CodeParam_default("rkf45_error_tolerance", 1.0e-8)
    par.adjust_CodeParam_default("rkf45_h_max", 10.0)
    par.adjust_CodeParam_default("rkf45_h_min", 1.0e-4)
    if normalized_eom:
        par.adjust_CodeParam_default("rkf45_log_energy_tolerance", 1.0e0)

    print(f" -> Numerical spacetime .bin path: {numerical_spacetime_bin_path}")
    print(f" -> Numerical coordinate system: {coord_system_numerical}")
    print(f" -> Interpolation method: {interpolation_method}")
    print(f" -> Photon equations of motion: {args.eom}")
    print(f" -> Numerical domain: {domain}")
    print(f" -> Numerical SINHWRHO: {sinhw_numerical_rho}")
    print(f" -> Numerical SINHWZ: {sinhw_numerical_z}")
    print(f" -> Numerical rho_slope: {rho_slope}")
    print(f" -> Numerical z_slope: {z_slope}")
    print(f" -> initial_t: {args.initial_t}")
    print(f" -> initial_position: {args.initial_position}")
    print(f" -> initial_momentum: {args.initial_momentum}")
    print(f" -> r_escape: {args.r_escape}")
    print(f" -> t_numerical_initial: {args.t_numerical_initial}")
    print(f" -> t_numerical_end: {args.t_numerical_end}")
    print(f" -> dt_spacetime_data: {args.dt_spacetime_data}")

    # Step 6.k: Generate C code for parameter handling.
    print(" -> Generating parameter handling code...")
    CPs.write_CodeParameters_h_files(project_dir=project_dir, set_commondata_only=True)
    CPs.register_CFunctions_params_commondata_struct_set_to_default()
    cmdline_input_and_parfiles.generate_default_parfile(
        project_dir=project_dir, project_name=project_name
    )
    cmdline_input_and_parfiles.register_CFunction_cmdline_input_and_parfile_parser(
        project_name=project_name
    )

    # Step 7: Assemble the generated C project.
    print(" -> Assembling C project on disk...")

    # Step 7.a: Map the shared CUDA-style helpers onto OpenMP.
    cpu_macros = {
        "ReadCUDA(ptr)": "#define ReadCUDA(ptr) (*(ptr))\n",
        "WriteCUDA(ptr, val)": "#define WriteCUDA(ptr, val) (*(ptr) = (val))\n",
        "BHAH_MALLOC_DEVICE(a, sz)": (
            "#define BHAH_MALLOC_DEVICE(a, sz) BHAH_MALLOC(a, sz)\n"
        ),
        "BHAH_FREE_DEVICE(a)": "#define BHAH_FREE_DEVICE(a) BHAH_FREE(a)\n",
        "MulCUDA(a, b)": "#define MulCUDA(a, b) ((a) * (b))\n",
        "DivCUDA(a, b)": "#define DivCUDA(a, b) ((a) / (b))\n",
        "AddCUDA(a, b)": "#define AddCUDA(a, b) ((a) + (b))\n",
        "FusedMulAddCUDA(a, b, c)": (
            "#define FusedMulAddCUDA(a, b, c) ((a) * (b) + (c))\n"
        ),
        "AbsCUDA(val)": "#define AbsCUDA(val) fabs(val)\n",
        "SqrtCUDA(val)": "#define SqrtCUDA(val) sqrt(val)\n",
        "PowCUDA(a, b)": "#define PowCUDA(a, b) pow(a, b)\n",
        "BHAH_HD_FUNC": "#define BHAH_HD_FUNC\n",
        "BHAH_HD_INLINE": "#define BHAH_HD_INLINE static inline\n",
        "BHAH_WARP_ATOMIC_ADD(ptr, val)": (
            "#define BHAH_WARP_ATOMIC_ADD(ptr, val) "
            '_Pragma("omp atomic") *(ptr) += (val)\n'
        ),
        "GLOBAL_COMMONDATA_EXTERN": (
            "// CPU passes commondata by reference, no global needed.\n"
        ),
        "BHAH_DEVICE_SYNC()": "#define BHAH_DEVICE_SYNC() do {} while(0)\n",
    }

    # Step 7.b: Match the combined raytracing payload layout, which uses
    # NGHOSTS = 3.
    BHaH_defines_h.output_BHaH_defines_h(
        project_dir=project_dir,
        enable_rfm_precompute=False,
        fin_NGHOSTS_add_one_for_upwinding_or_KO=True,
        supplemental_defines_dict=cpu_macros,
    )

    compiler = "gcc"
    cflags = [
        "-fopenmp",
        "-O3",
        "-fno-omit-frame-pointer",
        "-DDEBUG",
        "-Wno-stringop-truncation",
    ]
    libs = ["-lm"]
    ext = "c"

    print(" -> Generating Makefile")

    # Step 7.c: Select the Makefile optimization profile.
    opt_option = "fast"

    Makefile.output_CFunctions_function_prototypes_and_construct_Makefile(
        project_dir=project_dir,
        project_name=project_name,
        exec_or_library_name=exec_name,
        compiler_opt_option=opt_option,
        addl_CFLAGS=cflags,
        addl_libraries=libs,
        CC=compiler,
        src_code_file_ext=ext,
    )
    # Step 8: Copy the trajectory visualizer and print usage instructions.
    vis_dir = os.path.join("nrpy", "examples", "geodesic_visualizations")
    vis_script_src = os.path.join(vis_dir, "visualize_trajectory.py")
    if os.path.exists(vis_script_src):
        shutil.copy(vis_script_src, project_dir)
    else:
        print(
            "Warning: visualize_trajectory.py was not found; the integrator "
            "project was still generated."
        )

    parfile_path = os.path.join(project_dir, f"{project_name}.par")

    print(f"Finished! Now go into {project_dir}.")
    print(f"    Parameter file can be found at {parfile_path}\n")
    print("    Build and run the photon executable:")
    print("    make")
    print(f"    ./{exec_name} {project_name}.par\n")
    print("    Accepted trajectory samples are written to trajectory.txt.")
    print("    To generate the trajectory plot, install the required Python packages:")
    print("    pip install matplotlib numpy\n")
    print("    To visualize the trajectory, run:")
    print("    python3 visualize_trajectory.py --particle_type Photon\n")
