"""
Orchestrator for the CPU numerical-spacetime photon geodesic integrator.

This module constructs the C project that evolves batched photon trajectories
through a numerical spacetime sourced from the combined raytracing ``.bin``
generated from ``two_blackholes_collide.py --raytracing-time ...``.

The generated code keeps the existing Structure-of-Arrays photon pipeline and
adaptive RKF45 stepping, but metric and Christoffel evaluations now use a
piecewise analytic/numerical interpolation pipeline. One user-selected static
analytic spacetime covers the lower-time region, while the intermediate and
late-time coordinate interval uses the numerical interpolation helpers fed by
the combined numerical-spacetime dataset, freezing the numerical spacetime to
its final stored slice after `t_numerical_end`.

This example currently generates a CPU/OpenMP project.

Author: Dalton J. Moone
        daltonmoone **at** gmail **dot** com
"""

import argparse
import os
import shutil
import sys
import warnings

import sympy as sp

import nrpy.c_function as cfc
import nrpy.params as par
import nrpy.reference_metric as refmetric
from nrpy.equations.general_relativity.geodesics import geodesics as geo
from nrpy.infrastructures.BHaH import BHaH_defines_h
from nrpy.infrastructures.BHaH import CodeParameters as CPs
from nrpy.infrastructures.BHaH import Makefile_helpers as Makefile
from nrpy.infrastructures.BHaH import cmdline_input_and_parfiles
from nrpy.infrastructures.BHaH.general_relativity.geodesics import (
    connections,
    g4DD_metric,
    normalization_constraint,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.interpolation import (
    azimuthal_symmetry_spatial_lagrange_interpolation_metric_derivatives,
    numerical_interpolation_metric_derivatives,
    temporal_lagrange_interpolation_metric_derivatives,
    temporal_lagrange_interpolation_metric_derivatives_c1_startup,
)
from nrpy.infrastructures.BHaH.general_relativity.geodesics.photon import (
    batch_integrator_numerical,
    calculate_and_fill_blueprint_data_universal,
    calculate_ode_rhs_kernel,
    event_detection_manager_kernel,
    find_event_time_and_state,
    handle_source_plane_intersection,
    handle_window_plane_intersection,
    main,
    normalization_constraint_photon_normalized,
    p0_reverse_kernel,
    photon_momentum_to_normalized_kernel,
    rkf45_5th_state,
    rkf45_finalize_and_control_kernel,
    rkf45_numerical_control,
    rkf45_stage_update,
    set_initial_conditions_kernel,
)


def _require(condition: bool, message: str) -> None:
    """
    Raise ``ValueError`` if an argument validation condition fails.

    :param condition: Condition that must hold.
    :param message: Description of the violated constraint.
    :raises ValueError: If ``condition`` is false.
    """
    if not condition:
        raise ValueError(message)


BRILL_LINDQUIST_CARTESIAN = "BrillLindquist_Cartesian"


if __name__ == "__main__":
    # Step 1: Configure command-line arguments for the generation pipeline
    parser = argparse.ArgumentParser(
        description="""Generate the Split-Pipeline Photon Geodesic Integrator (Numerical). Requires a numerical spacetime .bin file generated by two_blackholes_collide.py.""",
        epilog="""To generate the desired numerical spacetime data, run:
python3 two_blackholes_collide.py --raytracing-time T_FINAL DIAGNOSTICS_OUTPUT_EVERY --raytracing-coord-system CoordSystem --raytracing-Nxx NXX0 NXX1 NXX2 --raytracing-domain ...

Then rerun this photon script using the .bin filename printed to the terminal by two_blackholes_collide.py, e.g.:
python3 photon_batch_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_SinhSpherical_sinhw_0p4_72_12_2.bin --coord-system-numerical SinhSpherical --domain 7.5 0.4 --analytical-metric-0 KerrSchild_Cartesian --t-metric-0 5.0 --t-numerical-end 100.0 --dt-spacetime-data 0.5

or:
python3 photon_batch_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_SinhCylindrical_sinhwrho_0p25_sinhwz_0p4_72_2_12.bin --coord-system-numerical SinhCylindrical --domain 7.5 0.25 0.4 --analytical-metric-0 KerrSchild_Cartesian --t-metric-0 5.0 --t-numerical-end 100.0 --dt-spacetime-data 0.5

or:
python3 photon_batch_geodesic_integrator_numerical.py --bin-name two_blackholes_collide_7p5_7p5_0p25_z1_0p5_z2_neg0p5_M1_0p5_M2_0p5_SinhCylindricalv2n2_sinhwrho_0p25_sinhwz_0p4_rho-slope_0p0625_z-slope_0p0625_72_2_12.bin --coord-system-numerical SinhCylindricalv2n2 --domain 7.5 0.25 0.4 0.0625 0.0625 --analytical-metric-0 BrillLindquist_Cartesian --brill-lindquist-bhs 0.5 -0.5 0.5 0.5 --t-metric-0 5.0 --t-numerical-end 100.0 --dt-spacetime-data 0.5""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--bin-name",
        type=str,
        required=True,
        help="""Name of the numerical spacetime .bin file inside project/raytracing_data.""",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="project",
        help="The parent directory where the generated C project will reside.",
    )
    parser.add_argument(
        "--coord-system-numerical",
        type=str,
        required=True,
        choices=refmetric.supported_CoordSystems,
        help="""Coordinate system used when generating the numerical spacetime dataset. Required by the spatial interpolation pipeline.""",
    )
    parser.add_argument(
        "--domain",
        nargs="+",
        type=float,
        required=True,
        help="""Coordinate-system-specific domain parameters used when generating the numerical spacetime dataset. Spherical/Cylindrical: GRID_PHYSICAL_SIZE. SinhSpherical: GRID_PHYSICAL_SIZE SINHW. SinhCylindrical: GRID_PHYSICAL_SIZE SINHWRHO SINHWZ. SinhCylindricalv2n2: GRID_PHYSICAL_SIZE SINHWRHO SINHWZ RHO_SLOPE Z_SLOPE.""",
    )
    parser.add_argument(
        "--analytical-metric-0",
        type=str,
        required=True,
        help="""Analytic spacetime name used for photon times strictly below t_metric_0.""",
    )
    parser.add_argument(
        "--t-metric-0",
        type=float,
        required=True,
        help="""Lower coordinate-time transition from analytical-metric-0 to the numerical interpolation region.""",
    )
    parser.add_argument(
        "--t-numerical-end",
        type=float,
        required=True,
        help="""Coordinate time of the final stored numerical slice. After this time the numerical spacetime is frozen to that final slice.""",
    )
    parser.add_argument(
        "--dt-spacetime-data",
        type=float,
        required=True,
        help="""Uniform physical coordinate-time spacing of the numerical spacetime data.""",
    )
    parser.add_argument(
        "--time-start",
        type=float,
        default=20.0,
        help="""Initial coordinate time assigned to the photon batch.""",
    )
    parser.add_argument(
        "--eom",
        type=str,
        choices=("geodesic", "normalized"),
        default="geodesic",
        help="""Photon equations of motion: direct affine-parameter geodesics or normalized coordinate-time evolution.""",
    )
    parser.add_argument(
        "--brill-lindquist-bhs",
        nargs=4,
        type=float,
        default=None,
        metavar=("Z_1", "Z_2", "M_1", "M_2"),
        help="""Override the Brill-Lindquist black-hole z positions and masses, e.g. --brill-lindquist-bhs 0.5 -0.5 0.5 0.5.""",
    )
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    args = parser.parse_args()
    normalized_eom = args.eom == "normalized"

    _require(
        os.path.basename(args.bin_name) == args.bin_name,
        "--bin-name must be a filename only, not a path.",
    )
    _require(
        args.bin_name.endswith(".bin"),
        "--bin-name must name a numerical spacetime .bin file.",
    )
    _require(
        args.dt_spacetime_data > 0.0,
        "--dt-spacetime-data must be positive.",
    )
    _require(
        len(args.domain) > 0,
        "--domain requires at least one value.",
    )
    _require(
        args.time_start >= 0.0,
        "--time-start must be nonnegative.",
    )
    _require(
        args.t_metric_0 < args.t_numerical_end,
        "--t-metric-0 must be strictly less than --t-numerical-end.",
    )
    domain = list(args.domain)
    grid_physical_size = None
    sinhw_numerical = None
    sinhw_numerical_rho = None
    sinhw_numerical_z = None
    rho_slope = None
    z_slope = None
    if args.coord_system_numerical in ("Spherical", "Cylindrical"):
        _require(
            len(domain) == 1,
            f"""--coord-system-numerical {args.coord_system_numerical} requires --domain GRID_PHYSICAL_SIZE.""",
        )
        grid_physical_size = domain[0]
    elif args.coord_system_numerical == "SinhSpherical":
        _require(
            len(domain) == 2,
            "--coord-system-numerical SinhSpherical requires --domain GRID_PHYSICAL_SIZE SINHW.",
        )
        grid_physical_size, sinhw_numerical = domain
        _require(sinhw_numerical > 0.0, "SINHW must be positive.")
    elif args.coord_system_numerical == "SinhCylindrical":
        _require(
            len(domain) == 3,
            """--coord-system-numerical SinhCylindrical requires --domain GRID_PHYSICAL_SIZE SINHWRHO SINHWZ.""",
        )
        grid_physical_size, sinhw_numerical_rho, sinhw_numerical_z = domain
        _require(sinhw_numerical_rho > 0.0, "SINHWRHO must be positive.")
        _require(sinhw_numerical_z > 0.0, "SINHWZ must be positive.")
    elif args.coord_system_numerical == "SinhCylindricalv2n2":
        _require(
            len(domain) == 5,
            """--coord-system-numerical SinhCylindricalv2n2 requires --domain GRID_PHYSICAL_SIZE SINHWRHO SINHWZ RHO_SLOPE Z_SLOPE.""",
        )
        (
            grid_physical_size,
            sinhw_numerical_rho,
            sinhw_numerical_z,
            rho_slope,
            z_slope,
        ) = domain
        _require(sinhw_numerical_rho > 0.0, "SINHWRHO must be positive.")
        _require(sinhw_numerical_z > 0.0, "SINHWZ must be positive.")
        _require(rho_slope > 0.0, "RHO_SLOPE must be positive.")
        _require(z_slope > 0.0, "Z_SLOPE must be positive.")
    else:
        raise ValueError(
            f"Unsupported numerical coordinate system: {args.coord_system_numerical}."
        )
    assert grid_physical_size is not None
    _require(grid_physical_size > 0.0, "GRID_PHYSICAL_SIZE must be positive.")
    analytical_metric_0 = args.analytical_metric_0
    analytical_metric_0_is_brill_lindquist = (
        analytical_metric_0 == BRILL_LINDQUIST_CARTESIAN
    )
    use_brill_lindquist_bhs = analytical_metric_0_is_brill_lindquist
    default_BH1_z_posn = None
    default_BH2_z_posn = None
    default_BH1_mass = None
    default_BH2_mass = None
    _require(
        not analytical_metric_0_is_brill_lindquist
        or args.brill_lindquist_bhs is not None,
        f"""--brill-lindquist-bhs is required when --analytical-metric-0 is {BRILL_LINDQUIST_CARTESIAN}.""",
    )
    if args.brill_lindquist_bhs is not None:
        default_BH1_z_posn = args.brill_lindquist_bhs[0]
        default_BH2_z_posn = args.brill_lindquist_bhs[1]
        default_BH1_mass = args.brill_lindquist_bhs[2]
        default_BH2_mass = args.brill_lindquist_bhs[3]
        _require(
            default_BH1_mass > 0.0 and default_BH2_mass > 0.0,
            """--brill-lindquist-bhs masses M_1 and M_2 must be positive.""",
        )
        if not use_brill_lindquist_bhs:
            warnings.warn(
                f"""--brill-lindquist-bhs was provided, but no analytic metric is {BRILL_LINDQUIST_CARTESIAN}. These black-hole inputs will be ignored.""",
                stacklevel=1,
            )
    particle_type = "photon"
    for analytical_metric in [analytical_metric_0]:
        try:
            _ = geo.Geodesic_Equations[f"{analytical_metric}_{particle_type}"]
        except ValueError as exc:
            raise ValueError(
                f"Unsupported analytic spacetime '{analytical_metric}' for {particle_type}."
            ) from exc

    # Step 2: Define strict project constants and simulation targets
    project_name = "photon_batch_geodesic_integrator_numerical"
    exec_name = "photon_batch_geodesic_integrator_numerical"
    project_dir = os.path.abspath(os.path.join(args.outdir, project_name))

    # Step 2.a: Define the target spacetime and particle type.
    SPACETIME = "Numerical"
    integrator_mode = "Numerical"
    PARTICLE = "photon"
    GEO_KEY = f"{SPACETIME}_{PARTICLE}"
    coord_system_numerical = args.coord_system_numerical
    enable_simd = False

    # Step 3: Initialize the project directory and select the infrastructure backend
    print(f"Initializing project: {project_name}")
    shutil.rmtree(project_dir, ignore_errors=True)
    os.makedirs(project_dir, exist_ok=True)

    # Step 3.a: Select the BHaH OpenMP backend for this example.
    par.set_parval_from_str("Infrastructure", "BHaH")
    par.set_parval_from_str("parallelization", "openmp")
    par.set_parval_from_str(
        "CoordSystem_to_register_CodeParameters", coord_system_numerical
    )

    # Step 4: Build the symbolic photon data used by the mixed
    # analytic/numerical interpolation pipeline.
    print(f" -> Assembling symbolic data for {GEO_KEY}...")
    # Step 4.a: Bypass __init__ because these symbolic helper methods build
    # placeholder-based expressions and do not require spacetime-specific state.
    generic_geodesic_equations = geo.GeodesicEquations.__new__(geo.GeodesicEquations)
    coordinate_symbols = list(sp.symbols("t x y z", real=True))
    geodesic_rhs = (
        generic_geodesic_equations.geodesic_eom_rhs_photon_normalized()
        if normalized_eom
        else generic_geodesic_equations.geodesic_eom_rhs_photon()
    )
    p0_photon = generic_geodesic_equations.hamiltonian_constraint_photon()
    normalization_constraint_expr = (
        generic_geodesic_equations.normalization_constraint_photon_normalized()
        if normalized_eom
        else generic_geodesic_equations.normalization_constraint()
    )
    analytical_geodesic_data_0 = geo.Geodesic_Equations[
        f"{analytical_metric_0}_{PARTICLE}"
    ]

    # Step 5: Register C functions in split-pipeline order.
    print(" -> Registering C functions and local CodeParameters...")

    # Step 5.a: Register initialization kernels.
    set_initial_conditions_kernel.set_initial_conditions_kernel(SPACETIME)

    p0_reverse_kernel.p0_reverse_kernel(p0_photon)
    if normalized_eom:
        u_expr, PiD_exprs = (
            geo.GeodesicEquations.photon_momentum_to_normalized_quantities()
        )
        photon_momentum_to_normalized_kernel.photon_momentum_to_normalized_kernel(
            u_expr, PiD_exprs
        )

    # Step 5.b: Register normalization diagnostics.
    if normalized_eom:
        normalization_constraint_photon_normalized.normalization_constraint_photon_normalized(
            normalization_constraint_expr
        )
    else:
        normalization_constraint.normalization_constraint(
            normalization_constraint_expr, PARTICLE
        )

    # Step 5.c: Register the lower analytic spacetime workers used outside the
    # early-time numerical interval and on one reconstructed stencil edge.
    g4DD_metric.g4DD_metric(
        analytical_geodesic_data_0.g4DD, analytical_metric_0, PARTICLE
    )
    # Using metric deritive data
    connections.connections(
        analytical_geodesic_data_0.g4DD_dD, analytical_metric_0, PARTICLE
    )

    # Step 5.d: Register numerical interpolation helpers.
    register_azimuthal_interp = (
        azimuthal_symmetry_spatial_lagrange_interpolation_metric_derivatives.register_CFunction_azimuthal_symmetry_spatial_lagrange_interpolation
    )
    register_azimuthal_interp(
        coord_system_numerical, enable_simd=enable_simd, project_dir=project_dir
    )
    temporal_lagrange_interpolation_metric_derivatives.register_CFunction_temporal_lagrange_interpolation(
        enable_simd=enable_simd, project_dir=project_dir
    )
    temporal_lagrange_interpolation_metric_derivatives_c1_startup.register_CFunction_temporal_lagrange_interpolation_c1_startup(
        enable_simd=enable_simd, project_dir=project_dir
    )
    numerical_interpolation_metric_derivatives.register_CFunction_numerical_interpolation(
        coord_system_numerical,
        enable_simd=enable_simd,
        project_dir=project_dir,
        analytical_metric_0=analytical_metric_0,
    )

    # Step 5.e: Register RKF45 evolution kernels.
    calculate_ode_rhs_kernel.calculate_ode_rhs_kernel(
        geodesic_rhs, coordinate_symbols, normalized_eom=normalized_eom
    )
    rkf45_stage_update.rkf45_stage_update()
    if normalized_eom:
        rkf45_5th_state.rkf45_5th_state()
        rkf45_numerical_control.rkf45_numerical_control(
            normalization_constraint_expr,
            enable_numerical_time_window_step_cap=True,
        )
    else:
        rkf45_finalize_and_control_kernel.rkf45_finalize_and_control_kernel(
            enable_numerical_time_window_step_cap=True
        )

    # Step 5.f: Register event-detection and boundary-intersection kernels.
    find_event_time_and_state.find_event_time_and_state()
    handle_source_plane_intersection.handle_source_plane_intersection()
    handle_window_plane_intersection.handle_window_plane_intersection()
    event_detection_manager_kernel.event_detection_manager_kernel()
    calculate_and_fill_blueprint_data_universal.calculate_and_fill_blueprint_data_universal()

    # Step 5.g: Register project-level orchestration helpers.
    # The numerical interpolation and RKF45 finalization registrations above
    # already pull in the shared slot/time-window helpers on demand. Calling
    # them again here would append duplicate definitions into BHaH_defines.h.
    batch_integrator_numerical.batch_integrator_numerical(
        SPACETIME, coord_system_numerical, normalized_eom=normalized_eom
    )
    main.main(SPACETIME, integrator_mode)

    # Step 5.h: Remove helper registrations emitted only through other kernels.
    # The event manager emits its local event helpers through prefunc. The
    # analytic metric and connection helpers are likewise copied into the
    # numerical interpolation wrapper through prefunc, so keeping standalone
    # registrations would add unused source files and duplicate prototypes.
    internal_funcs_to_remove = [
        "find_event_time_and_state",
        "handle_source_plane_intersection",
        "handle_window_plane_intersection",
        f"g4DD_metric_{analytical_metric_0}",
        f"connections_{analytical_metric_0}",
    ]
    for internal_func in internal_funcs_to_remove:
        cfc.CFunction_dict.pop(internal_func, None)

    # Step 6: Override CodeParameter defaults before parfile generation.
    print(" -> Overriding desired photon CodeParameters before .par generation...")

    # Step 6.a: Set the numerical-spacetime data path.
    # This path intentionally stays under the repo-root raytracing cache.
    # ``--outdir`` controls only the generated photon project location.
    numerical_spacetime_bin_path = os.path.abspath(
        os.path.join(
            "project",
            "raytracing_data",
            args.bin_name,
        )
    )

    par.glb_code_params_dict["numerical_spacetime_bin_path"].defaultvalue = (
        numerical_spacetime_bin_path
    )

    # Step 6.b: Match the dataset reference-metric defaults used by the
    # combined raytracing file before metadata overrides Nxx/dxx/xxmin/xxmax.
    par.adjust_CodeParam_default("grid_physical_size", grid_physical_size)
    rfm = refmetric.reference_metric[coord_system_numerical]
    for param_name, grid_size_mapping in rfm.grid_physical_size_dict.items():
        if grid_size_mapping == "grid_physical_size":
            par.adjust_CodeParam_default(param_name, grid_physical_size)
        elif grid_size_mapping == "-grid_physical_size":
            par.adjust_CodeParam_default(param_name, -grid_physical_size)
        else:
            raise ValueError(
                f"""Unsupported grid_physical_size mapping '{grid_size_mapping}' for {coord_system_numerical}:{param_name}"""
            )
    if coord_system_numerical == "SinhSpherical":
        assert sinhw_numerical is not None
        par.adjust_CodeParam_default("SINHW", sinhw_numerical)
    elif coord_system_numerical == "SinhCylindrical":
        assert sinhw_numerical_rho is not None
        assert sinhw_numerical_z is not None
        par.adjust_CodeParam_default("SINHWRHO", sinhw_numerical_rho)
        par.adjust_CodeParam_default("SINHWZ", sinhw_numerical_z)
    elif coord_system_numerical == "SinhCylindricalv2n2":
        assert sinhw_numerical_rho is not None
        assert sinhw_numerical_z is not None
        assert rho_slope is not None
        assert z_slope is not None
        par.adjust_CodeParam_default("SINHWRHO", sinhw_numerical_rho)
        par.adjust_CodeParam_default("SINHWZ", sinhw_numerical_z)
        par.adjust_CodeParam_default("rho_slope", rho_slope)
        par.adjust_CodeParam_default("z_slope", z_slope)

    # Step 6.c: Set interpolation-order defaults.
    par.glb_code_params_dict[
        "numerical_spacetime_spatial_interp_order"
    ].defaultvalue = 3
    par.glb_code_params_dict[
        "numerical_spacetime_temporal_interp_order"
    ].defaultvalue = 3

    # Step 6.d: Set initial-condition defaults.
    par.glb_code_params_dict["t_start"].defaultvalue = 28.0  # args.time_start
    par.glb_code_params_dict["scan_density"].defaultvalue = 100

    # Step 6.e: Set batch-integrator and numerical-limit defaults.
    par.glb_code_params_dict["p_t_max"].defaultvalue = 3.0 if normalized_eom else 1000.0
    par.glb_code_params_dict["perform_normalization_check"].defaultvalue = True
    par.glb_code_params_dict["r_escape"].defaultvalue = 25.0

    # Step 6.f: Set the lower analytic / numerical transition defaults.
    par.glb_code_params_dict["t_metric_0"].defaultvalue = args.t_metric_0
    par.glb_code_params_dict["t_numerical_end"].defaultvalue = args.t_numerical_end
    par.glb_code_params_dict["dt_numerical_spacetime_data"].defaultvalue = (
        args.dt_spacetime_data
    )
    # Keep sparse retained-slice debugging disabled for normal runs.
    par.glb_code_params_dict["numerical_spacetime_time_slice_stride"].defaultvalue = 1

    # Step 6.f.i: Set Brill-Lindquist black-hole defaults only when requested.
    if use_brill_lindquist_bhs:
        assert args.brill_lindquist_bhs is not None
        assert default_BH1_z_posn is not None
        assert default_BH2_z_posn is not None
        assert default_BH1_mass is not None
        assert default_BH2_mass is not None
        par.adjust_CodeParam_default("BH1_mass", default_BH1_mass)
        par.adjust_CodeParam_default("BH2_mass", default_BH2_mass)
        par.adjust_CodeParam_default("BH1_posn_z", default_BH1_z_posn)
        par.adjust_CodeParam_default("BH2_posn_z", default_BH2_z_posn)

    # Step 6.g: Cap coordinate-time growth per accepted RKF45 step.
    par.glb_code_params_dict["rkf45_max_delta_t"].defaultvalue = 0.5

    # Step 6.h: Set time-window manager defaults.
    par.glb_code_params_dict["slot_manager_delta_t"].defaultvalue = 5.0
    par.glb_code_params_dict["slot_manager_t_min"].defaultvalue = -150.0

    # Step 6.i: Set source-plane geometry defaults.
    par.glb_code_params_dict["source_plane_center_x"].defaultvalue = -40.0
    par.glb_code_params_dict["source_plane_center_y"].defaultvalue = 0.0
    par.glb_code_params_dict["source_plane_center_z"].defaultvalue = 0.0

    par.glb_code_params_dict["source_plane_normal_x"].defaultvalue = 1.0
    par.glb_code_params_dict["source_plane_normal_y"].defaultvalue = 0.0
    par.glb_code_params_dict["source_plane_normal_z"].defaultvalue = 0.0

    par.glb_code_params_dict["source_r_max"].defaultvalue = 100.0
    par.glb_code_params_dict["source_r_min"].defaultvalue = 0.0

    par.glb_code_params_dict["source_up_vec_x"].defaultvalue = 0.0
    par.glb_code_params_dict["source_up_vec_y"].defaultvalue = 0.0
    par.glb_code_params_dict["source_up_vec_z"].defaultvalue = 1.0

    # Step 6.j: Set camera window geometry defaults.
    par.glb_code_params_dict["camera_pos_x"].defaultvalue = 10.0
    par.glb_code_params_dict["camera_pos_y"].defaultvalue = 0.0
    par.glb_code_params_dict["camera_pos_z"].defaultvalue = 0.0

    par.glb_code_params_dict["original_window_center_x"].defaultvalue = 9.5
    par.glb_code_params_dict["original_window_center_y"].defaultvalue = 0.0
    par.glb_code_params_dict["original_window_center_z"].defaultvalue = 0.0

    par.glb_code_params_dict["window_height"].defaultvalue = 1.0
    par.glb_code_params_dict["window_width"].defaultvalue = 1.0

    par.glb_code_params_dict["window_up_vec_x"].defaultvalue = 0.0
    par.glb_code_params_dict["window_up_vec_y"].defaultvalue = 0.0
    par.glb_code_params_dict["window_up_vec_z"].defaultvalue = 1.0

    # Step 6.k: Set the fixed CPU tiling defaults.
    par.glb_code_params_dict["window_tiles_width"].defaultvalue = 1
    par.glb_code_params_dict["window_tiles_height"].defaultvalue = 1

    # Step 6.l: Set RKF45 controller defaults.
    par.glb_code_params_dict["numerical_initial_h"].defaultvalue = (
        -0.05 if normalized_eom else 0.05
    )
    par.glb_code_params_dict["rkf45_absolute_error_tolerance"].defaultvalue = 1.0e-8
    par.glb_code_params_dict["rkf45_error_tolerance"].defaultvalue = 1.0e-8
    par.glb_code_params_dict["rkf45_h_max"].defaultvalue = 10.0
    par.glb_code_params_dict["rkf45_h_min"].defaultvalue = 1.0e-4
    if normalized_eom:
        par.glb_code_params_dict["rkf45_constraint_tolerance"].defaultvalue = 1.0e0
        par.glb_code_params_dict["rkf45_log_energy_tolerance"].defaultvalue = 1.0e0

    print(f" -> Numerical spacetime .bin path: {numerical_spacetime_bin_path}")
    print(f" -> Numerical coordinate system: {coord_system_numerical}")
    print(f" -> Photon equations of motion: {args.eom}")
    print(f" -> Numerical domain: {domain}")
    if sinhw_numerical is not None:
        print(f" -> Numerical SINHW: {sinhw_numerical}")
    if sinhw_numerical_rho is not None:
        print(f" -> Numerical SINHWRHO: {sinhw_numerical_rho}")
    if sinhw_numerical_z is not None:
        print(f" -> Numerical SINHWZ: {sinhw_numerical_z}")
    if rho_slope is not None:
        print(f" -> Numerical rho_slope: {rho_slope}")
    if z_slope is not None:
        print(f" -> Numerical z_slope: {z_slope}")
    print(f" -> Analytic metric 0: {analytical_metric_0}")
    if use_brill_lindquist_bhs:
        print(
            " -> Brill-Lindquist BHs: "
            f"z1={default_BH1_z_posn}, z2={default_BH2_z_posn}, "
            f"M1={default_BH1_mass}, M2={default_BH2_mass}"
        )
    print(f" -> time_start: {args.time_start}")
    print(f" -> t_metric_0: {args.t_metric_0}")
    print(f" -> t_numerical_end: {args.t_numerical_end}")
    print(f" -> dt_spacetime_data: {args.dt_spacetime_data}")

    # Step 6.m: Generate C code for parameter handling.
    print(" -> Generating parameter handling code...")
    CPs.write_CodeParameters_h_files(project_dir=project_dir, set_commondata_only=True)
    CPs.register_CFunctions_params_commondata_struct_set_to_default()
    cmdline_input_and_parfiles.generate_default_parfile(
        project_dir=project_dir, project_name=project_name
    )
    cmdline_input_and_parfiles.register_CFunction_cmdline_input_and_parfile_parser(
        project_name=project_name,
        cmdline_inputs=[
            "source_r_min",
            "source_r_max",
            "window_width",
            "window_height",
            "window_tiles_width",
            "window_tiles_height",
            "scan_density",
        ],
    )

    # Step 7: Assemble the generated C project.
    print(" -> Assembling C project on disk...")

    # Step 7.a: Map the shared CUDA-style helpers onto OpenMP.
    cpu_macros = {
        "ReadCUDA(ptr)": "#define ReadCUDA(ptr) (*(ptr))\n",
        "WriteCUDA(ptr, val)": "#define WriteCUDA(ptr, val) (*(ptr) = (val))\n",
        "BHAH_MALLOC_DEVICE(a, sz)": (
            "#define BHAH_MALLOC_DEVICE(a, sz) BHAH_MALLOC(a, sz)\n"
        ),
        "BHAH_FREE_DEVICE(a)": "#define BHAH_FREE_DEVICE(a) BHAH_FREE(a)\n",
        "MulCUDA(a, b)": "#define MulCUDA(a, b) ((a) * (b))\n",
        "DivCUDA(a, b)": "#define DivCUDA(a, b) ((a) / (b))\n",
        "AddCUDA(a, b)": "#define AddCUDA(a, b) ((a) + (b))\n",
        "FusedMulAddCUDA(a, b, c)": (
            "#define FusedMulAddCUDA(a, b, c) ((a) * (b) + (c))\n"
        ),
        "AbsCUDA(val)": "#define AbsCUDA(val) fabs(val)\n",
        "SqrtCUDA(val)": "#define SqrtCUDA(val) sqrt(val)\n",
        "PowCUDA(a, b)": "#define PowCUDA(a, b) pow(a, b)\n",
        "BHAH_HD_FUNC": "#define BHAH_HD_FUNC\n",
        "BHAH_HD_INLINE": "#define BHAH_HD_INLINE static inline\n",
        "BHAH_WARP_ATOMIC_ADD(ptr, val)": (
            "#define BHAH_WARP_ATOMIC_ADD(ptr, val) "
            '_Pragma("omp atomic") *(ptr) += (val)\n'
        ),
        "GLOBAL_COMMONDATA_EXTERN": (
            "// CPU passes commondata by reference, no global needed.\n"
        ),
        "BHAH_DEVICE_SYNC()": "#define BHAH_DEVICE_SYNC() do {} while(0)\n",
    }

    # Step 7.b: Match the combined raytracing payload layout, which uses
    # NGHOSTS = 3.
    BHaH_defines_h.output_BHaH_defines_h(
        project_dir=project_dir,
        enable_rfm_precompute=False,
        fin_NGHOSTS_add_one_for_upwinding_or_KO=True,
        supplemental_defines_dict=cpu_macros,
    )

    compiler = "gcc"
    cflags = [
        "-fopenmp",
        "-O3",
        "-fno-omit-frame-pointer",
        "-DDEBUG",
        "-Wno-stringop-truncation",
    ]
    libs = ["-lm"]
    ext = "c"

    print(" -> Generating Makefile")

    # Step 7.c: Select the Makefile optimization profile.
    opt_option = "fast"

    Makefile.output_CFunctions_function_prototypes_and_construct_Makefile(
        project_dir=project_dir,
        project_name=project_name,
        exec_or_library_name=exec_name,
        compiler_opt_option=opt_option,
        addl_CFLAGS=cflags,
        addl_libraries=libs,
        CC=compiler,
        src_code_file_ext=ext,
    )
    # Step 8: Copy helper scripts and print usage instructions.
    vis_dir = os.path.join("nrpy", "examples", "geodesic_visualizations")
    vis_script_src = os.path.join(vis_dir, "visualize_lensed_image.py")
    config_src = os.path.join(vis_dir, "blueprint_config_and_schema.py")
    render_src = os.path.join(vis_dir, "render_lensed_image.py")
    blueprint_analysis_src = os.path.join(vis_dir, "blueprint_analysis.py")

    for script_src in (
        vis_script_src,
        config_src,
        render_src,
        blueprint_analysis_src,
    ):
        shutil.copy(script_src, project_dir)

    # Step 8.a: Build helper commands from CodeParameter defaults.
    c_r_min = float(par.glb_code_params_dict["source_r_min"].defaultvalue)
    c_r_max = float(par.glb_code_params_dict["source_r_max"].defaultvalue)
    c_window_width = float(par.glb_code_params_dict["window_width"].defaultvalue)
    c_window_height = float(par.glb_code_params_dict["window_height"].defaultvalue)
    c_tiles_width = int(par.glb_code_params_dict["window_tiles_width"].defaultvalue)
    c_tiles_height = int(par.glb_code_params_dict["window_tiles_height"].defaultvalue)
    c_pixel_width = 450
    data_request_file = "numerical_spacetime_data_request.json"
    data_prep_command = f"python3 combined_raytracing_bin_helper.py {data_request_file}"
    parfile_path = os.path.join(project_dir, f"{project_name}.par")

    vis_command = " ".join(
        [
            "python3 visualize_lensed_image.py",
            f"--source_r_min {c_r_min}",
            f"--source_r_max {c_r_max}",
            f"--window_width {c_window_width}",
            f"--window_height {c_window_height}",
            f"--window_tiles_width {c_tiles_width}",
            f"--window_tiles_height {c_tiles_height}",
            f"--pixel_width {c_pixel_width}",
        ]
    )

    print(f"Finished! Now go into {project_dir}.")
    print(f"    Parameter file can be found at {parfile_path}\n")
    print("    To prepare the required numerical spacetime data, run:")
    print(f"    {data_prep_command}\n")
    print("    Then build and run the photon executable:")
    print("    make")
    print(f"    ./{exec_name}\n")
    print(
        """    To generate the lensed image after running the C executable, ensure you have the required Python packages:"""
    )
    print("    pip install matplotlib numpy numba Pillow\n")
    print(
        "    Then, execute the visualization script directly from the project directory:"
    )
    print(f"    {vis_command}\n")
    print("    To use your own celestial sphere image, add:")
    print("    --sphere_image /path/to/celestial_sphere.png")
    print("    To use your own source image, add:")
    print("    --source_image /path/to/source_image.png\n")

    blueprint_command = " ".join(
        [
            "python3 blueprint_analysis.py",
            f"--window_tiles_width {c_tiles_width}",
            f"--window_tiles_height {c_tiles_height}",
            f"--window_width {c_window_width}",
            f"--window_height {c_window_height}",
        ]
    )

    print("    To run the blueprint diagnostic:")
    print(f"    {blueprint_command}\n")
