const REAL NOSIMDAMPL = params->AMPL;                                          // nrpy.reference_metric::AMPL
MAYBE_UNUSED const REAL_SIMD_ARRAY AMPL = ConstSIMD(NOSIMDAMPL);               // nrpy.reference_metric::AMPL
const REAL NOSIMDbare_mass_0 = commondata->bare_mass_0;                        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::bare_mass_0
MAYBE_UNUSED const REAL_SIMD_ARRAY bare_mass_0 = ConstSIMD(NOSIMDbare_mass_0); // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::bare_mass_0
const REAL NOSIMDbare_mass_1 = commondata->bare_mass_1;                        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::bare_mass_1
MAYBE_UNUSED const REAL_SIMD_ARRAY bare_mass_1 = ConstSIMD(NOSIMDbare_mass_1); // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::bare_mass_1
const REAL NOSIMDCart_originx = params->Cart_originx;                          // nrpy.grid::Cart_originx
MAYBE_UNUSED const REAL_SIMD_ARRAY Cart_originx = ConstSIMD(NOSIMDCart_originx); // nrpy.grid::Cart_originx
const REAL NOSIMDCart_originy = params->Cart_originy;                            // nrpy.grid::Cart_originy
MAYBE_UNUSED const REAL_SIMD_ARRAY Cart_originy = ConstSIMD(NOSIMDCart_originy); // nrpy.grid::Cart_originy
const REAL NOSIMDCart_originz = params->Cart_originz;                            // nrpy.grid::Cart_originz
MAYBE_UNUSED const REAL_SIMD_ARRAY Cart_originz = ConstSIMD(NOSIMDCart_originz); // nrpy.grid::Cart_originz
const REAL NOSIMDCFL_FACTOR = commondata->CFL_FACTOR;                            // nrpy.infrastructures.superB.MoL::CFL_FACTOR
MAYBE_UNUSED const REAL_SIMD_ARRAY CFL_FACTOR = ConstSIMD(NOSIMDCFL_FACTOR);     // nrpy.infrastructures.superB.MoL::CFL_FACTOR
const REAL NOSIMDconvergence_factor = commondata->convergence_factor; // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::convergence_factor
MAYBE_UNUSED const REAL_SIMD_ARRAY convergence_factor =
    ConstSIMD(NOSIMDconvergence_factor);                            // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::convergence_factor
MAYBE_UNUSED const int CoordSystem_hash = params->CoordSystem_hash; // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::CoordSystem_hash
const REAL NOSIMDdiagnostics_output_every =
    commondata->diagnostics_output_every; // nrpy.infrastructures.BHaH.diagnostics.diagnostics::diagnostics_output_every
MAYBE_UNUSED const REAL_SIMD_ARRAY diagnostics_output_every =
    ConstSIMD(NOSIMDdiagnostics_output_every);                   // nrpy.infrastructures.BHaH.diagnostics.diagnostics::diagnostics_output_every
const REAL NOSIMDdt = commondata->dt;                            // nrpy.infrastructures.superB.MoL::dt
MAYBE_UNUSED const REAL_SIMD_ARRAY dt = ConstSIMD(NOSIMDdt);     // nrpy.infrastructures.superB.MoL::dt
const REAL NOSIMDdxx0 = params->dxx0;                            // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx0
MAYBE_UNUSED const REAL_SIMD_ARRAY dxx0 = ConstSIMD(NOSIMDdxx0); // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx0
const REAL NOSIMDdxx1 = params->dxx1;                            // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx1
MAYBE_UNUSED const REAL_SIMD_ARRAY dxx1 = ConstSIMD(NOSIMDdxx1); // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx1
const REAL NOSIMDdxx2 = params->dxx2;                            // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx2
MAYBE_UNUSED const REAL_SIMD_ARRAY dxx2 = ConstSIMD(NOSIMDdxx2); // nrpy.infrastructures.BHaH.diagnostics.sqrt_detgammahat_d3xx_volume_element::dxx2
const REAL NOSIMDeta_damping = commondata->eta_damping;          // nrpy.equations.nrpyelliptic.ConformallyFlat_RHSs::eta_damping
MAYBE_UNUSED const REAL_SIMD_ARRAY eta_damping = ConstSIMD(NOSIMDeta_damping); // nrpy.equations.nrpyelliptic.ConformallyFlat_RHSs::eta_damping
const REAL NOSIMDgrid_hole_radius = params->grid_hole_radius;                  // nrpy.reference_metric::grid_hole_radius
MAYBE_UNUSED const REAL_SIMD_ARRAY grid_hole_radius = ConstSIMD(NOSIMDgrid_hole_radius); // nrpy.reference_metric::grid_hole_radius
MAYBE_UNUSED const int grid_idx = params->grid_idx;               // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::grid_idx
const REAL NOSIMDgrid_physical_size = params->grid_physical_size; // nrpy.reference_metric::grid_physical_size
MAYBE_UNUSED const REAL_SIMD_ARRAY grid_physical_size = ConstSIMD(NOSIMDgrid_physical_size); // nrpy.reference_metric::grid_physical_size
MAYBE_UNUSED const bool grid_rotates = params->grid_rotates;                                 // nrpy.grid::grid_rotates
const REAL NOSIMDinvdxx0 = params->invdxx0;                            // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx0
MAYBE_UNUSED const REAL_SIMD_ARRAY invdxx0 = ConstSIMD(NOSIMDinvdxx0); // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx0
const REAL NOSIMDinvdxx1 = params->invdxx1;                            // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx1
MAYBE_UNUSED const REAL_SIMD_ARRAY invdxx1 = ConstSIMD(NOSIMDinvdxx1); // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx1
const REAL NOSIMDinvdxx2 = params->invdxx2;                            // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx2
MAYBE_UNUSED const REAL_SIMD_ARRAY invdxx2 = ConstSIMD(NOSIMDinvdxx2); // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::invdxx2
const REAL NOSIMDlog10_current_residual =
    commondata->log10_current_residual; // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::log10_current_residual
MAYBE_UNUSED const REAL_SIMD_ARRAY log10_current_residual =
    ConstSIMD(NOSIMDlog10_current_residual); // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::log10_current_residual
const REAL NOSIMDlog10_residual_tolerance =
    commondata->log10_residual_tolerance; // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::log10_residual_tolerance
MAYBE_UNUSED const REAL_SIMD_ARRAY log10_residual_tolerance =
    ConstSIMD(NOSIMDlog10_residual_tolerance); // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::log10_residual_tolerance
const REAL NOSIMDMINIMUM_GLOBAL_WAVESPEED =
    commondata->MINIMUM_GLOBAL_WAVESPEED; // nrpy.infrastructures.BHaH.nrpyelliptic.auxevol_gfs_set_to_constant::MINIMUM_GLOBAL_WAVESPEED
MAYBE_UNUSED const REAL_SIMD_ARRAY MINIMUM_GLOBAL_WAVESPEED =
    ConstSIMD(NOSIMDMINIMUM_GLOBAL_WAVESPEED);        // nrpy.infrastructures.BHaH.nrpyelliptic.auxevol_gfs_set_to_constant::MINIMUM_GLOBAL_WAVESPEED
MAYBE_UNUSED const int Nchare0 = commondata->Nchare0; // nrpy.infrastructures.superB.main_chare::Nchare0
MAYBE_UNUSED const int Nchare1 = commondata->Nchare1; // nrpy.infrastructures.superB.main_chare::Nchare1
MAYBE_UNUSED const int Nchare2 = commondata->Nchare2; // nrpy.infrastructures.superB.main_chare::Nchare2
MAYBE_UNUSED const int nn = commondata->nn;           // nrpy.infrastructures.superB.MoL::nn
MAYBE_UNUSED const int nn_0 = commondata->nn_0;       // nrpy.infrastructures.superB.MoL::nn_0
MAYBE_UNUSED const int nn_max = commondata->nn_max;   // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::nn_max
MAYBE_UNUSED const int NUMGRIDS = commondata->NUMGRIDS;                 // nrpy.grid::NUMGRIDS
MAYBE_UNUSED const int Nxx0 = params->Nxx0;                             // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx0
MAYBE_UNUSED const int Nxx1 = params->Nxx1;                             // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx1
MAYBE_UNUSED const int Nxx2 = params->Nxx2;                             // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx2
MAYBE_UNUSED const int Nxx_plus_2NGHOSTS0 = params->Nxx_plus_2NGHOSTS0; // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx_plus_2NGHOSTS0
MAYBE_UNUSED const int Nxx_plus_2NGHOSTS1 = params->Nxx_plus_2NGHOSTS1; // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx_plus_2NGHOSTS1
MAYBE_UNUSED const int Nxx_plus_2NGHOSTS2 = params->Nxx_plus_2NGHOSTS2; // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::Nxx_plus_2NGHOSTS2
const REAL NOSIMDP0_x = commondata->P0_x;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_x
MAYBE_UNUSED const REAL_SIMD_ARRAY P0_x = ConstSIMD(NOSIMDP0_x);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_x
const REAL NOSIMDP0_y = commondata->P0_y;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_y
MAYBE_UNUSED const REAL_SIMD_ARRAY P0_y = ConstSIMD(NOSIMDP0_y);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_y
const REAL NOSIMDP0_z = commondata->P0_z;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_z
MAYBE_UNUSED const REAL_SIMD_ARRAY P0_z = ConstSIMD(NOSIMDP0_z);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P0_z
const REAL NOSIMDP1_x = commondata->P1_x;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_x
MAYBE_UNUSED const REAL_SIMD_ARRAY P1_x = ConstSIMD(NOSIMDP1_x);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_x
const REAL NOSIMDP1_y = commondata->P1_y;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_y
MAYBE_UNUSED const REAL_SIMD_ARRAY P1_y = ConstSIMD(NOSIMDP1_y);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_y
const REAL NOSIMDP1_z = commondata->P1_z;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_z
MAYBE_UNUSED const REAL_SIMD_ARRAY P1_z = ConstSIMD(NOSIMDP1_z);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::P1_z
const REAL NOSIMDPI = params->PI;                                       // nrpy.reference_metric::PI
MAYBE_UNUSED const REAL_SIMD_ARRAY PI = ConstSIMD(NOSIMDPI);            // nrpy.reference_metric::PI
const REAL NOSIMDS0_x = commondata->S0_x;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_x
MAYBE_UNUSED const REAL_SIMD_ARRAY S0_x = ConstSIMD(NOSIMDS0_x);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_x
const REAL NOSIMDS0_y = commondata->S0_y;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_y
MAYBE_UNUSED const REAL_SIMD_ARRAY S0_y = ConstSIMD(NOSIMDS0_y);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_y
const REAL NOSIMDS0_z = commondata->S0_z;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_z
MAYBE_UNUSED const REAL_SIMD_ARRAY S0_z = ConstSIMD(NOSIMDS0_z);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S0_z
const REAL NOSIMDS1_x = commondata->S1_x;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_x
MAYBE_UNUSED const REAL_SIMD_ARRAY S1_x = ConstSIMD(NOSIMDS1_x);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_x
const REAL NOSIMDS1_y = commondata->S1_y;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_y
MAYBE_UNUSED const REAL_SIMD_ARRAY S1_y = ConstSIMD(NOSIMDS1_y);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_y
const REAL NOSIMDS1_z = commondata->S1_z;                               // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_z
MAYBE_UNUSED const REAL_SIMD_ARRAY S1_z = ConstSIMD(NOSIMDS1_z);        // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::S1_z
const REAL NOSIMDSINHW = params->SINHW;                                 // nrpy.reference_metric::SINHW
MAYBE_UNUSED const REAL_SIMD_ARRAY SINHW = ConstSIMD(NOSIMDSINHW);      // nrpy.reference_metric::SINHW
MAYBE_UNUSED const bool stop_relaxation =
    commondata->stop_relaxation;                               // nrpy.infrastructures.BHaH.nrpyelliptic.stop_conditions_check::stop_relaxation
const REAL NOSIMDt_0 = commondata->t_0;                        // nrpy.infrastructures.superB.MoL::t_0
MAYBE_UNUSED const REAL_SIMD_ARRAY t_0 = ConstSIMD(NOSIMDt_0); // nrpy.infrastructures.superB.MoL::t_0
const REAL NOSIMDt_final = commondata->t_final;                // nrpy.infrastructures.superB.MoL::t_final
MAYBE_UNUSED const REAL_SIMD_ARRAY t_final = ConstSIMD(NOSIMDt_final); // nrpy.infrastructures.superB.MoL::t_final
const REAL NOSIMDtime = commondata->time;                              // nrpy.infrastructures.superB.MoL::time
MAYBE_UNUSED const REAL_SIMD_ARRAY time = ConstSIMD(NOSIMDtime);       // nrpy.infrastructures.superB.MoL::time
const REAL NOSIMDxxmax0 = params->xxmax0;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax0
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmax0 = ConstSIMD(NOSIMDxxmax0);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax0
const REAL NOSIMDxxmax1 = params->xxmax1;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax1
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmax1 = ConstSIMD(NOSIMDxxmax1);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax1
const REAL NOSIMDxxmax2 = params->xxmax2;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax2
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmax2 = ConstSIMD(NOSIMDxxmax2);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmax2
const REAL NOSIMDxxmin0 = params->xxmin0;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin0
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmin0 = ConstSIMD(NOSIMDxxmin0);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin0
const REAL NOSIMDxxmin1 = params->xxmin1;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin1
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmin1 = ConstSIMD(NOSIMDxxmin1);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin1
const REAL NOSIMDxxmin2 = params->xxmin2;                              // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin2
MAYBE_UNUSED const REAL_SIMD_ARRAY xxmin2 = ConstSIMD(NOSIMDxxmin2);   // nrpy.infrastructures.BHaH.numerical_grids_and_timestep::xxmin2
const REAL NOSIMDzPunc = commondata->zPunc;                            // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::zPunc
MAYBE_UNUSED const REAL_SIMD_ARRAY zPunc = ConstSIMD(NOSIMDzPunc);     // nrpy.equations.nrpyelliptic.ConformallyFlat_SourceTerms::zPunc
