"""
Emit checkpoint/restart support owned by a generated Dendro application.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from typing import List, cast

import nrpy.grid as gri
import nrpy.params as par
from nrpy.infrastructures.Dendro import CodeParameters, state_h


def output_checkpoint_cpp(
    solver_stem: str,
    solver_namespace: str,
    formulation_name: str,
    *,
    enable_fCCZ4: bool = False,
) -> str:
    """
    Emit ``checkpoint.cpp`` with a checked, formulation-specific restart.

    The metadata records the exact evolved-field layout, all emitted
    parameters, iteration, physical time, time step, and the algebraic
    residual of the already-projected state.  Restore rejects incompatible
    metadata and loads the stored state without projection or Lambda changes.

    :param solver_stem: Lowercase formulation stem used by generated headers.
    :param solver_namespace: Generated application namespace.
    :param formulation_name: Stable checkpoint formulation identifier.
    :param enable_fCCZ4: Select the canonical fCCZ4 state layout when true.
    :return: Complete generated ``checkpoint.cpp`` text.
    """
    state_h.validate_registered_state(enable_fCCZ4)
    evolved_names = []
    for name in state_h.evolved_gridfunctions(enable_fCCZ4):
        gridfunction = cast(gri.DendroGridFunction, gri.glb_gridfcs_dict[name])
        evolved_names.append(gridfunction.dendro_name)

    parameter_names = CodeParameters.emitted_parameter_names()
    parameter_write_lines: List[str] = []
    parameter_check_lines: List[str] = []
    for name in parameter_names:
        code_parameter = par.glb_code_params_dict[name]
        base_type, size, is_array = par.parse_cparam_type(code_parameter.cparam_type)
        if is_array and base_type == "char":
            parameter_write_lines.append(
                f'    metadata["NRPY_PARAMETERS"]["{name}"] = '
                f"std::string(params.{name});"
            )
            parameter_check_lines.extend(
                [
                    f'        const std::string stored_{name} = parameters.at("{name}").get<std::string>();',
                    f"        if (stored_{name} != std::string(params.{name})) metadata_valid = false;",
                ]
            )
        elif is_array:
            cpp_type = CodeParameters.c_type(code_parameter.cparam_type)
            parameter_write_lines.append(
                f'    metadata["NRPY_PARAMETERS"]["{name}"] = '
                f"std::vector<{cpp_type}>(params.{name}, params.{name} + {size});"
            )
            parameter_check_lines.extend(
                [
                    f'        const auto stored_{name} = parameters.at("{name}").get<std::vector<{cpp_type}>>();',
                    f"        if (stored_{name}.size() != {size}) metadata_valid = false;",
                    f"        for (std::size_t i = 0; metadata_valid && i < {size}; ++i) {{",
                    f"            if (stored_{name}[i] != params.{name}[i]) metadata_valid = false;",
                    "        }  // END LOOP: for i over array entries",
                ]
            )
        else:
            cpp_type = CodeParameters.c_type(code_parameter.cparam_type)
            parameter_write_lines.append(
                f'    metadata["NRPY_PARAMETERS"]["{name}"] = params.{name};'
            )
            parameter_check_lines.append(
                f'        if (parameters.at("{name}").get<{cpp_type}>() != '
                f"params.{name}) metadata_valid = false;"
            )

    field_literals = ",\n".join(f'        "{name}"' for name in evolved_names)
    parameter_literals = ",\n".join(f'        "{name}"' for name in parameter_names)
    parameter_writes = "\n".join(parameter_write_lines)
    parameter_checks = "\n".join(parameter_check_lines)
    namespace_alias = f"namespace generated = {solver_namespace}::generated;"

    return f"""// GENERATED FILE - DO NOT EDIT
// AUTOMATICALLY GENERATED BY NRPy

#include "{solver_stem}_defines.h"

#include <mpi.h>

#include <array>
#include <cmath>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "checkPoint.h"
#include "dvec.h"
#include "parUtils.h"

{namespace_alias}
namespace {solver_namespace} {{

int {solver_stem}_write_checkpoint(
    const std::string& prefix,
    unsigned checkpoint_index,
    ot::Mesh* mesh,
    ot::DVector<DendroScalar, unsigned int>& state,
    const generated::params_struct& params,
    unsigned iteration,
    DendroScalar time,
    DendroScalar time_step,
    const Point& domain_minimum,
    const Point& domain_maximum,
    const std::array<Point, 2>& excision_centers,
    const std::vector<DendroScalar>& black_hole_time_history,
    const std::vector<std::array<DendroScalar, 6>>&
        black_hole_position_history,
    DendroScalar black_hole_merge_time,
    bool merged_checkpoint_written,
    DendroScalar projected_algebraic_residual) {{
    if (!mesh->isActive()) return 0;

    const unsigned rank = mesh->getMPIRank();
    int local_status =
        std::isfinite(projected_algebraic_residual) &&
                std::abs(projected_algebraic_residual) <= 1.0e-10
            ? 0
            : 1;
    std::ostringstream octree_name;
    octree_name << prefix << "_" << checkpoint_index << "_octree_" << rank
                << ".oct";
    const std::string temporary_octree_name = octree_name.str() + ".tmp";
    const ot::TreeNode* local_elements =
        &*(mesh->getAllElements().begin() + mesh->getElementLocalBegin());
    if (local_status == 0 &&
        io::checkpoint::writeOctToFile(
            temporary_octree_name.c_str(), local_elements,
            mesh->getNumLocalMeshElements()) != 0)
        local_status = 1;

    std::array<DendroScalar*, generated::NUM_EVOL_GFS> variables{{}};
    state.to_2d(variables.data());
    std::array<const DendroScalar*, generated::NUM_EVOL_GFS>
        checkpoint_variables{{}};
    for (unsigned i = 0; i < generated::NUM_EVOL_GFS; ++i) {{
        checkpoint_variables[i] = variables[i];
    }}  // END LOOP: for i over evolved gridfunctions
    std::ostringstream state_name;
    state_name << prefix << "_" << checkpoint_index << "_" << rank << ".var";
    const std::string temporary_state_name = state_name.str() + ".tmp";
    if (local_status == 0 &&
        io::checkpoint::writeVecToFile(
            temporary_state_name.c_str(), mesh,
            checkpoint_variables.data(),
            generated::NUM_EVOL_GFS) != 0)
        local_status = 1;

    int global_status = 0;
    MPI_Allreduce(&local_status, &global_status, 1, MPI_INT, MPI_MAX,
                  mesh->getMPICommunicator());
    if (global_status != 0) {{
        std::filesystem::remove(temporary_octree_name);
        std::filesystem::remove(temporary_state_name);
        return 1;
    }}  // END IF: temporary checkpoint write failed

    std::ostringstream metadata_name;
    metadata_name << prefix << "_" << checkpoint_index << "_step.cp";
    if (rank == 0) {{
        std::error_code remove_error;
        std::filesystem::remove(metadata_name.str(), remove_error);
        if (remove_error) global_status = 1;
    }}  // END IF: rank 0 removes old metadata
    MPI_Bcast(&global_status, 1, MPI_INT, 0, mesh->getMPICommunicator());
    if (global_status == 0) {{
        try {{
            std::filesystem::rename(temporary_octree_name, octree_name.str());
            std::filesystem::rename(temporary_state_name, state_name.str());
        }}  // END TRY: rename checkpoint files
        catch (const std::filesystem::filesystem_error&) {{
            local_status = 1;
        }}  // END CATCH: checkpoint rename failure
    }}  // END IF: old metadata removed
    else {{
        local_status = 1;
    }}  // END ELSE: old metadata removal failed
    MPI_Allreduce(&local_status, &global_status, 1, MPI_INT, MPI_MAX,
                  mesh->getMPICommunicator());
    if (global_status != 0) {{
        std::filesystem::remove(temporary_octree_name);
        std::filesystem::remove(temporary_state_name);
        return 1;
    }}  // END IF: checkpoint file rename failed

    json metadata;
    metadata["NRPY_FORMULATION"] = "{formulation_name}";
    metadata["NRPY_FIELD_COUNT"] = generated::NUM_EVOL_GFS;
    metadata["NRPY_FIELD_NAMES"] = std::vector<std::string>{{
{field_literals}
    }};
    metadata["NRPY_ITERATION"] = iteration;
    metadata["NRPY_TIME"] = time;
    metadata["NRPY_TIME_STEP"] = time_step;
    metadata["NRPY_ELEMENT_ORDER"] = mesh->getElementOrder();
    metadata["NRPY_ACTIVE_COMM_SIZE"] = mesh->getMPICommSize();
    metadata["NRPY_DOMAIN_MINIMUM"] = std::array<DendroScalar, 3>{{
        domain_minimum.x(), domain_minimum.y(), domain_minimum.z()}};
    metadata["NRPY_DOMAIN_MAXIMUM"] = std::array<DendroScalar, 3>{{
        domain_maximum.x(), domain_maximum.y(), domain_maximum.z()}};
    metadata["NRPY_EXCISION_CENTERS"] = std::array<DendroScalar, 6>{{
        excision_centers[0].x(), excision_centers[0].y(),
        excision_centers[0].z(), excision_centers[1].x(),
        excision_centers[1].y(), excision_centers[1].z()}};
    metadata["NRPY_BH_HISTORY_TIMES"] = black_hole_time_history;
    metadata["NRPY_BH_HISTORY_POSITIONS"] = black_hole_position_history;
    metadata["NRPY_BH_MERGE_TIME"] = black_hole_merge_time;
    metadata["NRPY_MERGED_CHECKPOINT_WRITTEN"] = merged_checkpoint_written;
    metadata["NRPY_PROJECTED_ALGEBRAIC_RESIDUAL"] =
        projected_algebraic_residual;
    metadata["NRPY_PARAMETER_NAMES"] = std::vector<std::string>{{
{parameter_literals}
    }};
    metadata["NRPY_PARAMETERS"] = json::object();
{parameter_writes}

    if (rank == 0) {{
        const std::string temporary_name = metadata_name.str() + ".tmp";
        std::ofstream output(temporary_name);
        if (!output) {{
            global_status = 1;
        }}  // END IF: metadata file open failed
        else {{
            output << std::setprecision(17) << std::setw(2) << metadata << '\\n';
            output.close();
            if (!output.good()) {{
                global_status = 1;
            }}  // END IF: metadata write failed
            else {{
                try {{
                    std::filesystem::rename(temporary_name, metadata_name.str());
                }}  // END TRY: publish metadata file
                catch (const std::filesystem::filesystem_error&) {{
                    global_status = 1;
                    std::filesystem::remove(temporary_name);
                }}  // END CATCH: metadata rename failure
            }}  // END ELSE: metadata written successfully
        }}  // END ELSE: metadata file opened
    }}  // END IF: rank 0 writes metadata
    MPI_Bcast(&global_status, 1, MPI_INT, 0, mesh->getMPICommunicator());
    return global_status;
}}  // END FUNCTION: {solver_stem}_write_checkpoint

int {solver_stem}_restore_checkpoint(
    const std::string& prefix,
    unsigned checkpoint_index,
    MPI_Comm global_communicator,
    const Point& domain_minimum,
    const Point& domain_maximum,
    ot::Mesh*& mesh,
    ot::DVector<DendroScalar, unsigned int>& state,
    const generated::params_struct& params,
    unsigned& iteration,
    DendroScalar& time,
    DendroScalar& time_step,
    std::array<Point, 2>& excision_centers,
    std::vector<DendroScalar>& black_hole_time_history,
    std::vector<std::array<DendroScalar, 6>>& black_hole_position_history,
    DendroScalar& black_hole_merge_time,
    bool& merged_checkpoint_written,
    DendroScalar algebraic_residual_tolerance) {{
    int global_rank = 0;
    int global_size = 0;
    MPI_Comm_rank(global_communicator, &global_rank);
    MPI_Comm_size(global_communicator, &global_size);

    std::ostringstream metadata_name;
    metadata_name << prefix << "_" << checkpoint_index << "_step.cp";
    json metadata;
    std::array<DendroScalar, 6> stored_excision_centers{{}};
    std::vector<DendroScalar> stored_black_hole_times;
    std::vector<std::array<DendroScalar, 6>> stored_black_hole_positions;
    DendroScalar stored_merge_time = 0.0;
    bool stored_merged_checkpoint_written = false;
    bool metadata_valid = std::filesystem::exists(metadata_name.str());
    try {{
        if (metadata_valid) {{
            std::ifstream input(metadata_name.str());
            metadata_valid = static_cast<bool>(input);
            if (metadata_valid) input >> metadata;
        }}  // END IF: read existing metadata file
        if (!metadata_valid) throw std::runtime_error("missing checkpoint metadata");
        const std::vector<std::string> expected_fields{{
{field_literals}
        }};
        metadata_valid =
            metadata.at("NRPY_FORMULATION").get<std::string>() ==
                "{formulation_name}" &&
            metadata.at("NRPY_FIELD_COUNT").get<unsigned>() ==
                generated::NUM_EVOL_GFS &&
            metadata.at("NRPY_FIELD_NAMES").get<std::vector<std::string>>() ==
                expected_fields;
        const std::vector<std::string> expected_parameters{{
{parameter_literals}
        }};
        if (metadata.at("NRPY_PARAMETER_NAMES")
                .get<std::vector<std::string>>() != expected_parameters) {{
            metadata_valid = false;
        }}  // END IF: parameter-name list mismatch
        const json& parameters = metadata.at("NRPY_PARAMETERS");
{parameter_checks}
        const DendroScalar stored_residual =
            metadata.at("NRPY_PROJECTED_ALGEBRAIC_RESIDUAL")
                .get<DendroScalar>();
        if (!std::isfinite(stored_residual) ||
            std::abs(stored_residual) > algebraic_residual_tolerance) {{
            metadata_valid = false;
        }}  // END IF: stored residual exceeds tolerance
        (void)metadata.at("NRPY_ITERATION").get<unsigned>();
        const DendroScalar stored_time =
            metadata.at("NRPY_TIME").get<DendroScalar>();
        const DendroScalar stored_time_step =
            metadata.at("NRPY_TIME_STEP").get<DendroScalar>();
        if (!std::isfinite(stored_time) || !std::isfinite(stored_time_step) ||
            stored_time_step <= 0.0) {{
            metadata_valid = false;
        }}  // END IF: invalid stored time data
        const unsigned stored_order =
            metadata.at("NRPY_ELEMENT_ORDER").get<unsigned>();
        const std::array<DendroScalar, 3> stored_minimum =
            metadata.at("NRPY_DOMAIN_MINIMUM")
                .get<std::array<DendroScalar, 3>>();
        const std::array<DendroScalar, 3> stored_maximum =
            metadata.at("NRPY_DOMAIN_MAXIMUM")
                .get<std::array<DendroScalar, 3>>();
        stored_excision_centers = metadata.at("NRPY_EXCISION_CENTERS")
            .get<std::array<DendroScalar, 6>>();
        stored_black_hole_times = metadata.at("NRPY_BH_HISTORY_TIMES")
            .get<std::vector<DendroScalar>>();
        stored_black_hole_positions =
            metadata.at("NRPY_BH_HISTORY_POSITIONS")
                .get<std::vector<std::array<DendroScalar, 6>>>();
        stored_merge_time = metadata.at("NRPY_BH_MERGE_TIME")
            .get<DendroScalar>();
        stored_merged_checkpoint_written =
            metadata.at("NRPY_MERGED_CHECKPOINT_WRITTEN").get<bool>();
        if (stored_black_hole_times.empty() ||
            stored_black_hole_times.size() !=
                stored_black_hole_positions.size() ||
            stored_black_hole_times.back() != stored_time ||
            !std::isfinite(stored_merge_time))
            metadata_valid = false;
        for (std::size_t index = 0;
             index < stored_black_hole_times.size(); ++index) {{
            if (!std::isfinite(stored_black_hole_times[index]) ||
                (index > 0 && stored_black_hole_times[index] <=
                                  stored_black_hole_times[index - 1]))
                metadata_valid = false;
            for (const DendroScalar coordinate :
                 stored_black_hole_positions[index])
                if (!std::isfinite(coordinate)) metadata_valid = false;
        }}  // END LOOP: for index over history entries
        if (!stored_black_hole_positions.empty() &&
            stored_black_hole_positions.back() != stored_excision_centers)
            metadata_valid = false;
        for (const DendroScalar coordinate : stored_excision_centers) {{
            if (!std::isfinite(coordinate)) metadata_valid = false;
        }}  // END LOOP: for coordinate over excision centers
        if (metadata.at("NRPY_ACTIVE_COMM_SIZE").get<unsigned>() == 0 ||
            (stored_order != 4 && stored_order != 6 && stored_order != 8) ||
            stored_minimum != std::array<DendroScalar, 3>{{
                domain_minimum.x(), domain_minimum.y(), domain_minimum.z()}} ||
            stored_maximum != std::array<DendroScalar, 3>{{
                domain_maximum.x(), domain_maximum.y(), domain_maximum.z()}}) {{
            metadata_valid = false;
        }}  // END IF: incompatible mesh or domain
    }}  // END TRY: parse checkpoint metadata
    catch (const std::exception&) {{
        metadata_valid = false;
    }}  // END CATCH: malformed metadata

    int local_status = metadata_valid ? 0 : 1;
    int global_status = 0;
    MPI_Allreduce(&local_status, &global_status, 1, MPI_INT, MPI_MAX,
                  global_communicator);
    if (global_status != 0) {{
        if (global_rank == 0) {{
            std::cerr << "Checkpoint metadata does not match {formulation_name}"
                      << std::endl;
        }}  // END IF: rank 0 reports mismatch
        return std::filesystem::exists(metadata_name.str()) ? 1 : 2;
    }}  // END IF: checkpoint metadata rejected

    const unsigned active_size =
        metadata.at("NRPY_ACTIVE_COMM_SIZE").get<unsigned>();
    const unsigned element_order =
        metadata.at("NRPY_ELEMENT_ORDER").get<unsigned>();
    if (active_size > static_cast<unsigned>(global_size)) return 1;

    const bool active = static_cast<unsigned>(global_rank) < active_size;
    MPI_Comm active_communicator = MPI_COMM_NULL;
    MPI_Comm_split(global_communicator, active ? 1 : MPI_UNDEFINED,
                   global_rank, &active_communicator);
    std::vector<ot::TreeNode> octree;
    local_status = 0;
    if (active) {{
        int active_rank = 0;
        MPI_Comm_rank(active_communicator, &active_rank);
        std::ostringstream octree_name;
        octree_name << prefix << "_" << checkpoint_index << "_octree_"
                    << active_rank << ".oct";
        local_status = io::checkpoint::readOctFromFile(
            octree_name.str().c_str(), octree);
    }}  // END IF: active rank reads octree
    MPI_Allreduce(&local_status, &global_status, 1, MPI_INT, MPI_MAX,
                  global_communicator);
    if (global_status != 0) {{
        if (active) MPI_Comm_free(&active_communicator);
        return 1;
    }}  // END IF: octree read failed

    ot::Mesh* restored_mesh = new ot::Mesh(
        octree, 1, element_order, active_size, global_communicator);
    restored_mesh->setDomainBounds(domain_minimum, domain_maximum);
    state.create_vector(restored_mesh, ot::DVEC_TYPE::OCT_SHARED_NODES,
                        ot::DVEC_LOC::HOST, generated::NUM_EVOL_GFS, true);

    if (active) {{
        int active_rank = 0;
        MPI_Comm_rank(active_communicator, &active_rank);
        std::array<DendroScalar*, generated::NUM_EVOL_GFS> variables{{}};
        state.to_2d(variables.data());
        std::ostringstream state_name;
        state_name << prefix << "_" << checkpoint_index << "_" << active_rank
                   << ".var";
        local_status = io::checkpoint::readVecFromFile(
            state_name.str().c_str(), restored_mesh, variables.data(),
            generated::NUM_EVOL_GFS);
        MPI_Comm_free(&active_communicator);
    }}  // END IF: active rank reads state
    MPI_Allreduce(&local_status, &global_status, 1, MPI_INT, MPI_MAX,
                  global_communicator);
    if (global_status != 0) {{
        state.destroy_vector();
        delete restored_mesh;
        return 1;
    }}  // END IF: state read failed

    mesh = restored_mesh;
    iteration = metadata.at("NRPY_ITERATION").get<unsigned>();
    time = metadata.at("NRPY_TIME").get<DendroScalar>();
    time_step = metadata.at("NRPY_TIME_STEP").get<DendroScalar>();
    excision_centers[0] = Point(
        stored_excision_centers[0], stored_excision_centers[1],
        stored_excision_centers[2]);
    excision_centers[1] = Point(
        stored_excision_centers[3], stored_excision_centers[4],
        stored_excision_centers[5]);
    black_hole_time_history = std::move(stored_black_hole_times);
    black_hole_position_history = std::move(stored_black_hole_positions);
    black_hole_merge_time = stored_merge_time;
    merged_checkpoint_written = stored_merged_checkpoint_written;
    return 0;
}}  // END FUNCTION: {solver_stem}_restore_checkpoint
// clang-format off
}}  // END NAMESPACE: {solver_namespace}
// clang-format on
"""
