# nrpy/infrastructures/Dendro/CMakeLists.py
"""
Emit registered CFunctions and the complete Dendro application build.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

import shlex
from pathlib import Path, PurePosixPath
from typing import Dict, Sequence

import nrpy.c_function as cfc


def output_CFunctions_function_prototypes_and_construct_CMakeLists(
    solver_name: str,
    solver_stem: str,
    solver_prefix: str,
    executable_name: str,
    application_sources: Sequence[str],
) -> Dict[str, str]:
    """
    Emit registered CFunctions, their declarations, and one explicit build.

    ``application_sources`` lists the application-owned sources that are not
    registered CFunctions, relative to the generated module root. Registered
    CFunctions are appended in sorted registry order. No source discovery or
    native Dendro-GR BSSN source is permitted.

    :param solver_name: Generated application directory name.
    :param solver_stem: Lowercase formulation stem used by generated headers.
    :param solver_prefix: Uppercase prefix used by CMake options.
    :param executable_name: Generated application executable name.
    :param application_sources: Explicit module-relative non-CFunction sources.
    :return: Mapping from generated path to file text.
    :raises ValueError: If a source is unsafe, duplicated, or native-BSSN-owned.
    """
    source_paths = []
    seen_sources = set()
    forbidden_fragments = (
        "BSSN_GR/",
        "bssn_common",
        "bssngr_main.cpp",
        "bssn_constraints.cpp",
        "grUtils.cpp",
        "rhs.cpp",
    )
    for source in application_sources:
        normalized = PurePosixPath(source).as_posix()
        path = PurePosixPath(normalized)
        if (
            path.is_absolute()
            or ".." in path.parts
            or normalized in ("", ".")
            or any(fragment in normalized for fragment in forbidden_fragments)
        ):
            raise ValueError(f"Invalid generated-application source {source!r}.")
        if normalized in seen_sources:
            raise ValueError(f"Duplicate generated-application source {source!r}.")
        source_paths.append(normalized)
        seen_sources.add(normalized)

    artifacts: Dict[str, str] = {}
    prototypes = [
        "// GENERATED FILE - DO NOT EDIT",
        "// AUTOMATICALLY GENERATED BY NRPy",
        f"#ifndef {solver_stem.upper()}_FUNCTION_PROTOTYPES_H",
        f"#define {solver_stem.upper()}_FUNCTION_PROTOTYPES_H",
        "",
        f'#include "{solver_stem}_parameters.h"',
        f'#include "{solver_stem}_state.h"',
        f'#include "{solver_stem}_types.h"',
        '#include "BHaH_defines.h"',
        '#include "aeh_bhahaha.h"',
        "",
        "namespace ot { class Block; class Mesh;",
        "// clang-format off",
        "}  // END NAMESPACE: ot",
        "// clang-format on",
        "",
    ]
    for name, cfunc in sorted(cfc.CFunction_dict.items()):
        subdirectory = PurePosixPath(cfunc.subdirectory).as_posix()
        if (
            PurePosixPath(subdirectory).is_absolute()
            or ".." in PurePosixPath(subdirectory).parts
        ):
            raise ValueError(
                f"Registered CFunction {name!r} has unsafe subdirectory "
                f"{cfunc.subdirectory!r}."
            )
        source = f"{subdirectory}/{name}.cpp"
        if source in seen_sources:
            raise ValueError(f"Duplicate emitted source {source!r}.")
        source_paths.append(source)
        seen_sources.add(source)
        artifacts[f"{solver_name}/{source}"] = cfunc.raw_function
        if (
            cfunc.subdirectory != "TwoPunctures"
            and name != "initialize_ID_persist_struct"
        ):
            prototypes.append(cfunc.function_prototype)
    prototypes.extend(
        [
            "",
            f"#endif  // {solver_stem.upper()}_FUNCTION_PROTOTYPES_H",
            "",
        ]
    )
    artifacts[
        f"{solver_name}/generated/include/{solver_stem}_function_prototypes.h"
    ] = "\n".join(prototypes)

    cmake_sources = [f'  "${{CMAKE_CURRENT_LIST_DIR}}/{path}"' for path in source_paths]
    artifacts[f"{solver_name}/CMakeLists.txt"] = "\n".join(
        [
            "# GENERATED FILE - DO NOT EDIT",
            "# AUTOMATICALLY GENERATED BY NRPy",
            "cmake_minimum_required(VERSION 3.16)",
            f"project({solver_name} C CXX Fortran)",
            "set(CMAKE_CXX_STANDARD 17)",
            "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
            "set(CMAKE_CXX_EXTENSIONS OFF)",
            'set(CPU_ARCH "native" CACHE STRING "Target CPU Architecture")',
            "set(CPU_ARCH_STRINGS native znver1 znver2 znver3 znver4",
            "    haswell broadwell skylake-avx512 cascadelake icelake-server",
            "    generic_avx2 x86-64-v3)",
            "set_property(CACHE CPU_ARCH PROPERTY STRINGS ${CPU_ARCH_STRINGS})",
            'if(CPU_ARCH STREQUAL "generic_avx2")',
            "  add_compile_options(-mavx2 -mfma)",
            "elseif(CPU_ARCH IN_LIST CPU_ARCH_STRINGS)",
            '  add_compile_options("-march=${CPU_ARCH}")',
            "else()",
            '  message(FATAL_ERROR "Unknown CPU_ARCH: ${CPU_ARCH}")',
            "endif()",
            "find_package(OpenMP REQUIRED)",
            "find_package(MPI REQUIRED COMPONENTS CXX)",
            "find_package(GSL REQUIRED)",
            "include(FetchContent)",
            "FetchContent_Declare(toml11",
            '  GIT_REPOSITORY "https://github.com/ToruNiina/toml11"',
            '  GIT_TAG "v4.4.0")',
            "FetchContent_MakeAvailable(toml11)",
            "FetchContent_Declare(dendrolib",
            '  GIT_REPOSITORY "https://github.com/paralab/Dendro-5.01"',
            '  GIT_TAG "master")',
            "FetchContent_MakeAvailable(dendrolib)",
            "",
            f"add_executable({executable_name}",
            *cmake_sources,
            ")",
            f"target_compile_features({executable_name} PRIVATE cxx_std_17)",
            f"target_compile_options({executable_name} PRIVATE -Wall",
            "                                                      -fext-numeric-literals)",
            f"target_include_directories({executable_name} PRIVATE",
            '  "${CMAKE_CURRENT_LIST_DIR}/include"',
            '  "${CMAKE_CURRENT_LIST_DIR}/generated/include"',
            '  "${CMAKE_CURRENT_LIST_DIR}/twopunctures/include"',
            ")",
            f"target_link_libraries({executable_name} PRIVATE",
            "  dendro5",
            "  MPI::MPI_CXX",
            "  GSL::gsl",
            "  toml11::toml11",
            "  m",
            ")",
            "",
            f'option({solver_prefix}_ENABLE_CUDA "Build a generated CUDA backend" OFF)',
            f"if({solver_prefix}_ENABLE_CUDA)",
            '  message(FATAL_ERROR "This generated application is CPU-qualified only")',
            "endif()",
            "",
        ]
    )
    return artifacts


def build_and_run_instructions(
    solver_dir: Path, executable_name: str, parfile: str
) -> str:
    """
    Return copy-paste commands that build and run a generated application.

    The application is a standalone CMake project that fetches Dendrolib and
    toml11. The commands build and run it inside its own directory.

    :param solver_dir: Generated application directory.
    :param executable_name: Generated application executable name.
    :param parfile: Parameter file, relative to ``solver_dir``.
    :return: Prerequisites and shell commands, one per line.

    Doctests:
    >>> print(build_and_run_instructions(Path("project/Dendro_NRPy_BSSN"), "nrpyBssnSolver", "pars/bssn.toml"))
    Prerequisites: CMake 3.16 or newer; GNU compilers (gcc, g++ with C++17,
    gfortran); MPI with C, C++, and Fortran bindings; OpenMP; GSL; BLAS and
    LAPACK; git and network access (CMake fetches Dendrolib, toml11, and spdlog
    on first configure).
    To build and run, copy and paste:
    <BLANKLINE>
    # 1. Enter the generated application directory.
    cd project/Dendro_NRPy_BSSN
    # 2. Configure the CMake project.
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    # 3. Compile the executable with four build jobs.
    cmake --build build --parallel 4
    # 4. Generate TwoPunctures initial data on one MPI rank.
    mpiexec -n 1 build/nrpyBssnSolver --tpid pars/bssn.toml
    # 5. Evolve the binary on four MPI ranks.
    mpiexec -n 4 build/nrpyBssnSolver pars/bssn.toml
    <BLANKLINE>
    The --tpid run solves the TwoPunctures initial data once, on one MPI rank;
    step 5 evolves it, with -n set to the MPI ranks to use. The
    default parameter file is a production binary-black-hole run. For a short
    test, add BSSN_MAX_ITERATIONS = 100 to the parameter file before step 5.
    >>> text = build_and_run_instructions(Path("my dir/Dendro_NRPy_BSSN"), "x", "p.toml")
    >>> [line for line in text.splitlines() if line.startswith("cd ")]
    ["cd 'my dir/Dendro_NRPy_BSSN'"]
    """
    solver_dir_quoted = shlex.quote(str(solver_dir))
    return f"""Prerequisites: CMake 3.16 or newer; GNU compilers (gcc, g++ with C++17,
gfortran); MPI with C, C++, and Fortran bindings; OpenMP; GSL; BLAS and
LAPACK; git and network access (CMake fetches Dendrolib, toml11, and spdlog
on first configure).
To build and run, copy and paste:

# 1. Enter the generated application directory.
cd {solver_dir_quoted}
# 2. Configure the CMake project.
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
# 3. Compile the executable with four build jobs.
cmake --build build --parallel 4
# 4. Generate TwoPunctures initial data on one MPI rank.
mpiexec -n 1 build/{executable_name} --tpid {parfile}
# 5. Evolve the binary on four MPI ranks.
mpiexec -n 4 build/{executable_name} {parfile}

The --tpid run solves the TwoPunctures initial data once, on one MPI rank;
step 5 evolves it, with -n set to the MPI ranks to use. The
default parameter file is a production binary-black-hole run. For a short
test, add BSSN_MAX_ITERATIONS = 100 to the parameter file before step 5."""


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()

    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    else:
        print(f"Doctest passed: All {results.attempted} test(s) passed")
