# nrpy/infrastructures/Dendro/cmake_helpers.py
"""
CMake emitters for a generated Dendro solver.

Every emitted name derives from the ``solver_name``, ``solver_prefix`` and
``exec_or_library_name`` arguments threaded from the calling example, matching
how BHaH threads ``project_name`` and ETLegacy threads ``thorn_name``.

Dendro's own conventions govern the emitted identifiers: the solver directory
carries the ``_GR`` suffix (``BSSN_GR``) while CMake variables and library
targets carry the bare formulation prefix (``BSSN_ENABLE_CUDA``,
``bssn_common``), and solver sources are named for the formulation
(``bssnCtx.cpp``), never for the framework.

No field list, physics parameter, finite-difference coefficient or numerical
loop appears here; the generated source list is read from the CFunction
registry.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from typing import List

from nrpy.infrastructures.Dendro import Dendro_self_tests_cpp, output_CFunctions

BANNER = (
    "# GENERATED FILE - DO NOT EDIT",
    "# AUTOMATICALLY GENERATED BY nrpy.infrastructures.Dendro.cmake_helpers",
)
SRC = "${CMAKE_CURRENT_SOURCE_DIR}"


def output_generated_sources_cmake(solver_prefix: str) -> str:
    """
    Emit ``generated/cmake/nrpy_generated_sources.cmake``.

    One entry per registered CFunction, in sorted name order.

    :param solver_prefix: Bare formulation prefix for CMake variables, e.g. ``BSSN`` for Dendro's own ``BSSN_GR``.
    :return: The CMake file text.
    """
    lines: List[str] = list(BANNER) + [
        f"# {solver_prefix}_MODULE_ROOT is set by the including scope so this list",
        "# is correct from either the solver or the tests directory.",
        f"set({solver_prefix}_NRPY_GENERATED_SOURCES",
    ]
    for path in output_CFunctions.CFunction_cmake_source_list():
        lines.append("  ${" + solver_prefix + "_MODULE_ROOT}/" + path)
    lines += [")", ""]
    return "\n".join(lines)


def output_solver_cmake(
    solver_name: str, solver_prefix: str, solver_stem: str, exec_or_library_name: str
) -> str:
    """
    Emit the generated solver's ``CMakeLists.txt``.

    :param solver_name: Solver directory and CMake project name, e.g. Dendro's own ``BSSN_GR``.
    :param solver_prefix: Bare formulation prefix for CMake variables, e.g. ``BSSN`` for Dendro's own ``BSSN_GR``.
    :param solver_stem: Lowercase stem the emitters use for solver file names.
    :param exec_or_library_name: Name of the solver executable target.
    :return: The CMake file text.

    Doctests:
    >>> text = output_solver_cmake("BSSN_GR", "BSSN", "bssn", "bssnSolver")
    >>> "project(BSSN_GR CXX)" in text
    True
    >>> "add_executable(bssnSolver" in text
    True
    >>> "${BSSN_NRPY_GENERATED_SOURCES}" in text
    True
    >>> "src/bssnCtx.cpp" in output_solver_cmake("Z_GR", "ZORP", "zrp", "zSolver")
    False
    >>> "src/zrpCtx.cpp" in output_solver_cmake("Z_GR", "ZORP", "zrp", "zSolver")
    True
    """
    # The file names come from solver_stem, which output_project also uses to
    # name the emitted sources; deriving a second stem from solver_prefix
    # would emit a target whose sources do not exist whenever the two differ.
    stem = solver_stem
    lines: List[str] = list(BANNER) + [
        "cmake_minimum_required(VERSION 3.13)",
        f"project({solver_name} CXX)",
        "",
        "# The solver lifecycle runs under MPI for the rank-agreement gates.",
        "# MPI is a standard host dependency, not Dendrolib; the real Dendro-GR",
        "# build also provides it.",
        "find_package(MPI REQUIRED COMPONENTS CXX)",
        "",
        f'option({solver_prefix}_USE_HOST_MOCK "Build against the NRPy mock Dendro host header" ON)',
        f"if(NOT {solver_prefix}_USE_HOST_MOCK)",
        '  message(FATAL_ERROR "This generated profile is mock-vehicle only.")',
        "endif()",
        "",
        f"set({solver_prefix}_MODULE_ROOT {SRC})",
        f"include({SRC}/generated/cmake/nrpy_generated_sources.cmake)",
        "",
        f"add_library({stem}_common OBJECT",
        f"  src/{stem}Ctx.cpp",
        "  ${" + solver_prefix + "_NRPY_GENERATED_SOURCES}",
        ")",
        "",
        f"target_compile_features({stem}_common PUBLIC cxx_std_17)",
        f"target_compile_options({stem}_common PRIVATE -Wall)",
        "",
        "# The mock host header is PRIVATE: it must not leak onto the include",
        "# path of every consumer of the solver.",
        f"target_include_directories({stem}_common PUBLIC",
        f"  {SRC}/include",
        f"  {SRC}/generated/include",
        ")",
        f"target_include_directories({stem}_common PRIVATE {SRC}/host_mock)",
        "",
        "# Linking the real Dendro-GR libraries would compile the mock host",
        "# doubles against the real host: refuse rather than build mismatched types.",
        "if(TARGET dendro5)",
        '  message(FATAL_ERROR "A real dendro5 target is present, but this'
        ' generated profile is mock-vehicle only.")',
        "endif()",
        "",
        f"if(TARGET {exec_or_library_name})",
        f'  message(STATUS "{exec_or_library_name} target already defined by the host")',
        "else()",
        f"  add_executable({exec_or_library_name} src/{stem}_main.cpp)",
        f"  target_include_directories({exec_or_library_name} PRIVATE {SRC}/host_mock)",
        f"  target_compile_options({exec_or_library_name} PRIVATE -Wall)",
        f"  target_link_libraries({exec_or_library_name} PRIVATE {stem}_common MPI::MPI_CXX)",
        "endif()",
        "",
        f'option({solver_prefix}_ENABLE_CUDA "Build a qualified generated CUDA backend" OFF)',
        f"if({solver_prefix}_ENABLE_CUDA)",
        '  message(FATAL_ERROR "This generated profile is CPU-qualified only")',
        "endif()",
        "",
        "enable_testing()",
        "add_subdirectory(tests)",
        "",
    ]
    return "\n".join(lines)


def output_tests_cmake(solver_prefix: str, solver_stem: str) -> str:
    """
    Emit the generated solver's ``tests/CMakeLists.txt``.

    The generated source list is included from the emitted CMake file, so this
    target never carries a source inventory.  Paths are relative to the tests
    directory, so the target is correct both in the standalone mock-vehicle
    build and when the solver is a subdirectory of a larger Dendro-GR project.

    :param solver_prefix: Bare formulation prefix for CMake variables, e.g. ``BSSN`` for Dendro's own ``BSSN_GR``.
    :param solver_stem: Lowercase stem the emitters use for solver file names.
    :return: The CMake file text.

    Doctests:
    >>> text = output_tests_cmake("BSSN", "bssn")
    >>> "include(${CMAKE_CURRENT_SOURCE_DIR}/../generated/cmake/nrpy_generated_sources.cmake)" in text
    True
    >>> "set(BSSN_MODULE_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/..)" in text
    True
    >>> "${BSSN_NRPY_GENERATED_SOURCES}" in text
    True
    >>> "add_test(NAME bssn_state" in output_tests_cmake("BSSN", "bssn")
    True
    """
    stem = solver_stem
    lines: List[str] = list(BANNER) + [
        f"set({solver_prefix}_MODULE_ROOT {SRC}/..)",
        f"include({SRC}/../generated/cmake/nrpy_generated_sources.cmake)",
        "add_executable(test_generated",
        f"  {SRC}/test_generated.cpp",
        "  ${" + solver_prefix + "_NRPY_GENERATED_SOURCES}",
        ")",
        "target_include_directories(test_generated PRIVATE",
        f"  {SRC}/../host_mock",
        f"  {SRC}/../include",
        f"  {SRC}/../generated/include",
        ")",
        "target_compile_features(test_generated PRIVATE cxx_std_17)",
        "",
    ]
    for section in Dendro_self_tests_cpp.SECTIONS:
        lines.append(
            f"add_test(NAME {stem}_{section} COMMAND test_generated {section})"
        )
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()
    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    print(f"Doctest passed: All {results.attempted} test(s) passed")
