# nrpy/infrastructures/Dendro/constants_h.py
"""
Emit the ``<stem>_constants.h`` header of generated compile-time constants.

The constants state the centered and Kreiss-Oliger finite-difference orders,
the ghost points their derivative operators reach, and whether the kernel
includes Kreiss-Oliger dissipation.  The caller passes the values recorded by
the kernel builder so the generated solver cannot disagree with its kernels.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from typing import List, Mapping, Optional, Sequence

BANNER = "// GENERATED FILE - DO NOT EDIT\n// AUTOMATICALLY GENERATED BY NRPy\n"


def output_constants_h(
    solver_stem: str,
    solver_namespace: str,
    fd_order: int,
    ko_fd_order: int,
    ko_effective_difference_order: int,
    required_padding: int,
    enable_KreissOliger_dissipation: bool,
    production_fd_orders: Sequence[int] = (),
    production_padding_by_order: Optional[Mapping[int, int]] = None,
) -> str:
    """
    Emit the generated constants header.

    It carries the numerical profile supplied by the kernel builder.  The
    builder computes the padding from the operators actually present, then
    checks it against the selected Dendro profile.  This emitter repeats that
    consistency check before writing the values.

    :param solver_stem: Lowercase formulation stem for the emitted header name.
    :param solver_namespace: NRPy-qualified solver namespace, e.g.
        ``nrpy::bssn``.
    :param fd_order: Centered finite-difference order.
    :param ko_fd_order: Base order supplied to NRPy's ``dKOD`` construction.
    :param ko_effective_difference_order: Actual even KO difference order.
    :param required_padding: Ghost points required on every axis.  Pass the
        exact reach the kernel builder recorded through
        finite-difference stencil reach verified by the kernel builder.
        Nothing here re-derives or bounds it: the coefficient-derived reach in
        ``nrpy.finite_difference.stencil_reach_per_axis`` is its only
        authority, so a caller that supplies some other number is emitting a
        padding this generator cannot vouch for.
    :param enable_KreissOliger_dissipation: Whether the emitted kernel carries
        Kreiss-Oliger dissipation, passed by the caller that built the kernels.
        It is recorded as ``KO_ENABLED`` so a reader of the generated header
        can tell which dissipation the kernel was lowered with.  Real-host
        profile validation compares ``ko_enabled`` with this constant, but no
        emitted numerical code reads it or derives a stencil reach from it.
        The emitted parameter file records the same switch as ``ko_enabled``.
    :param production_fd_orders: All finite-difference orders included in the
        generated application.
    :param production_padding_by_order: Required padding keyed by production
        finite-difference order.
    :return: The complete C++ header text.
    :raises ValueError: If the finite-difference order, KO order, effective KO
        difference order, and required padding do not define a supported
        Dendro profile.

    Doctests:
    >>> header = output_constants_h("bssn", "bssn", 4, 2, 4, 2, False)
    >>> "#ifndef BSSN_CONSTANTS_H" in header
    True
    >>> header.rstrip().endswith("#endif  // BSSN_CONSTANTS_H")
    True
    >>> from nrpy.helpers.generic import clang_format
    >>> "}  // END NAMESPACE: bssn::generated" in clang_format(header)
    True
    >>> "inline constexpr bool KO_ENABLED = false;" in header
    True
    >>> "inline constexpr unsigned REQUIRED_PADDING = 2;" in header
    True
    """
    fd_order = int(fd_order)
    padding = int(required_padding)
    ko_order = int(ko_fd_order)
    ko_effective_order = int(ko_effective_difference_order)
    if fd_order not in (4, 6, 8):
        raise ValueError(f"Unsupported Dendro FD_ORDER={fd_order}; allowed: (4, 6, 8).")
    if (
        ko_order != fd_order - 2
        or ko_effective_order != fd_order
        or padding != fd_order // 2
    ):
        raise ValueError(
            "Dendro profile must satisfy KO_FD_ORDER=FD_ORDER-2, "
            "KO_EFFECTIVE_DIFFERENCE_ORDER=FD_ORDER, and "
            "REQUIRED_PADDING=FD_ORDER/2."
        )
    guard = f"{solver_stem.upper()}_CONSTANTS_H"
    lines: List[str] = [
        BANNER.rstrip("\n"),
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    lines.append("#include <array>")
    lines.append("")
    lines.append(f"namespace {solver_namespace}::generated {{")
    lines.append("")
    lines.append(f"inline constexpr unsigned FD_ORDER = {fd_order};")
    lines.append(f"inline constexpr unsigned KO_FD_ORDER = {ko_order};")
    lines.append(
        f"inline constexpr unsigned KO_EFFECTIVE_DIFFERENCE_ORDER = {ko_effective_order};"
    )
    lines.append(f"inline constexpr unsigned REQUIRED_PADDING = {padding};")
    available = tuple(int(order) for order in production_fd_orders) or (fd_order,)
    padding_by_order = (
        {int(order): int(value) for order, value in production_padding_by_order.items()}
        if production_padding_by_order is not None
        else {fd_order: padding}
    )
    if tuple(sorted(padding_by_order)) != tuple(sorted(available)):
        raise ValueError("Production FD orders and padding map differ.")
    if any(padding_by_order[order] != order // 2 for order in available):
        raise ValueError("Every production FD order requires order/2 padding.")
    lines.append(
        f"inline constexpr std::array<unsigned, {len(available)}> PRODUCTION_FD_ORDERS = "
        "{" + ", ".join(str(order) for order in available) + "};"
    )
    lines.append(
        f"inline constexpr std::array<unsigned, {len(available)}> PRODUCTION_PADDING = "
        "{" + ", ".join(str(padding_by_order[order]) for order in available) + "};"
    )
    lines.append(
        f"inline constexpr std::array<unsigned, {len(available)}> PRODUCTION_KO_FD_ORDERS = "
        "{" + ", ".join(str(order - 2) for order in available) + "};"
    )
    lines.append(
        "inline constexpr std::array<unsigned, "
        f"{len(available)}> PRODUCTION_KO_EFFECTIVE_DIFFERENCE_ORDERS = "
        "{" + ", ".join(str(order) for order in available) + "};"
    )
    ko = "true" if enable_KreissOliger_dissipation else "false"
    lines.append(f"inline constexpr bool KO_ENABLED = {ko};")
    lines.append("")
    lines.append("// clang-format off")
    lines.append(f"}}  // END NAMESPACE: {solver_namespace}::generated")
    lines.append("// clang-format on")
    lines.append("")
    lines.append(f"#endif  // {guard}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()

    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    else:
        print(f"Doctest passed: All {results.attempted} test(s) passed")
