# nrpy/infrastructures/Dendro/Dendro_defines_h.py
"""
Emit the umbrella header included by generated Dendro kernels.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""


def output_Dendro_defines_h(solver_stem: str) -> str:
    """
    Emit ``<stem>_defines.h``, the one header every generated CFunction includes.

    :param solver_stem: Lowercase formulation stem for the generated header
        names, following Dendro's habit of naming solver files for the
        formulation (``bssnCtx.h``).
    :return: Complete C++ header text.
    """
    guard = f"{solver_stem.upper()}_DEFINES_H"
    return f"""// GENERATED FILE - DO NOT EDIT
// AUTOMATICALLY GENERATED BY NRPy
#ifndef {guard}
#define {guard}

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string_view>

#include "block.h"
#include "dendro.h"
#include "mesh.h"

#define GRIDX_TO_X(x_grid) (domain_min.x() + (domain_max.x() - domain_min.x()) * std::ldexp(static_cast<DendroScalar>(x_grid), -static_cast<int>(m_uiMaxDepth)))
#define GRIDY_TO_Y(y_grid) (domain_min.y() + (domain_max.y() - domain_min.y()) * std::ldexp(static_cast<DendroScalar>(y_grid), -static_cast<int>(m_uiMaxDepth)))
#define GRIDZ_TO_Z(z_grid) (domain_min.z() + (domain_max.z() - domain_min.z()) * std::ldexp(static_cast<DendroScalar>(z_grid), -static_cast<int>(m_uiMaxDepth)))

// clang-format off
#include "{solver_stem}_types.h"
#include "{solver_stem}_constants.h"
#include "{solver_stem}_parameters.h"
#include "{solver_stem}_state.h"
#include "{solver_stem}_function_prototypes.h"
// clang-format on

#endif  // {guard}
"""
