# nrpy/infrastructures/Dendro/Dendro_preamble_h.py
"""
Emit the preamble header every generated CFunction source includes.

It pulls in the host header, the generated scalar/state/parameter/constant
headers and the generated CFunction declarations, and defines the upwind
selection macro NRPy owns.  It carries no field name, no finite-difference
coefficient and no numerical loop.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

BANNER = (
    "// GENERATED FILE - DO NOT EDIT\n"
    "// AUTOMATICALLY GENERATED BY nrpy.infrastructures.Dendro.Dendro_preamble_h\n"
)


def output_Dendro_preamble_h(solver_stem: str) -> str:
    """
    Emit ``generated_project_preamble.h``.

    :param solver_stem: Lowercase formulation stem for the generated header
        names, following Dendro's habit of naming solver files for the
        formulation (``bssnCtx.h``).
    :return: The complete C++ header text.

    Doctests:
    >>> header = output_Dendro_preamble_h("bssn")
    >>> header.startswith("// GENERATED FILE - DO NOT EDIT")
    True
    >>> [line for line in header.splitlines() if line.startswith('#include "bssn')]
    ['#include "bssn_types.h"', '#include "bssn_constants.h"', '#include "bssn_parameters.h"', '#include "bssn_state.h"', '#include "bssn_cfunctions.h"']
    >>> "#define UPWIND_ALG(UpwindVecU) ((UpwindVecU) > 0.0 ? 1.0 : 0.0)" in header
    True
    """
    return BANNER + f"""#pragma once

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string_view>

#include "dendro_mock.h"

#include "{solver_stem}_types.h"
#include "{solver_stem}_constants.h"
#include "{solver_stem}_parameters.h"
#include "{solver_stem}_state.h"
#include "{solver_stem}_cfunctions.h"

// NRPy owns the upwind selection in the canonical backend, so the generated
// definition must win over any host definition -- matching
// nrpy/helpers/simd_intrinsics.h and cuda_intrinsics.h, which also #undef
// first.  A host macro with the opposite orientation would silently invert
// every advection term.
#ifdef UPWIND_ALG
#undef UPWIND_ALG
#endif
#define UPWIND_ALG(UpwindVecU) ((UpwindVecU) > 0.0 ? 1.0 : 0.0)
"""


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()
    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    print(f"Doctest passed: All {results.attempted} test(s) passed")
