# nrpy/infrastructures/Dendro/output_CFunctions.py
"""
Emit one generated source file per registered CFunction, plus their declarations.

Every artifact is read from the CFunction registry, as BHaH's
``Makefile_helpers`` and ETLegacy's ``make_code_defn`` do: the registered
``full_function`` becomes the file content after a generated-file banner,
declarations come from the registered prototypes, and the CMake source list is
derived from the same objects.  No signature is reconstructed, no loop is
wrapped, and no registered name is changed.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

import os
from typing import Dict, List, Tuple

import nrpy.c_function as cfc
import nrpy.params as par

BANNER = (
    "// GENERATED FILE - DO NOT EDIT\n"
    "// AUTOMATICALLY GENERATED BY nrpy.infrastructures.Dendro.output_CFunctions\n"
)


def registered_CFunctions() -> List[Tuple[str, cfc.CFunction]]:
    """
    Return the registered CFunctions in sorted name order.

    :return: ``(name, CFunction)`` pairs sorted by registered name.
    """
    return sorted(cfc.CFunction_dict.items())


def derived_source_path(name: str, subdirectory: str) -> str:
    """
    Derive the generated source path for one registered CFunction.

    The registered subdirectory is already solver-root-relative and includes the
    ``generated/src`` prefix, so the output path is exactly
    ``<registered-subdirectory>/<name>.cpp``.

    :param name: Registered CFunction name.
    :param subdirectory: Registered subdirectory for the CFunction.
    :return: Path relative to the solver root, with forward slashes.

    Doctests:
    >>> derived_source_path("bssn_rhs", "generated/src/rhs")
    'generated/src/rhs/bssn_rhs.cpp'
    """
    return f"{subdirectory.replace(os.sep, '/')}/{name}.cpp"


def output_CFunction_source(cfunc: cfc.CFunction) -> str:
    """
    Emit one generated CFunction source file.

    The registered ``full_function`` is written verbatim after the banner and a
    single preamble include supplying the host types, the generated state and
    parameter declarations, and the standard headers the body uses.

    :param cfunc: The registered CFunction to emit.
    :return: The complete source file text.
    """
    return (
        BANNER
        + '#include "generated_project_preamble.h"\n'
        + cfunc.full_function
        + "\n"
    )


def output_CFunction_declarations(solver_stem: str) -> str:
    """
    Emit the generated CFunction declaration header.

    One declaration per registered CFunction, from the registered prototype.

    :param solver_stem: Lowercase formulation stem for the emitted header names,
        following Dendro's own habit of naming solver files for the formulation
        (``bssnCtx.h``), never for the framework.
    :return: The complete C++ header text.
    """
    lines: List[str] = [BANNER.rstrip("\n"), "#pragma once", ""]
    lines.append(f'#include "{solver_stem}_types.h"')
    lines.append("")
    # Host types appear in registered prototypes.  Forward declarations keep the
    # header self-contained; the consuming translation unit includes the host
    # header for the complete types.
    lines.append("struct BlockGeometry;")
    lines.append("struct MockWorld;")
    lines.append("")
    for _name, cfunc in registered_CFunctions():
        lines.append(cfunc.function_prototype)
    lines.append("")
    return "\n".join(lines)


def CFunction_codeparameter_arguments(name: str) -> Tuple[str, ...]:
    """
    Return the registered CodeParameters in one CFunction's signature, in order.

    A host caller has to forward the same values in the same order.  Reading
    them back from the registered signature and the CodeParameter registry
    keeps the caller and the callee from drifting apart.

    :param name: Registered CFunction name.
    :return: The CodeParameter names the signature declares, in signature order.

    Doctests:
    >>> import nrpy.c_function as _cfc
    >>> import nrpy.params as _par
    >>> _ = _par.register_CodeParameter("REAL", __name__, "doctest_eta", 2.0)
    >>> _cfc.register_CFunction(
    ...     name="doctest_kernel",
    ...     desc="doctest",
    ...     params="const int n, const double doctest_eta",
    ...     body="(void) n; (void) doctest_eta;",
    ... )
    >>> CFunction_codeparameter_arguments("doctest_kernel")
    ('doctest_eta',)
    >>> del _cfc.CFunction_dict["doctest_kernel"]
    >>> del _par.glb_code_params_dict["doctest_eta"]
    """
    declared: List[str] = []
    for declarator in cfc.CFunction_dict[name].params.split(","):
        tokens = declarator.replace("*", " ").replace("&", " ").split()
        if tokens and tokens[-1] in par.glb_code_params_dict:
            declared.append(tokens[-1])
    return tuple(declared)


def CFunction_artifacts(solver_name: str, solver_stem: str) -> Dict[str, str]:
    """
    Emit all CFunction artifacts keyed by project-relative path.

    :param solver_name: Solver directory name, e.g. Dendro's own ``BSSN_GR``.
    :param solver_stem: Lowercase formulation stem for emitted header names.
    :return: Mapping of ``Dendro-GR/<solver_name>/<path>`` to file text.
    """
    prefix = f"Dendro-GR/{solver_name}/"
    artifacts: Dict[str, str] = {}
    for name, cfunc in registered_CFunctions():
        artifacts[prefix + derived_source_path(name, cfunc.subdirectory)] = (
            output_CFunction_source(cfunc)
        )
    artifacts[prefix + f"generated/include/{solver_stem}_cfunctions.h"] = (
        output_CFunction_declarations(solver_stem)
    )
    return artifacts


def CFunction_cmake_source_list() -> Tuple[str, ...]:
    """
    Derive the generated CMake source list from the registered CFunctions.

    :return: Solver-relative source paths, in sorted name order.
    """
    return tuple(
        derived_source_path(name, cfunc.subdirectory)
        for name, cfunc in registered_CFunctions()
    )


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()
    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    print(f"Doctest passed: All {results.attempted} test(s) passed")
