# nrpy/infrastructures/Dendro/param_toml.py
"""
Emit a q1-compatible parameter file for a generated Dendro application.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

from typing import List

import nrpy.grid as gri
import nrpy.params as par
from nrpy.infrastructures.Dendro import CodeParameters


def generate_default_parfile(
    solver_stem: str,
    profile_name: str,
    fd_order: int,
    ko_fd_order: int,
    ko_effective_difference_order: int,
    required_padding: int,
    enable_KreissOliger_dissipation: bool,
) -> str:
    """
    Emit one flat TOML parameter file accepted by the Dendro application.

    The file uses top-level key names from ``q1.par.lowres.toml``. The
    evolved conformal variable is selected at code generation; the
    TwoPunctures lapse is initialized to ``W=(psi_background+u)^(-2)``
    for either W or chi evolution. The generated eta default is one; an
    explicit ``ETA_CONST`` in another input file has normal TOML precedence.

    :param solver_stem: Lowercase formulation stem recorded in comments.
    :param profile_name: Name recorded for the generated numerical profile.
    :param fd_order: Centered finite-difference order.
    :param ko_fd_order: Base order supplied to NRPy's KO derivative.
    :param ko_effective_difference_order: Effective even KO difference order.
    :param required_padding: Required block padding on each side.
    :param enable_KreissOliger_dissipation: Enable the emitted KO profile.
    :return: Complete flat TOML text.
    :raises ValueError: If the finite-difference profile is unsupported or a
        runtime parameter type cannot be represented in TOML.
    """
    fd_order = int(fd_order)
    ko_fd_order = int(ko_fd_order)
    ko_effective_difference_order = int(ko_effective_difference_order)
    required_padding = int(required_padding)
    if (
        fd_order not in (4, 6, 8)
        or ko_fd_order != fd_order - 2
        or ko_effective_difference_order != fd_order
        or required_padding != fd_order // 2
    ):
        raise ValueError(
            "Dendro requires FD order 4, 6, or 8; KO base order FD-2; "
            "effective KO order FD; and padding FD/2."
        )

    lines: List[str] = [
        "# GENERATED FILE - DO NOT EDIT",
        "# AUTOMATICALLY GENERATED BY NRPy",
        f"# formulation = {solver_stem}",
        f"# profile = {profile_name}",
        f"# ko_fd_order = {ko_fd_order}",
        f"# ko_effective_difference_order = {ko_effective_difference_order}",
        f"# required_padding = {required_padding}",
        "",
        "BSSN_RESTORE_SOLVER = 0",
        f"BSSN_ELE_ORDER = {fd_order}",
        "BSSN_ID_TYPE = 0",
        "BSSN_RK_TIME_BEGIN = 0.0",
        "BSSN_RK_TIME_END = 700.0",
        'TPID_FILEPREFIX = "tp"',
        "TPID_REPLACE_LAPSE_WITH_SQRT_CHI = true",
        "ETA_CONST = 1.0",
    ]
    emitted_keys = {"ETA_CONST"}
    for name in CodeParameters.runtime_parameter_names():
        q1_name = CodeParameters.Q1_TOML_PARAMETER_NAMES.get(name, name)
        if q1_name in emitted_keys:
            continue
        code_parameter = par.glb_code_params_dict[name]
        base_type, _size, is_array = par.parse_cparam_type(code_parameter.cparam_type)
        value = code_parameter.defaultvalue
        if q1_name == "KO_DISS_SIGMA":
            value = 0.4 if enable_KreissOliger_dissipation else 0.0
        if is_array and base_type != "char":
            renderer = (
                (lambda element: str(int(element)))
                if base_type == "int"
                else (lambda element: repr(float(element)))
            )
            literal = "[" + ", ".join(renderer(element) for element in value) + "]"
        elif code_parameter.cparam_type == "bool":
            literal = "true" if bool(value) else "false"
        elif code_parameter.cparam_type == "int":
            literal = str(int(value))
        elif code_parameter.cparam_type in (
            "REAL",
            "float",
            "double",
            gri.DENDRO_SCALAR_TYPE,
        ):
            literal = repr(float(value))
        else:
            raise ValueError(
                f"No TOML mapping for {name!r} with type "
                f"{code_parameter.cparam_type!r}."
            )
        lines.append(f"{q1_name} = {literal}")
        emitted_keys.add(q1_name)
    lines.append("")
    return "\n".join(lines)
