# nrpy/infrastructures/Dendro/state_h.py
"""
Emit the generated state header for a Dendro solver.

The canonical evolved, Ricci-scratch, and diagnostic component lists are
defined here. Metadata values are read from the NRPy gridfunction registry.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

import math
from typing import List, Sequence, cast

import sympy as sp

import nrpy.grid as gri

BANNER = "// GENERATED FILE - DO NOT EDIT\n// AUTOMATICALLY GENERATED BY NRPy\n"

BSSN_EVOLVED_GRIDFUNCTIONS = (
    "alpha",
    "cf",
    "trK",
    "lambdaU0",
    "lambdaU1",
    "lambdaU2",
    "vetU0",
    "vetU1",
    "vetU2",
    "betU0",
    "betU1",
    "betU2",
    "hDD00",
    "hDD01",
    "hDD02",
    "hDD11",
    "hDD12",
    "hDD22",
    "aDD00",
    "aDD01",
    "aDD02",
    "aDD11",
    "aDD12",
    "aDD22",
)
FCCZ4_EVOLVED_GRIDFUNCTIONS = BSSN_EVOLVED_GRIDFUNCTIONS + ("Theta_fCCZ4",)
RICCI_GRIDFUNCTIONS = (
    "RbarDD00",
    "RbarDD01",
    "RbarDD02",
    "RbarDD11",
    "RbarDD12",
    "RbarDD22",
)
BSSN_DIAGNOSTIC_GRIDFUNCTIONS = (
    "H",
    "MU0",
    "MU1",
    "MU2",
    "M_CONSTRAINT",
    "LAMBDA_CONSTRAINT",
)
FCCZ4_DIAGNOSTIC_GRIDFUNCTIONS = (
    "H_Z4",
    "Z4constraintU0",
    "Z4constraintU1",
    "Z4constraintU2",
    "H",
    "MU0",
    "MU1",
    "MU2",
    "M_CONSTRAINT",
    "LAMBDA_CONSTRAINT",
)


def register_canonical_gridfunctions(enable_fCCZ4: bool) -> None:
    """
    Register the complete Dendro field layout before parallel code generation.

    Workers inherit this frozen layout, so every Ricci and evolution pointer
    index refers to the same field in the merged registry.

    :param enable_fCCZ4: Register the additional fCCZ4 fields when true.
    :raises ValueError: If the registry already contains a different layout.
    """
    if gri.glb_gridfcs_dict:
        validate_registered_state(enable_fCCZ4)
        expected_diagnostics = (
            FCCZ4_DIAGNOSTIC_GRIDFUNCTIONS
            if enable_fCCZ4
            else BSSN_DIAGNOSTIC_GRIDFUNCTIONS
        )
        registered_diagnostics = gri.GridFunction.gridfunction_lists()[2]
        if set(registered_diagnostics) != set(expected_diagnostics):
            raise ValueError(
                "Registered DIAG fields do not match the canonical Dendro "
                f"diagnostics: found={tuple(registered_diagnostics)}."
            )
        return

    for name in evolved_gridfunctions(enable_fCCZ4):
        rank = (
            2
            if name.startswith(("hDD", "aDD"))
            else 1 if name.startswith(("lambdaU", "vetU", "betU")) else 0
        )
        gri.register_gridfunctions(
            name,
            group="EVOL",
            rank=rank,
            is_basename=False,
            f_infinity=1.0 if name in ("alpha", "cf") else 0.0,
            wavespeed=float(sp.sqrt(2.0)) if name == "alpha" else 1.0,
        )
    for name in RICCI_GRIDFUNCTIONS:
        gri.register_gridfunctions(name, group="AUXEVOL", rank=2, is_basename=False)
    diagnostics = (
        FCCZ4_DIAGNOSTIC_GRIDFUNCTIONS
        if enable_fCCZ4
        else BSSN_DIAGNOSTIC_GRIDFUNCTIONS
    )
    for name in diagnostics:
        gri.register_gridfunctions(
            name,
            group="DIAG",
            rank=1 if name.startswith(("MU", "Z4constraintU")) else 0,
            is_basename=False,
        )
    validate_registered_state(enable_fCCZ4)


def evolved_gridfunctions(enable_fCCZ4: bool) -> Sequence[str]:
    """
    Return the frozen Dendro state order for one formulation.

    :param enable_fCCZ4: Select the fCCZ4 state when true.
    :return: Canonical evolved-gridfunction sequence.
    """
    return FCCZ4_EVOLVED_GRIDFUNCTIONS if enable_fCCZ4 else BSSN_EVOLVED_GRIDFUNCTIONS


def validate_registered_state(enable_fCCZ4: bool) -> None:
    """
    Require exact registered membership for the frozen state and Ricci scratch.

    :param enable_fCCZ4: Select the fCCZ4 state when true.
    :raises ValueError: If registered fields differ from the canonical layout.
    """
    registered_evol, registered_auxevol, _diag, _aux = (
        gri.GridFunction.gridfunction_lists()
    )
    expected_evol = evolved_gridfunctions(enable_fCCZ4)
    if set(registered_evol) != set(expected_evol):
        raise ValueError(
            "Registered EVOL fields do not match the canonical Dendro state: "
            f"missing={sorted(set(expected_evol) - set(registered_evol))}, "
            f"extra={sorted(set(registered_evol) - set(expected_evol))}."
        )
    if set(registered_auxevol) != set(RICCI_GRIDFUNCTIONS):
        raise ValueError(
            "Registered AUXEVOL fields must be exactly the six Ricci scratch "
            f"components; found={tuple(registered_auxevol)}."
        )


def dendro_state_name(gf_name: str) -> str:
    """
    Return the public Dendro state name of a registered NRPy gridfunction.

    NRPy's equations use the formulation-neutral name ``cf``. The generated
    Dendro state names that slot ``cf_W_or_chi``, because the selected
    formulation decides whether it stores W or chi. Every other name is the
    NRPy name. Role-prefixed stencil pointers (``in_``, ``rhs_``, ``out_``) keep
    the NRPy names that the core gridfunction reads emit.

    :param gf_name: Registered NRPy gridfunction name.
    :return: The name used by the generated state enumeration, name arrays,
        and checkpoint metadata.

    Doctests:
    >>> dendro_state_name("cf")
    'cf_W_or_chi'
    >>> dendro_state_name("alpha")
    'alpha'
    """
    return "cf_W_or_chi" if gf_name == "cf" else gf_name


def group_names(group: str) -> List[str]:
    """
    Return the registered gridfunction names in one group, in registry order.

    Read the core gridfunction registry at the point of use.

    :param group: Registry group name, one of ``EVOL``, ``AUXEVOL``, ``AUX``, ``DIAG``.
    :return: The group's gridfunction names, in NRPy registry order.
    :raises ValueError: If the group name is not a registered Dendro group.
    """
    evol, auxevol, diag, aux = gri.GridFunction.gridfunction_lists()
    names_by_group = {
        "EVOL": evol,
        "AUXEVOL": auxevol,
        "AUX": aux,
        "DIAG": diag,
    }
    if group not in names_by_group:
        raise ValueError(
            f"Unknown Dendro registry group {group!r}; expected one of "
            f"{', '.join(sorted(names_by_group))}."
        )
    return list(names_by_group[group])


def output_state_h(
    solver_stem: str, solver_namespace: str, *, enable_fCCZ4: bool = False
) -> str:
    """
    Emit the generated state header.

    It carries the EVOL enum, name array, per-field metadata, and exact public
    Dendro-name lookup over every registered group. Canonical sequences above
    set the evolved, Ricci, and diagnostic orders; auxiliary fields retain
    registry order. :func:`dendro_state_name` supplies each public Dendro name,
    and each :class:`nrpy.grid.DendroGridFunction` supplies its metadata.

    :param solver_stem: Lowercase formulation stem for emitted header names.
    :param solver_namespace: NRPy-qualified solver namespace, e.g.
        ``nrpy::bssn``.
    :param enable_fCCZ4: Select the fCCZ4 state when true.
    :return: The complete C++ header text.
    """
    validate_registered_state(enable_fCCZ4)
    evol = [
        (index, name, cast(gri.DendroGridFunction, gri.glb_gridfcs_dict[name]))
        for index, name in enumerate(evolved_gridfunctions(enable_fCCZ4))
    ]
    lines: List[str] = []
    guard = f"{solver_stem.upper()}_STATE_H"
    lines.append(BANNER.rstrip("\n"))
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstddef>")
    lines.append("#include <optional>")
    lines.append("#include <string_view>")
    lines.append("")
    lines.append(f'#include "{solver_stem}_types.h"')
    lines.append("")
    lines.append(f"namespace {solver_namespace}::generated {{")
    lines.append("")
    lines.append("enum class EvolVar : unsigned {")
    for index, name, _gf in evol:
        lines.append(f"    {dendro_state_name(name)} = {index},")
    lines.append("    END,")
    lines.append("};  // END ENUM: EvolVar")
    lines.append("")
    lines.append(
        "[[nodiscard]] inline constexpr unsigned to_index(EvolVar value) noexcept {"
    )
    lines.append("    return static_cast<unsigned>(value);")
    lines.append("}")
    lines.append("")
    lines.append("inline constexpr unsigned NUM_EVOL_GFS = to_index(EvolVar::END);")
    lines.append("")
    lines.append(
        "inline constexpr std::array<std::string_view, NUM_EVOL_GFS> EVOL_GF_NAMES = {"
    )
    for _index, name, _gf in evol:
        lines.append(f'    "{dendro_state_name(name)}",')
    lines.append("};  // END ARRAY: EVOL_GF_NAMES")
    lines.append("")
    lines.append("static_assert(NUM_EVOL_GFS == EVOL_GF_NAMES.size());")
    lines.append("")
    # The emitter also produces rank, asymptotic value and
    # wavespeed metadata, rendered from the registered gridfunction records.  The
    # host needs these in C++ (outer boundaries need f_infinity, a CFL step
    # needs the wavespeed); anything less would force a hand-maintained
    # table that could drift from the registry.
    lines.append("inline constexpr std::array<unsigned, NUM_EVOL_GFS> EVOL_GF_RANK = {")
    for _index, _name, gf in evol:
        lines.append(f"    {int(gf.rank)},")
    lines.append("};  // END ARRAY: EVOL_GF_RANK")
    lines.append("")
    scalar_type = gri.DENDRO_SCALAR_TYPE
    lines.append(
        f"inline constexpr std::array<{scalar_type}, NUM_EVOL_GFS>"
        " EVOL_GF_F_INFINITY = {"
    )
    for _index, name, gf in evol:
        lines.append(
            f"    {_cxx_scalar_literal(str(gf.f_infinity), name, 'f_infinity')},"
        )
    lines.append("};  // END ARRAY: EVOL_GF_F_INFINITY")
    lines.append("")
    lines.append(
        f"inline constexpr std::array<{scalar_type}, NUM_EVOL_GFS>"
        " EVOL_GF_WAVESPEED = {"
    )
    for _index, name, gf in evol:
        lines.append(
            f"    {_cxx_scalar_literal(str(gf.wavespeed), name, 'wavespeed')},"
        )
    lines.append("};  // END ARRAY: EVOL_GF_WAVESPEED")
    lines.append("")
    # The strict, case-sensitive exact-name lookup.
    # Matching is case-sensitive because NRPy tensor-variance suffixes are, and
    # an unknown name resolves to an empty optional rather than to a silently
    # wrong index.  Reporting an unknown name is the caller's obligation;
    # variable_count and variable_name let it list every valid generated name
    # without a second table.
    by_group = {
        "EVOL": list(evolved_gridfunctions(enable_fCCZ4)),
        "AUXEVOL": list(RICCI_GRIDFUNCTIONS),
        "AUX": group_names("AUX"),
        "DIAG": list(
            FCCZ4_DIAGNOSTIC_GRIDFUNCTIONS
            if enable_fCCZ4
            else BSSN_DIAGNOSTIC_GRIDFUNCTIONS
        ),
    }
    # The member names and their order are fixed:
    # evolved, diagnostic, auxevol, auxiliary.  "evolved" is rendered above.
    groups = (
        ("DIAG", "DIAG_GF_NAMES", "NUM_DIAG_GFS", "DIAG"),
        ("AUXEVOL", "AUXEVOL_GF_NAMES", "NUM_AUXEVOL_GFS", "AUXEVOL"),
        ("AUX", "AUX_GF_NAMES", "NUM_AUX_GFS", "AUX"),
    )
    for group, array_name, count_name, _member in groups:
        names = by_group.get(group, [])
        entries = "".join(f'    "{dendro_state_name(name)}",\n' for name in names)
        lines.append(
            f"inline constexpr unsigned {count_name} = {len(names)};\n"
            f"inline constexpr std::array<std::string_view, {count_name}>"
            f" {array_name} = {{\n"
            f"{entries}"
            f"}};  // END ARRAY: {array_name}\n"
        )
    members = "\n".join(f"        {member}," for _g, _a, _c, member in groups)
    count_cases = "\n".join(
        f"        case VariableRef::Group::{member}: return {count_name};"
        for _g, _a, count_name, member in groups
    )
    name_cases = "\n".join(
        f"        case VariableRef::Group::{member}:"
        f" return index < {count_name} ? {array_name}[index]"
        # An empty but non-null view: a null data() reaches printf-family
        # callers, which -Wnonnull / -Wformat-overflow reject under -O2.
        ' : std::string_view{""};'
        for _g, array_name, count_name, member in groups
    )
    group_members = "\n".join(
        f"    VariableRef::Group::{member}," for _g, _a, _c, member in groups
    )
    lines.append(rf"""// Strict, case-sensitive exact-name selection.
struct VariableRef {{
    enum class Group : unsigned {{
        evolved,
{members}
    }} group;  // END ENUM: generated variable groups
    unsigned index;
}};  // END STRUCT: exact-name reference

[[nodiscard]] inline constexpr unsigned variable_count(VariableRef::Group group) noexcept {{
    switch (group) {{
        case VariableRef::Group::evolved: return NUM_EVOL_GFS;
{count_cases}
    }}  // END SWITCH: generated group cardinality
    return 0;
}}  // END FUNCTION: variable_count

[[nodiscard]] inline constexpr std::string_view variable_name(VariableRef::Group group, unsigned index) noexcept {{
    switch (group) {{
        case VariableRef::Group::evolved: return index < NUM_EVOL_GFS ? EVOL_GF_NAMES[index] : std::string_view{{""}};
{name_cases}
    }}  // END SWITCH: generated group name array
    return std::string_view{{""}};
}}  // END FUNCTION: variable_name

inline constexpr std::array<VariableRef::Group, {len(groups) + 1}> VARIABLE_GROUPS = {{
    VariableRef::Group::evolved,
{group_members}
}};  // END ARRAY: VARIABLE_GROUPS

[[nodiscard]] inline constexpr std::optional<VariableRef> find_variable(std::string_view exact_name) noexcept {{
    for (const VariableRef::Group group : VARIABLE_GROUPS) {{
        const unsigned count = variable_count(group);
        for (unsigned index = 0; index < count; ++index) {{
            if (variable_name(group, index) == exact_name) {{
                return VariableRef{{group, index}};
            }}  // END IF: exact name matched
        }}  // END LOOP: for index over group
    }}  // END LOOP: for group over all groups
    return std::nullopt;
}}  // END FUNCTION: find_variable
""")
    lines.append("// clang-format off")
    lines.append(f"}}  // END NAMESPACE: {solver_namespace}::generated")
    lines.append("// clang-format on")
    lines.append("")
    lines.append(f"#endif  // {guard}")
    lines.append("")
    return "\n".join(lines)


def _cxx_scalar_literal(value: str, gf_name: str, field: str) -> str:
    """
    Render one registered scalar metadata value as a C++ floating-point literal.

    :param value: The registered metadata value.
    :param gf_name: Gridfunction name (for the error message).
    :param field: Record field name (for the error message).
    :return: A C++ literal.
    :raises ValueError: If the value is not a finite real number, which would
        otherwise emit an uncompilable symbolic expression such as ``sqrt(2)``.
    """
    try:
        number = float(value)
    except (TypeError, ValueError):
        try:
            number = float(cast(sp.Expr, sp.sympify(value)))
        except (TypeError, ValueError, AttributeError) as exc:
            raise ValueError(
                f"Gridfunction {gf_name!r} has non-numeric {field} {value!r}: "
                "generated metadata must be a finite real number."
            ) from exc
    if not math.isfinite(number):
        raise ValueError(f"Gridfunction {gf_name!r} has non-finite {field} {value!r}.")
    return repr(number)


if __name__ == "__main__":
    import doctest
    import sys

    results = doctest.testmod()

    if results.failed > 0:
        print(f"Doctest failed: {results.failed} of {results.attempted} test(s)")
        sys.exit(1)
    else:
        print(f"Doctest passed: All {results.attempted} test(s) passed")
