# nrpy/infrastructures/Dendro/types_h.py
"""
Emit the scalar aliases used by a generated Dendro application.

Author: Zachariah B. Etienne
        zachetie **at** gmail **dot* com
"""

import nrpy.grid as gri
import nrpy.params as par


def output_types_h(solver_stem: str, solver_namespace: str) -> str:
    """
    Emit ``<solver_stem>_types.h``.

    :param solver_stem: Lowercase formulation stem used by generated filenames.
    :param solver_namespace: Namespace that owns the generated application.
    :return: Complete C++ header text.
    """
    scalar_type = gri.DENDRO_SCALAR_TYPE
    fp_type = str(par.parval_from_str("fp_type"))
    guard = f"{solver_stem.upper()}_TYPES_H"
    return f"""// GENERATED FILE - DO NOT EDIT
// AUTOMATICALLY GENERATED BY NRPy
#ifndef {guard}
#define {guard}

#include <type_traits>

#if !defined(DENDRO_SCALAR_DEFINED) && !defined(DendroScalar)
#define DENDRO_SCALAR_DEFINED
using {scalar_type} = {fp_type};
#endif

namespace {solver_namespace}::generated {{

using NRPyArithmetic = {fp_type};
using TargetScalar = {scalar_type};

static_assert(sizeof(TargetScalar) == sizeof(NRPyArithmetic),
              "generated scalar type: width mismatch");
static_assert(std::is_same_v<TargetScalar, NRPyArithmetic>,
              "generated scalar type: alias must be the registered fp_type");

// clang-format off
}}  // END NAMESPACE: {solver_namespace}::generated
// clang-format on

#endif  // {guard}
"""
